- .github/ISSUE_TEMPLATE/bug_report.yml
In template bug_report need to change description about virtualization version
When you create an issue, the description shows the deckhouse version instead of the virtualization version.
> chore(templates): fix description bug_report template

- .github/workflows/build_dev.yml
- .github/workflows/build_dev_self_hosted.yml
- .prettierignore
- Taskfile.yaml
- api/Taskfile.dist.yaml
- hooks/Taskfile.yaml
- images/virtualization-artifact/Taskfile.cvmi.yaml
- images/virtualization-artifact/Taskfile.dist.yaml
- images/virtualization-artifact/Taskfile.init.yaml
- images/virtualization-artifact/Taskfile.vmi.yaml
- tests/e2e/Taskfile.yaml
Using a docker image instead of installing nodejs and prettier
> ci: change prettier lint to docker

- .github/workflows/build_dev.yml
- .github/workflows/build_dev_self_hosted.yml
Fix of workflow "Build and push for dev" for correct linting of yaml files
The task should only check files in PR
> ci: add ref into job lint_yaml

- virtualization-dashboard.yaml
add virtualization dashboard for performance tests
> feat(tests): add virtualization dashboard

- tests/performance/templates/nginx-service.yaml
- tests/performance/templates/node-exporter-service.yaml
- tests/performance/values.yaml
Fixed labels binding for service, ingress and servicemonitor
> fix: fixed ingress and service monitor

- tests/performance/Taskfile.yaml
- tests/performance/bootstrapper.sh
Fixed storage class and count processing
> fix: fixed storage class and count processing

- tests/performance/virtualization-dashboard.yaml
> fix(metrics): remove duplicated metrics

- .github/workflows/build_dev.yml
- .github/workflows/build_dev_self_hosted.yml
First step to migrate from v0.0.0-main tag to main tag 
Improve develop
> ci: add push main tag for main branch

- tests/performance/virtual-machine-dashboard.yaml
> feat(metrics): add node-exporter dashboard for virtual machine

- .github/workflows/validation.yaml
- Taskfile.yaml
- tests/e2e/Taskfile.yaml
- tools/validation/diff.go
- tools/validation/doc_changes.go
- tools/validation/main.go
- tools/validation/messages.go
- tools/validation/no_cyrillic.go
- tools/validation/no_cyrillic_test.go
Add validation doc-changes
If there are changes in the documentation, they should be in RU and EN files.
> ci: doc-changes validation

- tests/performance/templates/_cloud-config.tpl
Sometimes packages can't be installed with cloud init process.
> refactor(bootstrapper): replace ubuntu deb repo with yandex mirror

- tests/performance/templates/node-exporter-service.yaml
> fix(performance-test): change pod/service match label

- tests/performance/virtualization-dashboard.yaml
Add dashboards with VM pods stat.
Need more information
> chore(perf): add vm's pod phases info

- images/pre-delete-hook/entrypoint.sh
Failed hook leads to a deadlock in module lifecycle.
> fix(pre-delete-hook): hook should not fail

- .github/workflows/auto-author-assign.yml
- .github/workflows/build_dev.yml
- .github/workflows/build_dev_self_hosted.yml
- .github/workflows/build_prod.yml
- .github/workflows/cleanup_dev.yml
- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/validation.yaml
- .prettierignore
In most cases, the pull request author should be assigned as an assignee of the pull request.
This action automatically assigns the pull request author as an assignee.
> ci: add ci auto-author-assign

- .github/workflows/build_dev.yml
> chore: build_dev.yml cleanup

- images/kube-api-proxy/cmd/kube-api-proxy/main.go
- images/kube-api-proxy/go.mod
- images/kube-api-proxy/go.sum
- images/kube-api-proxy/pkg/server/http_server.go
- images/kube-api-proxy/pkg/target/webhook.go
- images/kube-api-proxy/pkg/tls/certmanager/certmanager.go
- images/kube-api-proxy/pkg/tls/certmanager/filesystem/file-cert-manager.go
- images/kube-api-proxy/pkg/tls/util/util.go
- images/virtualization-artifact/pkg/tls/util/util.go
> feat(kube-api-proxy): add certmanager

- CONTRIBUTING.md
> docs(contributing): add commit, branch, and PR name conventions

- .github/workflows/dev_module_build-on-self-hosted-runner.yml
- .github/workflows/dev_module_build.yml
- .github/workflows/dev_validation.yaml
- images/virtualization-artifact/Taskfile.dist.yaml
> chore(ci): fix ci and rm description in taskfile

- .github/workflows/dev_build-main.yml
Warming up the cache of the main branch
> chore(ci): Add workflow 'Build main every 8 hours for dev'

- images/kube-api-proxy/pkg/proxy/handler.go
- images/kube-api-proxy/pkg/rewriter/discovery.go
- images/kube-api-proxy/pkg/rewriter/discovery_test.go
- images/kube-api-proxy/pkg/rewriter/rule_rewriter.go
Implement rewriting for aggregated discovery.
> feat(proxy): add rewriter for APIGroupDiscoveryList

- .github/workflows/dev_build-main.yml
- .github/workflows/dev_module_build.yml
> chore(ci): add branch pre-alfa in build workflow

- .github/workflows/ dev_build_precache.yml
- .github/workflows/dev_module_build.yml
> refactor(ci): add build for pre-alpha, rename workflow for warmup cache

- images/kube-api-proxy/pkg/rewriter/rbac.go
- images/kube-api-proxy/pkg/rewriter/rule_rewriter.go
- images/kube-api-proxy/pkg/rewriter/target_request.go
add more resources for rewrite owner refs
> refactor(kube-api-rewriter): add more resources for rewrite owner refs

- docs/README.md
- docs/README_RU.md
- templates/user-authz-cluster-roles.yaml
Fix user API RBAC
We need the correct permissions for the different user roles
The following roles will be created for the module resources:
- User
- PrivelegedUser
- Editor
- Admin
- ClusterEditor
- ClusterAdmin
> fix(module): fix user API RBAC

- tests/performance/ceph-dashboard.yaml
Add ceph dashboard for grafana
Increased system observability
> chore(tests): add ceph dashboard for grafana

- images/base-alt-p10/werf.inc.yaml
- images/cdi-apiserver/werf.inc.yaml
- images/cdi-cloner/werf.inc.yaml
- images/cdi-controller/werf.inc.yaml
- images/cdi-importer/werf.inc.yaml
- images/cdi-operator/werf.inc.yaml
- images/cdi-uploadproxy/werf.inc.yaml
- images/cdi-uploadserver/werf.inc.yaml
- images/libguestfs/werf.inc.yaml
- images/virt-exportproxy/werf.inc.yaml
- images/virt-exportserver/werf.inc.yaml
- images/virt-handler/werf.inc.yaml
- images/virt-launcher/libvirt.conf
- images/virt-launcher/werf.inc.yaml
Use alt-linux and base-scratch as base runtime environments.
> chore(core): build images on alt-linux and base-scratch

- images/kube-api-proxy/pkg/kubevirt/kubevirt_rules.go
- DVP is a product name, use more generic prefix
> refactor(kube-api-rewriter): remove dvp prefixes

- .github/workflows/dev_build_precache.yml
Fix [PR 140](https://github.com/deckhouse/virtualization/pull/140)
> chore(ci): remove unnecessary branch, fix Set vars step

- .github/workflows/dev_auto-pr-author-assign.yml
- .github/workflows/dev_build_precache.yml
- .github/workflows/dev_module_build-and-registration.yml
- .github/workflows/dev_module_build-on-self-hosted-runner.yml
- .github/workflows/dev_module_build.yml
- .github/workflows/dev_registry-cleanup.yml
- .github/workflows/release_module_build-and-registration.yml
- .github/workflows/release_module_release-channels.yml
- .github/workflows/release_release-please.yml
- tools/addlicense/addlicense_test.go
- tools/addlicense/utils.go
- tools/addlicense/variables.go
Fix [PR 114](https://github.com/deckhouse/virtualization/pull/114)
Adding copyright to files in the .github folder
> chore(ci): fix tool addlicense

- api/client/kubeclient/async.go
- api/client/kubeclient/config.go
- api/client/kubeclient/request.go
- api/client/kubeclient/streamer.go
- api/client/kubeclient/vm.go
- api/client/kubeclient/websocket.go
Fix CE license text in some files
Copyright text must be the same
> chore: fix ce license text

- images/virtualization-artifact/pkg/controller/vi/internal/source/http.go
- images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go
- images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go
> fix(vi): fix status target

- images/virtualization-artifact/pkg/controller/cvi/cvi_reconciler.go
- images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go
- images/virtualization-artifact/pkg/controller/vi/vi_reconciler.go
Fixed pvc watching: added a vd request if pvc has entered a bound phase
Disks&Images: requeue in 2 second instead of 5
> fix(vd): fix pvc watching

- images/virtualization-artifact/pkg/controller/vm/internal/provisioning.go
do not check keys for sysprep secret
> fix(vm):  do not check keys for sysprep secret

- images/virtualization-artifact/pkg/controller/vm/internal/provisioning.go
> fix(vm): check secret keys

- images/kube-api-proxy/pkg/rewriter/metadata.go
- fix KVVM deletion: virt-controller can't remove original finalizer
> refactor(kubevirt): support renamings of JSON patches with /metadata path

- images/virtualization-artifact/pkg/controller/vm_reconciler.go
- images/virtualization-artifact/pkg/controller/vm_reconciler_state.go
Clean irrelevant changes from status.
> fix(vm): clean awaiting changes

- images/virtualization-artifact/Taskfile.dist.yaml
- images/virtualization-artifact/cmd/virtualization-controller/main.go
- images/virtualization-artifact/hack/args.sh
- images/virtualization-artifact/hack/pyroscope.sh
- images/virtualization-artifact/hack/pyroscope/config.alloy
- images/virtualization-artifact/hack/pyroscope/docker-compose.yaml
- images/virtualization-artifact/hack/pyroscope/endpoints.json
- templates/virtualization-controller/_helpers.tpl
- templates/virtualization-controller/deployment.yaml
- templates/virtualization-controller/service.yaml
> feat(controller): add pprof

- images/virtualization-artifact/pkg/controller/vd/vd_controller.go
- images/virtualization-artifact/pkg/monitoring/metrics/vd/collector.go
Add phase collector for virtual disk
> fix(vd): add phase collector

- images/kube-api-proxy/pkg/proxy/handler.go
- images/kube-api-proxy/pkg/proxy/stream_handler.go
> refactor(kube-api-rewriter): change log level to debug to reduce info log noise

- images/virtualization-artifact/pkg/controller/kvapi/kvapi.go
- images/virtualization-artifact/pkg/controller/service/attachment_service.go
- images/virtualization-artifact/pkg/controller/vm/internal/provisioning.go
- images/virtualization-artifact/pkg/controller/vmbda/internal/life_cycle.go
fix validating keys for sysprep
fix hotplug panic if kvvm doesn't exist
> fix(vd, vm): fix sysprep and hotplug

- .github/workflows/dev_registry-cleanup.yml
- werf_cleanup.yaml
Improved dev-registry cleanup for virtualization
> chore(ci): add werf cleanup policy

- images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go
- images/virtualization-artifact/pkg/controller/vm/internal/stats.go
- images/virtualization-artifact/pkg/controller/vm/vm_controller.go
- images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go
add statisticHandler
We need to display statistics on the virtual machine
> feat(vm): add statisticHandler

- .github/scripts/fetch_prs.mjs
- .github/scripts/package.json
- .github/workflows/dev_prs-summary.yml
Notification to the team of pending and required PRs
Notofication schedule on every day-of-week from Monday through Friday
Improve PRs review speed
> chore(ci): pr summary notofication

- docs/internal/kube_api_rewriter_diag.md
Add notes on kube-api-rewriter troubleshooting.
Share kube-api-rewriter internal knowledge.
> refactor(kube-api-rewriter): troubleshooting docs

- images/virtualization-artifact/pkg/controller/vmbda/internal/life_cycle.go
> fix(vmbda): fix panic

- images/virtualization-artifact/pkg/controller/cvi/cvi_controller.go
- images/virtualization-artifact/pkg/controller/vd/vd_controller.go
- images/virtualization-artifact/pkg/controller/vi/vi_controller.go
- images/virtualization-artifact/pkg/controller/vm/vm_controller.go
- images/virtualization-artifact/pkg/controller/vmbda/vmbda_controller.go
- images/virtualization-artifact/pkg/controller/vmclass/vmclass_controller.go
- images/virtualization-artifact/pkg/controller/vmip/vmip_controller.go
- images/virtualization-artifact/pkg/controller/vmiplease/vmiplease_controller.go
- images/virtualization-artifact/pkg/controller/vmop/vmop_controller.go
add panic recovery in all controllers
> feat(controller): add recovery

- images/virtualization-artifact/Taskfile.dist.yaml
- images/virtualization-artifact/hack/pyroscope/config.alloy
- images/vm-route-forge/cmd/vm-route-forge/app/options/options.go
- images/vm-route-forge/cmd/vm-route-forge/app/root.go
- images/vm-route-forge/internal/cache/cache.go
- images/vm-route-forge/internal/controller/route/host.go
- images/vm-route-forge/internal/controller/route/route_controller.go
- images/vm-route-forge/internal/netlinkmanager/manager.go
- images/vm-route-forge/internal/server/server.go
- templates/kubevirt/vm-route-forge/daemonset.yaml
- templates/kubevirt/vm-route-forge/service.yaml
add pprof server
need in profiling vm-route-forge
> feat(vm-route-forge): add pprof server

- .github/workflows/release_module_build-and-registration.yml
- .github/workflows/release_module_release-channels.yml
- Put checkout before removing unwanted software
- Add fetch 0 to efficiently build with werf.
> fix(ci): checkout before removing unwanted software

- docs/FAQ.md
- docs/FAQ_RU.md
Add examples with security policies which are required for virtual machine running.
> docs(module): add "admission-policy-engine and vm" to faq

- openapi/config-values.yaml
- openapi/doc-ru-config-values.yaml
Remove deprecated vmipCIDRs from module config
> fix(module): remove deprecated vmipCIDRs from module config

- crds/virtualmachine.yaml
Add 'need restart' and 'agent' status to brief output
> fix(module): add 'need restart' and 'agent' status to brief output

- images/cdi-apiserver/werf.inc.yaml
- images/cdi-cloner/werf.inc.yaml
- images/cdi-controller/werf.inc.yaml
- images/cdi-importer/werf.inc.yaml
- images/cdi-operator/werf.inc.yaml
- images/cdi-uploadproxy/werf.inc.yaml
- images/cdi-uploadserver/werf.inc.yaml
- images/dvcr-artifact/werf.inc.yaml
- images/libguestfs/werf.inc.yaml
- images/virt-exportserver/werf.inc.yaml
- images/virt-handler/werf.inc.yaml
- images/virt-launcher/werf.inc.yaml
Versions may change in unstable Sisyphus branch and stable p11 branch now contains all required versions.
> refactor(ci): replace Sisyphus with p11 branch

- images/virtualization-artifact/cmd/virtualization-controller/main.go
- images/virtualization-artifact/pkg/controller/cvi/cvi_controller.go
- images/virtualization-artifact/pkg/controller/service/stat_service.go
- images/virtualization-artifact/pkg/controller/vd/internal/attachee.go
- images/virtualization-artifact/pkg/controller/vd/internal/life_cycle.go
- images/virtualization-artifact/pkg/controller/vd/internal/resizing.go
- images/virtualization-artifact/pkg/controller/vd/internal/resizing_test.go
- images/virtualization-artifact/pkg/controller/vd/vd_controller.go
- images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go
- images/virtualization-artifact/pkg/controller/vd/vd_webhook.go
- images/virtualization-artifact/pkg/controller/vi/vi_controller.go
- images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go
- images/virtualization-artifact/pkg/controller/vmclass/vmclass_reconciler.go
- images/virtualization-artifact/pkg/logger/attrs.go
- images/virtualization-artifact/pkg/logger/constructor.go
- images/virtualization-artifact/pkg/logger/ctx.go
- images/virtualization-artifact/pkg/logger/logger.go
- openapi/config-values.yaml
- openapi/doc-ru-config-values.yaml
- templates/virtualization-controller/_helpers.tpl
Refactored vd controller to common logger interface (slog)
> feat(vd): set common logger slog for controller

- api/core/v1alpha2/vmcondition/condition.go
- images/virtualization-artifact/pkg/controller/vm/internal/class.go
rename class condition to VirtualMachineClass
> refactor(vm): rename class condition to VirtualMachineClass

- images/virtualization-artifact/pkg/monitoring/metrics/metrics.go
- templates/virtualization-controller/scrape-config.yaml
- Add `d8_virtualization_` natively
- Fix lost `namespace` label
> chore(module): add d8_* prefix and fix lost namespce label

- hooks/Taskfile.yaml
- hooks/copy_custom_certificate.py
- hooks/discovery_clusterip_service_for_dvcr.py
- hooks/generate_secret_for_dvcr.py
- hooks/lib/hooks/common.py
- hooks/lib/hooks/copy_custom_certificate.py
- hooks/lib/hooks/hook.py
- hooks/lib/hooks/internal_tls.py
- hooks/lib/hooks/manage_tenant_secrets.py
- hooks/lib/module/module.py
- hooks/manage_tenant_secrets_for_cdi.py
Hardcoded module name
We don't need to use this environment variable anymore (use thouse variable can affected module like tis [PR 9051](https://github.com/deckhouse/deckhouse/pull/9051)
> chore(core): hardcoded module name

- docs/ADMIN_GUIDE.ru.md
Corrected examples in the vmclass administrator's guide
> doc(module): fix admin guide vmclass

- api/core/v1alpha2/virtual_machine_class.go
- crds/virtualmachineclasses.yaml
Add missing labels to crd virtualmachineclasses
> chore(core): add labels to crd virtualmachineclasses

- images/virtualization-artifact/cmd/virtualization-controller/main.go
- images/virtualization-artifact/go.mod
- images/virtualization-artifact/go.sum
- images/virtualization-artifact/pkg/common/common.go
- images/virtualization-artifact/pkg/config/load_gc_settings.go
- images/virtualization-artifact/pkg/controller/gc/cron_source.go
- images/virtualization-artifact/pkg/controller/gc/gc_controller.go
- images/virtualization-artifact/pkg/controller/gc/gc_reconciler.go
- images/virtualization-artifact/pkg/controller/vm/gc.go
- images/virtualization-artifact/pkg/controller/vm/vm_controller.go
- images/virtualization-artifact/pkg/controller/vmop/gc.go
- images/virtualization-artifact/pkg/controller/vmop/vmop_controller.go
- templates/virtualization-controller/_helpers.tpl
- templates/virtualization-controller/rbac-for-us.yaml
- implementation base gc-controller
- add gc for vmop
- add gc for vmimigration
we need to remove old resources
> feat(controllelr): add gc for resources

- templates/virtualization-controller/_helpers.tpl
> fix(templates): add missed symbol

- images/virtualization-artifact/Taskfile.dist.yaml
- images/virtualization-artifact/hack/dlv-controller.Dockerfile
- images/virtualization-artifact/hack/dlv.sh
> feat(controller): add tasks with dlv

- .github/scripts/fetch_prs.mjs
Fix workflow PRs summary
Not all open PRs make it into the summary
> chore(ci): fix workflow PRs summary

- .github/scripts/fetch_prs.mjs
Add PR number to message with posted to loop
> chore(ci): add pr number to message for loop

- tests/e2e/tests_suite_test.go
- tests/e2e/virtualization_resources_test.go
> test(api): add vmbda phase checks

- .github/scripts/fetch_prs.mjs
Corrected display of PRs of required review
> chore(ci): fix required review prs

- images/virtualization-artifact/pkg/controller/vd/internal/validators/iso_source_validator.go
- images/virtualization-artifact/pkg/controller/vd/internal/validators/pvc_size_validator.go
1. VirtualDisk webhooks no longer return an error if an insufficient pvc size is specified or if the vd is created from an ISO image. Instead, a warning will be thrown.
2. Creating a disk from an HTTP source with an ISO suffix is allowed, but after uploading to the dvcr, we will identify that image format is iso and mark the disk as Failed.
> fix(vd): set validator warnings instead of errors

- images/virt-artifact/patches/015-rename-core-resources.patch
- templates/_helpers.tpl
- templates/cdi/cdi-operator/deployment.yaml
- templates/cdi/cdi.yaml
- templates/dvcr/deployment.yaml
- templates/kubevirt/kubevirt.yaml
- templates/kubevirt/priorityclass.yaml
- templates/kubevirt/virt-operator/deployment.yaml
- templates/kubevirt/vm-route-forge/daemonset.yaml
- templates/virtualization-api/deployment.yaml
- templates/virtualization-controller/deployment.yaml
- Set priority class `system-cluster-critical`
- Delete priority class `kubevirt-internal-virtualization-cluster-critical`
> chore(api): set priority class for pods

- monitoring/prometheus-rules/dvcr.yaml
- monitoring/prometheus-rules/internal-virtualization-cdi-apiservier.yaml
- monitoring/prometheus-rules/internal-virtualization-cdi-deployment.yaml
- monitoring/prometheus-rules/internal-virtualization-cdi-operator.yaml
- monitoring/prometheus-rules/internal-virtualization-virt-api.yaml
- monitoring/prometheus-rules/internal-virtualization-virt-controller.yaml
- monitoring/prometheus-rules/internal-virtualization-virt-hander.yaml
- monitoring/prometheus-rules/internal-virtualization-virt-operator.yaml
- monitoring/prometheus-rules/virtualization-api.yaml
- monitoring/prometheus-rules/virtualization-controller.yaml
- monitoring/prometheus-rules/vm-route-forge.yaml
- templates/kubevirt/service-monitor.yaml
- templates/monitoring.yaml
- templates/virtualization-controller/scrape-config.yaml
- werf.yaml
add base control-plane alerts
We need to know when something is wrong with the control plane controllers
> feat(module): add base control-plane alerts

- images/virtualization-artifact/pkg/controller/vd/internal/validators/pvc_size_validator.go
> fix(vd): fix panic if pvc not found

- .github/scripts/fetch_prs.mjs
- .gitignore
Improve PR notificator bot:
- Add Loop-style names for reviewers.
- Exclude PRs by labels, e.g. PRs from release-please.
> chore(ci): Loop mentions for reviewers, exclude autorelease PRs 

- images/virtualization-artifact/pkg/controller/vd/vd_controller.go
- images/virtualization-artifact/pkg/controller/vmbda/vmbda_controller.go
- images/virtualization-artifact/pkg/monitoring/metrics/vd/collector.go
- images/virtualization-artifact/pkg/monitoring/metrics/vd/data_metric.go
- images/virtualization-artifact/pkg/monitoring/metrics/vd/metrics.go
- images/virtualization-artifact/pkg/monitoring/metrics/vd/scraper.go
- images/virtualization-artifact/pkg/monitoring/metrics/vd/unsafe.go
- images/virtualization-artifact/pkg/monitoring/metrics/vmbda/collector.go
- images/virtualization-artifact/pkg/monitoring/metrics/vmbda/data_metric.go
- images/virtualization-artifact/pkg/monitoring/metrics/vmbda/metrics.go
- images/virtualization-artifact/pkg/monitoring/metrics/vmbda/scraper.go
- images/virtualization-artifact/pkg/monitoring/metrics/vmbda/unsafe.go
> refactor(vd, vmbda): apply new collector design

- images/virtualization-artifact/pkg/controller/service/stat_service.go
Fix target for upload data source
> fix(api): set target for upload data source

- images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go
- templates/virtualization-controller/rbac-for-us.yaml
1. Add patch rule for ingress
2. Fix vd reconciliation
> fix(api): add rbac patch for ingress and fix vd reconciliation

- images/virtualization-artifact/pkg/controller/vd/internal/resizing.go
- images/virtualization-artifact/pkg/controller/vd/internal/validators/pvc_size_validator.go
resizing `VirtualDisk` in  filesystem mode.
> feat(vd): resizing vd in  filesystem mode

- api/core/v1alpha2/virtual_machine_class.go
- crds/virtualmachineclasses.yaml
add label backup.deckhouse.io/cluster-config: ""
> chore(vmclass): add backup label

- crds/clustervirtualimages.yaml
> chore(module) add backup label for cvi

- api/core/v1alpha2/vmcondition/condition.go
- images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go
- images/virtualization-artifact/pkg/controller/vm/internal/util.go
add failure message to condition if migration is failed
> feat(vm): add failure message to condition if migration is failed

- templates/kubevirt/service-monitor.yaml
Rename and relabel VM metrics
The names of the metrics should be intuitive to the user
> chore(module): rename and relabel VM metrics

- templates/user-authz-cluster-roles.yaml
Add RBAC for vm and disk snapshots and vm restore
> fix(module) add RBAC for vm and disk snapshots and vm restore

- docs/ADMIN_GUIDE.md
- docs/ADMIN_GUIDE_RU.md
- docs/USER_GUIDE.md
- docs/USER_GUIDE_RU.md
Fix upload for in cluster urls
> docs(module): fix upload urls

- images/virt-artifact/werf.inc.yaml
Fix CVEs:
- CVE-2024-45310
- CVE-2024-9341
Vulnerability remediation
> refactor(ci): fix cve

- tests/performance/Taskfile.yaml
- tests/performance/templates/cloud-init-secret.yaml
- tests/performance/values.yaml
Modified the image for vm to alpine, corrected the type of cloud-init secret.
Added task for install necessary software.
Keep perf test config updated.
> chore(test): performance test updates

- templates/_kube_api_rewriter.tpl
- templates/cdi/cdi-apiserver/vpa.yaml
- templates/cdi/cdi-deployment/vpa.yaml
- templates/cdi/cdi-operator/deployment.yaml
- templates/dvcr/deployment.yaml
- templates/kubevirt/virt-api/vpa.yaml
- templates/kubevirt/virt-controller/vpa.yaml
- templates/kubevirt/virt-handler/vpa.yaml
- templates/kubevirt/virt-operator/deployment.yaml
- templates/virtualization-api/deployment.yaml
- templates/virtualization-controller/deployment.yaml
Add VPA setting for kube-api-rewriter proxy
Fix misconfigurations in `virtualizrion-controller`, `virtualization-api`, `dvcr`
> fix(kube-api-rewriter): add VPA settings

- werf.yaml
Get version directly from environment variable
- Reduce binary dependencies
> chore(module): remove obsolete release.yaml

- images/dvcr/werf.inc.yaml
Fixing vulnerabilities and preparing for builds in different environments
Vulnerability mitigation:
CVE-2023-45288
CVE-2024-34156
CVE-2023-39326
CVE-2023-45284
CVE-2023-45289
CVE-2023-45290
CVE-2024-24783
CVE-2024-24784
CVE-2024-24785
CVE-2024-24789
CVE-2024-24791
CVE-2024-34155
CVE-2024-34158
Works as before
> chore(ci): build from source registry2

- api/core/v1alpha2/virtual_machine_class.go
- api/core/v1alpha2/zz_generated.deepcopy.go
- api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go
- crds/doc-ru-virtualmachineclasses.yaml
- crds/virtualmachineclasses.yaml
- images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go
- images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_utils.go
- images/virtualization-artifact/pkg/controller/vmclass/internal/discovery.go
- images/virtualization-artifact/pkg/controller/vmclass/internal/lifecycle.go
- images/virtualization-artifact/pkg/controller/vmclass/internal/util.go
> feat(vmclass): add tolerations

- images/virtualization-artifact/pkg/controller/vmclass/internal/discovery.go
- images/virtualization-artifact/pkg/controller/vmclass/internal/state/state.go
status.availableNodes with nodeSelector
> feat(vmclass): /vmclass/nodselector

- api/core/v1alpha2/virtual_machine_class.go
- crds/virtualmachineclasses.yaml
Make `.spec.cpu` field immutable.
> feat(vmclass): immutable .spec.cpu

- images/virt-artifact/werf.inc.yaml
Fix git stageDependencies to install in image virt-artifact.
Patches should be applied when adding, deleting, or modifying on right stage.
When patches adding, deleting, or modifying the image must be rebuild.
> chore(ci): fix git stageDependencies to install in virt-artifact

- api/core/v1alpha2/virtual_machine_ip_address_lease.go
- api/core/v1alpha2/virtual_machine_operation.go
- images/virtualization-artifact/pkg/controller/service/resource.go
- images/virtualization-artifact/pkg/controller/vd/internal/datasource_ready.go
- images/virtualization-artifact/pkg/controller/vd/internal/datasource_ready_test.go
- images/virtualization-artifact/pkg/controller/vd/internal/resizing.go
- images/virtualization-artifact/pkg/controller/vd/internal/snapshotting.go
- images/virtualization-artifact/pkg/controller/vdsnapshot/internal/life_cycle.go
- images/virtualization-artifact/pkg/controller/vdsnapshot/internal/virtual_disk_ready.go
- tests/performance/shatal/internal/shatal/modifier.go
rewrite conditions with empty reasons
> fix(api): rewrite conditions with empty reasons

- .github/workflows/nightly_e2e_tests_main.yaml
- tests/e2e/complex_test.go
- tests/e2e/d8/d8.go
- tests/e2e/executor/executor.go
- tests/e2e/kubectl/kubectl.go
- tests/e2e/sizing_policy_test.go
- tests/e2e/tests_suite_test.go
- tests/e2e/util_test.go
- tests/e2e/vm_configuration_test.go
- tests/e2e/vm_connectivity_test.go
- tests/e2e/vm_disk_attachment_test.go
- tests/e2e/vm_disk_resizing_test.go
- tests/e2e/vm_migration_test.go
- add diff between timeouts of exec and kubectl commands;
- decrease default ssh command timeout;
- refactor workflow with kubernetes resource labels;
- refactor WaitPhase func: add async await for list of resources;
- refactor workflow with Eventually func;
- fix ginkgo installation in ci.
It fixes problem with missing logs and some problems in workflow of E2E tests.
> test(api): improve e2e tests logging and fix ci workflow

- .github/workflows/nightly_e2e_tests_main.yaml
It fixes ginkgo installation problem in E2E tests.
E2E tests running will be correct in CI workflow.
> test(ci): fix ginkgo version template in e2e tests

- images/virtualization-artifact/cmd/virtualization-controller/main.go
- templates/virtualization-controller/_helpers.tpl
add configuration metrics bind address
> feat(controller): add configuration metrics bind address

- templates/cdi/cdi-operator/deployment.yaml
Add kube-rbac-proxy to cdi-operator.
> fix(core): add kube-rbac-proxy to cdi-operator

- images/virtualization-artifact/pkg/controller/vm/internal/statistic.go
- images/virtualization-artifact/pkg/controller/vm/internal/statistic_test.go
fix generating wrong statistic
> fix(vm): fix generating wrong statistic

- images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle.go
> fix(vmop): set uid vm label

- .github/workflows/dev_module_build-on-self-hosted-runner.yml
- .github/workflows/dev_module_build.yml
Fix PR #542, build must run on main/pre-alfa branches
> chore(ci): fix run on main

- Taskfile.yaml
- images/virt-handler/debug/dlv.Dockerfile
add dlv debuger for virt-handler
> refactor(dev): add dlv debuger for virt-handler

- api/core/v1alpha2/virtual_image.go
- api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go
- crds/virtualimages.yaml
Reverts deckhouse/virtualization#549
> Revert "fix(vi): update CEL"

- images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go
- images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_test.go
proper affinity and tolerations merging
> fix(vmclass, vm): proper affinity and tolerations merging

- templates/cdi/service-monitor.yaml
change scheme to https for prometheus to correctly collect metrics
> fix(core): fix scheme for cdi servicemonitor

- images/virt-artifact/patches/026-add-healthz-to-virt-operator.patch
- templates/kubevirt/virt-operator/deployment.yaml
> feat(core): add separate healthz endpoint to virt-operator

- .github/workflows/release_module_build-and-registration.yml
- .github/workflows/release_module_release-channels.yml
Add SEPlus edition
We are developing the number of editions and adding one more - SEPlus
> chore(ci): add se-plus edition

- .github/workflows/release_module_release-channels.yml
> chore(ci): fix workflow Deploy Prod

- images/cdi-artifact/werf.inc.yaml
Changed order of applying patches
Fix PR #582, cdi must be patched differently
> chore(ci): fix build cdi-artifact

- .github/workflows/release_module_build-and-registration.yml
- .github/workflows/release_module_release-channels.yml
Update build and deploy prod for login to prod and dev
For use secondary repo as cache we need to login into to prod and dev registry
> chore(ci): update build and deploy prod for login to prod and dev repos

- .prettierignore
- api/Taskfile.dist.yaml
> chore: fix prettier yaml

- tests/e2e/Taskfile.yaml
Change branch env from `GITHUB_REF` to `GITHUB_REF_NAME` so that the summary of run would look more coherent.
Fix #593
> chore(ci): fix branch env in task for e2e CI

- templates/admission-policy.yaml
- tools/kubeconform/fixtures/module-values.yaml
- tools/kubeconform/kubeconform.sh
> feat(templates): add restricted access policy

- images/virtualization-artifact/pkg/controller/vd/internal/source/http.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go
- images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go
- images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go
- images/virtualization-artifact/pkg/controller/vi/internal/source/registry.go
- images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go
> fix(vi): nil recorder

- images/virt-artifact/patches/023-replace-expressions-for-validating-admission-policy.patch
manage labels or annotations with virtualization.deckhouse.io
> fix(core, kubevirt): manage labels or annotations with virtualization.deckhouse.io

- api/core/v1alpha2/virtual_machine_operation.go
- crds/virtualmachineoperations.yaml
- images/virtualization-artifact/pkg/controller/vmop/vmop_webhook.go
- templates/virtualization-controller/validation-webhook.yaml
add CREATE operation to webhook configuration
remove Update operation from webhook configuration. Move immutable logic to CEL
> fix(vmop): improve webhook configuration

- tests/e2e/Taskfile.yaml
While affinity problem is not solved.
It's known problem and it should be excluded from E2E workflow temporary.
> test(api): disable e2e affinity test

- crds/virtualmachines.yaml
> fix(vm): show real resources in brief

- images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go
> fix(vm): fix toleration dupe

- .github/workflows/dev_module_build.yml
Change runner to `ubuntu-22.04` for jobs test and lint_go
Fix for tests to work
The tests are running again and working
> chore(ci): change github runner for test job

- CHANGELOG.md
Update changelog for 0.14.1 and 0.15.0 releases
> chore(docs): update changelog for 0.14.1 and 0.15.0 releases

- templates/admission-policy.yaml
fix expressions for restrict admission policy
> fix: fix expressions for restrict admission policy

- images/virtualization-artifact/pkg/controller/vm/internal/sync_metadata.go
Improved synchronization metadata for VirtualMachine child resources.
> fix(vm):  Improved synchronization metadata for VirtualMachine child resources.

- base-images/alt_image_versions.yml
Update base distroless alt image
> chore: update base alt image

- images/cdi-importer/werf.inc.yaml
- images/cdi-uploadserver/werf.inc.yaml
- images/dvcr-artifact/werf.inc.yaml
- images/libguestfs/werf.inc.yaml
- images/virt-handler/werf.inc.yaml
- images/virt-launcher/werf.inc.yaml
Updating package versions:
- sqlite3==3.46.0-alt1
- libnbd==1.19.11-alt1
- nbd-client==3.26.1-alt1
- nbd-server==3.26.1-alt1
- libvirt-daemon-driver-qemu==10.7.0-alt1
- libvirt-client==10.7.0-alt1
- qemu-kvm-core==9.1.2-alt1
- qemu-img==9.1.2-alt1
- edk2-ovmf-20240811-alt2
```changes
section: ci
type: chore
summary: Updating package versions
```
> chore(ci): update package versions

- .github/scripts/fetch_prs.mjs
Remove PRs with `changelog` label from daily PR summary.
Fix #650 
```changes
section: ci
type: chore
summary: remove changelog from PR reports
```
> chore(ci): remove changelog from PR reports

- .github/actions/milestone-changelog/action.yml
Add default impact level for certain sections
Fix #650 
```changes
section: ci
type: chore
summary: add default impact level for certain sections
```
> fix(ci): add default impact level for certain sections

- .github/workflows/dev_test.yaml
Adding kubevirt tests
Changes to the kubevirt controller should be tracked by unit tests
```changes
section: ci
type: chore
summary: add kubevirt unit tests
```
> chore(ci): add kubevirt unit tests

- images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_utils.go
fix generate disk serial
```changes
section: <scope name in kebab-case (See CONTRIBUTING.md#scope)>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
```
> fix(vm): fix generate disk serial

- images/edk2/build.sh
Fix build flags to `OVMF_4M_FLAGS`
Since we are using OVMF 4M all files should be built with parameters `OVMF_4M_FLAGS`
Windows should boot up
```changes
section: <scope name in kebab-case (See CONTRIBUTING.md#scope)>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
```
> chore(core): fix build firmware (edk2)

- .github/PULL_REQUEST_TEMPLATE.md
- Shorten comments for PR sections
- More info for changelog entries section
- There was no direct link to CONTRIBUTING.md
- There was no info about impact and impact_level fields
- Examples should be handy for developers
- Developer should see all options for changelog section when editing PR description.
- Developer should see that CONTRIBUTING.md has more details.
```changes
section: ci
type: chore
summary: More info in the PR template
```
> chore(ci): more info in PULL_REQUEST_TEMPLATE.md

- images/virtualization-artifact/pkg/controller/vd/internal/life_cycle_test.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/mock.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vdsnapshot.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vdsnapshot_test.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/step/create_pvc_step.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/step/ready_step.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/step/runner.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/step/terminating_step.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/step/wait_for_pvc_step.go
Add wffc phase for vd from snapshot
```changes
section: vd
type: fix
summary: add wffc phase for vd from snapshot
```
> fix(vd): add wffc phase for vd from snapshot

- images/virtualization-artifact/pkg/controller/vd/internal/resizing.go
- images/virtualization-artifact/pkg/controller/vd/internal/resizing_test.go
Fixed Condition Formation : The logic for forming the condition has been corrected to avoid mistakenly setting its status to true, specifically in scenarios where resizing is required. 
Handler Refactoring : Significant refactoring has been performed on the handler to improve code readability, maintainability, and performance. The refactor also aims to simplify complex logic, reduce redundancy, and adhere to best coding practices.
Enhanced Test Coverage : The handler's logic has been thoroughly tested, with most logic branches now covered by unit tests. This enhancement ensures robustness, reliability, and prevents future regressions by verifying that all critical paths operate as expected.
```changes
section: vd
type: fix
summary: fix resizing handler and cover it with unit tests
```
> fix(vd): fix resizing handler

- .github/workflows/dev_module_build.yml
- werf_cleanup.yaml
Add dev release build
```changes
section: ci
type: chore
summary: add dev release build
```
> chore(ci): add dev release build

- .prettierignore
Fix failed `Run YAML linter` jobs
```changes
section: ci
type: chore
summary: ignore prettier checks in CHANGELOG
```
> chore(ci): ignore prettier checks in CHANGELOG

- .github/workflows/dev_module_build.yml
Fix regex for release branches
We only need to build release branches (release-0.16, release-0.17, etc.), not all branches that contain a release
```changes
section: ci
type: fix
summary:  fix ci for release branch build
```
> chore(ci): fix release branch build

- images/virtualization-api/werf.inc.yaml
- images/virtualization-controller/werf.inc.yaml
- templates/virtualization-api/deployment.yaml
- templates/virtualization-controller/deployment.yaml
Change images to distroless:
- virtualization-api
- virtualization-controller
We want our images to be distroless-based
```changes
section: core
type: chore
summary: virtualization api,controller to distroless
```
> chore(core): virtualization api, controller to distroless

- images/virt-operator/werf.inc.yaml
- images/virtualization-api/werf.inc.yaml
- images/virtualization-controller/werf.inc.yaml
- templates/kubevirt/virt-operator/deployment.yaml
- templates/virtualization-api/deployment.yaml
- templates/virtualization-controller/deployment.yaml
We need to use default distroless user deckhouse
Fix PRs #744 #745
```changes
section: core
type: chore
summary: change distroless user to deckhouse
```
> chore(core): change context and user for images

- .github/workflows/dev_module_build-and-registration.yml
Add MODULE_EDITION variable
```changes
section: ci
type: chore
summary: add varible MODULE_EDITION to workflow deploy for dev
```
> chore(ci): fix var module_edition for deploy for dev

- .github/workflows/dev_module_build-and-registration.yml
- werf_cleanup.yaml
Create image module tag in dev-registry. Image will have suffix `-dev`. **For example: v0.16.1-dev**
```changes
section: ci
type: chore
summary: create image module tag in dev-registry
```
> chore(ci): create image module tag in dev-registry

- images/distroless/werf.inc.yaml
All files in /bin,sbin,lib,lib64 directories should use symlinks to their respective counterparts in /usr
In modern Linux systems, the contents of /bin, /sbin, etc are often symlinked to their counterparts in /usr. 
This change simplifies system operation and improves maintainability
```changes
section: core
type: fix
summary: directories in root such as bin,sbin,etc linked to their respective counterparts in /usr
```
> fix(core): distroless image fix bin,sbin directories

- .github/workflows/dev_build_precache.yml
- .github/workflows/dev_module_build.yml
The `pre-alpha` branch has been removed from ci
We don't need `pre-alpha` branch anymore
```changes
section: ci
type: refactor
summary: the pre-alpha branch has been removed from ci
```
> refactor(ci): precache build, change runner, delete brunch pre-alpha

- images/vm-route-forge/werf.inc.yaml
Change vm-router-forge image to distroless
We want our images to be distroless-based
```changes
section: core
type: chore
summary: change vm-router-forge image to distroless
```
> chore(core): distroless vm-route-forge

- .github/CODEOWNERS
- tools/validation/copyright.go
Add codeowners
```changes
section: ci
type: chore
summary: add codeowners
```
> chore(ci): add codeowners

- api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go
Fix description in generated code.
```changes
section: vm
type: fix
summary: fix description in generated code
```
> fix(vm): update descriptions for CPU topology schema

- docs/ADMIN_GUIDE.md
- docs/ADMIN_GUIDE_RU.md
Add more cloud images sources
```changes
section: docs
type: chore
summary: add more cloud images sources
```
> docs: add more cloud images sources

- images/cdi-cloner/werf.inc.yaml
- images/cdi-controller/werf.inc.yaml
- images/cdi-importer/werf.inc.yaml
- images/cdi-uploadserver/werf.inc.yaml
- images/dvcr-importer/werf.inc.yaml
- images/dvcr-uploader/werf.inc.yaml
- images/dvcr/werf.inc.yaml
Fix build `cdi` and `dvcr` images. Removed unnecessary binaries. 
During the build process there were some unnecessary binary files in the image, now there will be no more of them
```changes
section: core
type: fix
summary: fix dvcr images imports, cdi components to distroless images
```
> chore(core): fix distroless imports

- .github/scripts/prs_notifier.mjs
The assignee could get into the reviewers list if they left comments on the pull request. 
Fixed this.
```changes
section: ci
type: chore
summary: remove assignee from reviewer list 
```
> chore(ci): fix reviewers list

- tests/e2e/README.md
```changes
section: docs
type: chore
summary: add permissions block to e2e README.md
```
> chore(docs): add permissions block to e2e README.md

- docs/ADMIN_GUIDE.md
- docs/USER_GUIDE.md
- docs/USER_GUIDE_RU.md
Fix links of virtual machine images at user guide.
```changes
section: docs
type: fix
summary: Fix links of virtual machine images at user guide. 
```
> docs: fix links of virtual machine images at user guide

- .github/workflows/check-changelog-entry.yml
Add changelog entry check for automatic verification of changelog section in PR.
To verify changelog entry automatically, to avoid `MALFORMED` sections in changelog.
```changes
section: ci
type: chore
summary: add changelog entry check
```
> chore(ci): add changelog entry check

- templates/cdi/config.yaml
Add to cdi config HonorWaitForFirstConsumer
```yaml
config:
featureGates:
- HonorWaitForFirstConsumer
```
To be fully compatible with any external tools that may already use CDI, this new feature has to be enabled by 
the feature gate: `HonorWaitForFirstConsumer`
```changes
section: core
type: fix
summary: Add to cdi config HonorWaitForFirstConsumer
```
> fix(core): fix dci config template, add feature gate HonorWaitForFirstConsumer

- .github/workflows/dev_module_build-and-registration.yml
- .github/workflows/dev_module_build.yml
Changing the labels of self-hosted runners
```changes
section: ci
type: chore
summary: Changing the labels of self-hosted runners
```
> chore(ci): rename labels for self-hosted runners

- tests/e2e/complex_test.go
e2e tests could fail when testing network connectivity before/after vm migration due to a bug on the network side. To prevent the test from failing, network availability checks were restricted. 
Removed this temporary restriction since the bug is no longer relevant.
```changes
section: test
type: vm
summary: remove temporary connectivity check restriction
```
> test: remove temporary connectivity check restriction

- monitoring/grafana-dashboards/main/virtual-machine.json
- templates/monitoring.yaml
- tools/kubeconform/kubeconform.sh
Add VM grafana dashboard
```changes
type: feature
summary: Add VM grafana dashboard
```
> feat: add VM grafana dashboard

- images/virtualization-artifact/pkg/controller/cvi/cvi_reconciler.go
- images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go
- images/virtualization-artifact/pkg/controller/cvi/internal/source/sources.go
- images/virtualization-artifact/pkg/controller/reconciler/reconciler.go
- images/virtualization-artifact/pkg/controller/reconciler/resource.go
- images/virtualization-artifact/pkg/controller/service/protection_service.go
- images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go
- images/virtualization-artifact/pkg/controller/vdsnapshot/vdsnapshot_reconciler.go
- images/virtualization-artifact/pkg/controller/vi/vi_reconciler.go
- images/virtualization-artifact/pkg/controller/vm/internal/block_devices_test.go
- images/virtualization-artifact/pkg/controller/vm/internal/state/state.go
- images/virtualization-artifact/pkg/controller/vm/internal/statistic_test.go
- images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state_test.go
- images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go
- images/virtualization-artifact/pkg/controller/vmbda/vmbda_reconciler.go
- images/virtualization-artifact/pkg/controller/vmclass/internal/state/state.go
- images/virtualization-artifact/pkg/controller/vmclass/vmclass_reconciler.go
- images/virtualization-artifact/pkg/controller/vmip/vmip_reconciler.go
- images/virtualization-artifact/pkg/controller/vmiplease/vmiplease_reconciler.go
- images/virtualization-artifact/pkg/controller/vmop/internal/state/state.go
- images/virtualization-artifact/pkg/controller/vmop/vmop_reconciler.go
- images/virtualization-artifact/pkg/controller/vmrestore/vmrestore_reconciler.go
- images/virtualization-artifact/pkg/controller/vmsnapshot/vmsnapshot_reconciler.go
Add generic handler reconciler
```changes
section: api
type: chore
summary: add generic handler reconciler
```
> chore(api): add generic handler reconciler

- docs/internal/dvcr_cleaner.md
- docs/internal/dvcr_cleaner_RU.md
https://github.com/distribution/distribution/issues/1803
DVCR should be restarted after cleaning with the `dvcr-cleaner` tool.
```changes
section: docs
type: chore
summary: "Update dvcr-cleaner internal doc."
```
> chore(docs): update dvcr-cleaner internal doc

- tests/e2e/default_config.yaml
Add error messages from virtualization-controller to e2e error exceptions list for further processing.
```changes
section: ci
type: chore
summary: add error messages from virtualization-controller to e2e error exceptions list for further processing.
```
> chore(test): add err to exceptions list

- images/virtualization-artifact/pkg/controller/service/uploader_service.go
Fix the e2e test issue where attempting to unprotect the uploader fails due to a nil pod argument.
```changes
section: images
type: fix
summary: fix unprotect uploader with nil pod arg
```
> fix(images): nil pointer uploader pod

- tests/e2e/default_config.yaml
Filter vmiplease errors
```changes
section: api
type: chore
summary: filter vmiplease errors
```
> test: filter vmiplease errors

- tests/e2e/testdata/affinity-toleration/vm/base/cfg/cloudinit.yaml
- tests/e2e/testdata/complex-test/vm/base/cfg/cloudinit.yaml
- tests/e2e/testdata/disk-resizing/base/cfg/cloudinit.yaml
- tests/e2e/testdata/image-hotplug/base/cfg/cloudinit.yaml
- tests/e2e/testdata/sizing-policy/base/cfg/cloudinit.yaml
- tests/e2e/testdata/vd-snapshots/vm/base/cfg/cloudinit.yaml
- tests/e2e/testdata/vm-configuration/base/cfg/cloudinit.yaml
- tests/e2e/testdata/vm-disk-attachment/base/cfg/cloudinit.yaml
- tests/e2e/testdata/vm-label-annotation/base/cfg/cloudinit.yaml
- tests/e2e/testdata/vm-migration/vm/base/cfg/cloudinit.yaml
Fix cloud init
```changes
section: vm
type: chore
summary: fix cloud init
```
> test(vm): fix cloud init

- .github/workflows/dev_module_build.yml
Fix trivy registry to read only one.
```changes
section: ci
type: chore
summary: fix trivy registry
```
> chore(ci): fix trivy registry

- tests/e2e/tests_suite_test.go
The restart check for the v12n-controllers pod works properly.
Sometimes we see an error when the v12n-controller error logger finishes its work, and we do not see the cause of this error.
```changes
section: api
type: chore
summary: "The restart check for the v12n-controllers pod works properly."
```
> test: refactor v12n-controller errlogger

- tests/e2e/default_config.yaml
Filter vm ip errors
```changes
section: api
type: chore
summary: filter vm ip errors
```
> test: filter vm ip errors

- tests/e2e/affinity_toleration_test.go
Fix migration to the same node
```changes
section: vm
type: chore
summary: fix migration to the same node
```
> test(vm): fix migration to the same node

- tests/e2e/affinity_toleration_test.go
Fix panic
```changes
section: vm
type: chore
summary: fix panic
```
> test(vm): fix panic

- .github/workflows/dev_validation.yaml
Fix PR #940, ubuntu 22 has the same helm version, 3.17.3 as ubuntu 24 
Pin helm version to 3.17.2
```changes
section: ci
type: chore
summary: add step helm setup and pin version to 3.17.2
```
> chore(ci): add step helm setup

- images/virtualization-artifact/pkg/controller/reconciler/resource.go
- tests/e2e/default_config.yaml
Ignore not found error while deleting finalizers.
```changes
section: api
type: fix
summary: ignore not found error while deleting finalizers
```
> fix(api): ignore not found error while deleting finalizers

- images/dvcr-artifact/pkg/monitoring/progress.go
- images/dvcr-artifact/pkg/monitoring/prometheus.go
- images/dvcr-artifact/pkg/retry/backoff.go
Fix importer progress display error.
```changes
section: core
type: fix
summary: fix importer progress display error
impact_level: low 
```
> fix(core): fix importer progress display error

- tests/e2e/vm_migration_cancel_test.go
wait correct abort status when migration canceled
```changes
section: vmop
type: fix
summary: wait correct abort status when migration canceled
```
> tests(vmop): wait correct abort status when migration canceled

- tests/e2e/util_test.go
fix file creation while dump test resources.
```changes
section: ci
type: chore
summary: fix file creation while dump test resources.
```
> chore(ci): fix dump intvirt resources

- tests/e2e/testdata/affinity-toleration/vi/kustomization.yaml
- tests/e2e/testdata/affinity-toleration/vi/vi-ubuntu-http.yaml
- tests/e2e/testdata/affinity-toleration/vm/base/vd-root.yaml
Signed-off-by: Maksim Fedotov <maksim.fedotov@flant.com>
```changes
section: ci
type: chore
summary: change image for affinity tests to ubuntu
```
> chore(test): change image for affinity tests to ubuntu

- werf.yaml
Add missind module.yaml to werf
```changes
type: chore
summary: add module.yaml to werf
```
> chore(module): add module.yaml to werf

- tests/e2e/vm_migration_cancel_test.go
fix migration cancel test 
```changes
section: vmop
type: fix
summary:  fix migration cancel test 
```
> tests: fix migration cancel test 

- .github/workflows/release_module_release-channels.yml
Fix Build Prod workflow env escaping
```changes
section: ci
type: chore
summary: fix Build Prod env escaping
```
> chore(ci): fix Build Prod env escaping

- images/virtualization-artifact/pkg/controller/evacuation/internal/handler/evacuation.go
Handle conflict error in evacuation-controller.
```changes
section: vmop
type: fix
summary:  handle conflict error in evacuation-controller
```
> fix(vmop): handle conflict error in evacuation-controller

- .github/workflows/dev_module_build.yml
Add a comment on e2e tests run status.
To track e2e tests more effectively.
```changes
section: ci
type: chore
summary: add e2e comment
```
> chore(ci): add e2e comment

- tests/e2e/complex_test.go
Fix complex test for VirtualMachine with custom ip address in E2E tests.
```changes
section: ci
type: chore
summary: Fix complex test for VirtualMachine with custom ip address in E2E tests.
```
> chore(test): fix complex test for vm with custom vmip

- component_versions/version_map.yml
- images/packages/binaries/gnutls/werf.inc.yaml
- images/virt-launcher/werf.inc.yaml
Build the gnutls package and replace it in virt-launcher image.
We want more control when building binary files, as well as making images more secure
```changes
section: core
type: chore
summary: self-build gnutls and replace it in virt-launcher image
```
> chore(core): self-build gnutls

- images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vd.go
- images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go
Fix cleanup for CVI and VI when creating from object reference with the type VirtualDisk.
```changes
section: vd 
type: fix
summary: Fix cleanup for CVI and VI when creating from object reference with the type VirtualDisk.
```
> fix(vi,cvi): fix cleanup for CVI and VI when creating from vd

- component_versions/version_map.yml
- images/libvirt/werf.inc.yaml
- images/packages/binaries/dmidecode/werf.inc.yaml
- images/qemu/werf.inc.yaml
- images/virt-launcher/werf.inc.yaml
Build dmidecode
```changes
section: ci
type: chore
summary: build dmidecode
```
> chore(ci): build dmidecode

- images/virtualization-artifact/pkg/controller/vmiplease/internal/lifecycle_handler.go
- images/virtualization-artifact/pkg/controller/vmiplease/internal/protection_handler.go
- images/virtualization-artifact/pkg/controller/vmiplease/internal/retention_handler.go
Fix problem with deleting the finalizer from VirtualMachineIPLease.
```changes
section: vmipl
type: fix
summary: Fix problem with deleting the finalizer from VirtualMachineIPLease.
```
> fix(vmipl): fix problem with deleting the finalizer

- tests/e2e/testdata/complex-test/vm/overlays/with-mounted-cvi/kustomization.yaml
- tests/e2e/testdata/complex-test/vm/overlays/with-mounted-vi/kustomization.yaml
replace mounted cvi, vi
```changes
section: vm 
type: fix
summary: replace mounted cvi, vi
```
> test: replace mounted cvi, vi

- templates/virtualization-audit/audit-service.yaml
- templates/virtualization-audit/cert-secret.yaml
- templates/virtualization-audit/deployment.yaml
- templates/virtualization-audit/log-config.yaml
- templates/virtualization-audit/rbac-for-us.yaml
Fix nil pointer in audit templates.
```changes
section: core
type: chore
summary: Fix nil pointer in audit templates.
```
> chore(core): fix audit template

- monitoring/grafana-dashboards/main/virtual-machine.json
- templates/kubevirt/service-monitor.yaml
add VM live migration stat dashboard
fixed wrong metrics names: `d8_virtualization_virtualmachine_*_seconds_total -> d8_virtualization_virtualmachine_*_milliseconds_total`
Give the user an understanding of why live VM live migration take a long time to complete. 
```changes
type: feature
summary: add VM live migration stat dashboard
```
> feat(module): add vm livemigration stat dashboard

- .github/workflows/dev_module_build.yml
- .github/workflows/release_module_build-and-registration.yml
- .github/workflows/release_module_release-channels.yml
Fix variable module tag for dev_modules_build, release_module_build-and-registration, release_module_release-channels
```changes
section: ci
type: fix
summary: fix variable module tag
```
> fix(ci): fix variable for module tag

- werf.yaml
remove png builder script from module image
```changes
type: chore
summary: remove png builder script from module image
```
> chore(module): remove png builder script from module image

- .github/workflows/dev_module_build.yml
Fail pipeline on discovered CVEs in Trivy.
To make existing Trivy scan job useful for us.
Failed pipelines on CVEs.
```changes
section: ci
type: chore
summary: fail on trivy vulnerabilities
```
> chore(ci): fail on trivy vulnerabilities

- component_versions/version_map.yml
- images/packages/binaries/libblkid/werf.inc.yaml
Build libblkid library.
```changes
section: core
type: chore
summary: build libblkid
```
> chore(ci): build libblkid

- tests/e2e/ipam_test.go
- tests/e2e/util_test.go
Fix the issue with event detection related to lease deletion.
```changes
section: vmip
type: chore
summary: Fix the issue with event detection related to lease deletion.
```
> test(vmip): fix the issue with event detection related to lease deletion

- images/virtualization-artifact/pkg/controller/vdsnapshot/internal/life_cycle.go
- images/virtualization-artifact/pkg/controller/vdsnapshot/internal/life_cycle_test.go
Unfreezes the filesystem of the `VirtualMachine` that is using the `VirtualDisk` from which an attempt to create a snapshot was made, which failed.
```changes
section: vdsnapshot 
type: fix
summary: unfreeze virtual machine filesystem if snapshotting failed
```
> fix(vdsnapshot): unfreeze virtual machine filesystem if snapshotting failed

- images/virtualization-artifact/pkg/controller/vd/internal/inuse.go
Remove the checking of the conditions on the VirtualMachine when it is in the “Pending” phase, while updating the “inUse” condition on the VirtualDisk.
This solves an issue where a VM waiting for a VirtualMachineClass or VirtualMachineIP was not capturing a VirtualDisk (InUse condition = False), and the BlockDevicesReady VM's condition was set to 'not ready for use'
```changes
section: vm
type: fix
summary: fix BlockDevicesReady VM's condition was set to 'not ready for use' when VD ready.
```
> fix(vm): fix BlockDeviceReady condition

- crds/virtualdisks.yaml
Change additionalPrinterColumns: .spec.persistentVolumeClaim.storageClassName -> .status.storageClassName
```changes
section: vd
type: fix
summary: output storageClassName in VirtualDisk's brief from .status 
```
> fix(vd): change brief for vd

- images/dvcr-artifact/werf.inc.yaml
- images/dvcr/werf.inc.yaml
- images/virtualization-artifact/werf.inc.yaml
```changes
section: ci
type: chore
summary:  add audit, dvcr, importer, uploader to svace
```
> chore(ci): add audit, dvcr, importer, uploader to svace

- .github/workflows/dev_build_svace.yml
Add svace build job
To manually build svace on arbitrary branches
```changes
section: ci
type: feature
summary: add svace cronjob
```
> feat(ci): add svace cronjob

- .github/workflows/dev_build_svace.yml
Fix svace cronjob to tag images with `-svace` suffix. 
Also remove unused code with invocation of `inputs`.
Fix #1137 
```changes
section: ci
type: chore
summary: fix svace cronjob
```
> chore(ci): fix svace cronjob

- .github/workflows/dev_build_svace.yml
- images/vm-route-forge/werf.inc.yaml
Add concurrency for workflow svace.
Also build EE image in svace workflow for virtualization-audit static analysis, add svace build for vm-route-forge
```changes
section: ci
type: chore
summary: build EE image in svace workflow for virtualization-audit static analysis, add svace build for vm-route-forge
```
> chore(ci): add concurrency to svace

- .github/scripts/js/ci.js
- .github/workflows/dev_module_build.yml
Remove svace/analyze label at the end of the workflow.
We need this to improve user experience of svace build.
```changes
section: ci
type: chore
summary: remove svace/analyze label after build
```
> chore(ci): remove svace/analyze label after build

- .github/workflows/dev_build_svace.yml
- images/virtualization-artifact/werf.inc.yaml
fix virtualization-audit svace build
Fix #1131 
```changes
section: ci
type: chore
summary: fix virtualization-audit svace build
```
> chore(ci): fix virtualization-audit svace build

- .github/workflows/dev_build_svace.yml
Enable schedule for svace
```changes
section: ci
type: chore
summary: enable schedule for svace
```
> chore(ci): enable schedule for svace

- .github/workflows/dev_build_svace.yml
Add `MODULE_EDITION` to svace workflow
```changes
section: ci
type: chore
summary:  add `MODULE_EDITION` to svace workflow
```
> chore(ci): add `MODULE_EDITION` to svace workflow

- images/virtualization-api/werf.inc.yaml
- images/virtualization-artifact/cmd/virtualization-controller/main.go
- images/virtualization-artifact/pkg/controller/vd/internal/life_cycle.go
- images/virtualization-artifact/pkg/controller/vd/internal/source/sources.go
- images/virtualization-artifact/werf.inc.yaml
- images/virtualization-audit/werf.inc.yaml
- images/virtualization-controller/werf.inc.yaml
- Fix probable Lost phase blinking on vd deletion.
- Cleanups in build script.
- Stop using prepopulated directories /usr/local/go/api and /usr/local/go/src as a build dirirectories for virtualization binaries.
- Keep -a flag for first binary only.
1. We need to fix regression: Disk deletion is stuck in "invalid phase Lost" after merging #859.
2. Also, VD phase stays "Ready" for disk in a deletion state - also fixed.
Disk deletion works as expected.
Terminating phase set as expected.
```changes
section: vd
type: chore
summary: Fix disk deletion error "invalid phase Lost"
```
> chore(vd): fix disk deletion error

- .werf/packages.yaml
- images/cdi-artifact/werf.inc.yaml
- images/kube-api-rewriter/werf.inc.yaml
- images/packages/binaries/swtpm/werf.inc.yaml
Add cdi, swtpm, kube-api-rewriter to svace
```changes
section: ci
type: chore
summary: add cdi, swtpm, kube-api-rewriter to svace
```
> chore(ci): add cdi, swtpm, kube-api-rewriter to svace

- component_versions/version_map.yml
- images/packages/binaries/libhogweed/werf.inc.yaml
Build libhogweed library.
```changes
section: core
type: chore
summary: build libhogweed
```
> chore(ci): build libhogweed

- component_versions/version_map.yml
- images/packages/binaries/libisoburn/werf.inc.yaml
Build libisoburn library.
```changes
section: core
type: chore
summary: build libisoburn
```
> chore(ci): build libisoburn

- .github/workflows/check-changelog-entry.yml
Add type `docs` to changelog.
To stop docs from appearing in changelog.
1. Type `docs` can be used in changelog entry field.
2. PRs with aforementioned type will not appear in changelog for milestone.
```changes
section: ci
type: docs
summary: add docs docs docs
```
> chore(ci): add type docs

- component_versions/version_map.yml
- images/packages/binaries/libidn2/werf.inc.yaml
Build libidn2 library.
```changes
section: core
type: chore
summary: build libidn2
```
> chore(ci): build libidn2

- .github/workflows/dev_module_build.yml
Update cve_scan version to v3
```changes
section: ci
type: chore
summary: update cve_scan version to v3
```
> chore(ci): update `cve_scan` version to v3

- images/hooks/werf.inc.yaml
- images/pre-delete-hook/werf.inc.yaml
Add pre-delete-hook and module hooks to svace build.
```changes
section: ci
type: chore 
summary: add hooks to svace
```
> chore(ci): add hooks to svace

- templates/nodegroupconfiguration-aio-max-nr.yaml
- templates/nodegroupconfiguration-detect-kvm.yaml
- templates/nodegroupconfiguration-selinux.yaml
Fix ngc for centos derivatives and change their name from virt- prefix to virtualization-
```changes
section: core
type: fix
summary: fix integration with SELinux for CentOS and its derivatives
```
> fix(core): fix ngc for centos derivatives

- images/virtualization-artifact/cmd/virtualization-audit/app/app.go
- templates/virtualization-audit/log-config.yaml
Fix typo in template for fixing TLS in audit controller. Also enable tls in code and delete comment with variant without TLS.
```changes
section: core
type: chore
summary: fix typo in template for fixing TLS in audit controller.
```
> chore(core): fix TLS in audit controller

- images/virtualization-artifact/pkg/controller/workload-updater/internal/watcher/vm.go
Add react on create virtual machine event for WorkloadUpdater controller
```changes
section: vm
type: fix
summary: Add react on create virtual machine event for WorkloadUpdater controller
```
> fix(vm): Add react on create virtual machine event for WorkloadUpdater controller

- CHANGELOG/CHANGELOG-v0.24.md
fix MALFORMED in changelog for 0.24.0 version
> chore(ci): fix changelog for v0.24.0

- build/components/versions.yml
- images/packages/libgsasl/werf.inc.yaml
- images/packages/libidn/README.md
- images/packages/libidn/werf.inc.yaml
- images/packages/libidn2/werf.inc.yaml
Refactor build libidn and libidn2
```changes
section: core
type: fix
summary: Refactor build libidn and libidn2
```
> chore(core): refactor build libidn libidn2

- tests/e2e/vm_disk_attachment_test.go
fix typo in VirtualDiskAttachment
> chore(tests): fix typo in VirtualDiskAttachment

- .github/workflows/dev_build_svace.yml
1. Fix Svace alert not sending
2. Move alert to separate job to send even if the build has failed
Fix #1388
> chore(ci): fix svace alert

- .github/workflows/dev_module_build-and-registration.yml
Add build for tag like major.minor.patch-rc.num
```changes
section: ci
type: chore
summary: add build for tag like major.minor.patch-rc.num
```
> chore(ci): add build for tag like major.minor.patch-rc.num

- images/virtualization-artifact/pkg/controller/service/restorer/restorer.go
This PR fixes incorrect data encoding during snapshot creation and restoration by removing redundant base64 encoding when storing JSON in Kubernetes Secrets.
```changes
section: vm
type: fix 
summary: fix incorrect data encoding during snapshot creation and restoration by removing redundant base64 encoding when storing JSON in Kubernetes Secrets.
```
> fix(vm):  fix incorrect data encoding during snapshot creation and restoration by removing redundant base64 encoding 

- build/components/versions.yml
- images/packages/dtc/werf.inc.yaml
- images/packages/file/werf.inc.yaml
- images/packages/gcc/werf.inc.yaml
- images/packages/glib2/werf.inc.yaml
- images/packages/gnutls/werf.inc.yaml
- images/packages/libcurl/werf.inc.yaml
- images/packages/libgsasl/werf.inc.yaml
- images/packages/libnbd/werf.inc.yaml
- images/packages/libnl3/README.md
- images/packages/libnl3/werf.inc.yaml
- images/packages/libntlm/README.md
- images/packages/libntlm/werf.inc.yaml
- images/packages/libssh/werf.inc.yaml
- images/packages/libssh2/werf.inc.yaml
- images/packages/nbdkit/werf.inc.yaml
- images/packages/pcre2/README.md
- images/packages/pcre2/werf.inc.yaml
- images/packages/rdma-core/werf.inc.yaml
- images/packages/ubdsrv/README.md
- images/packages/ubdsrv/werf.inc.yaml
- images/packages/zstd/README.md
- images/packages/zstd/werf.inc.yaml
- images/qemu/werf.inc.yaml
- images/virt-launcher/werf.inc.yaml
build libs:
- libnl3: libnl3_11_0
- libntlm: v1.8
- pcre2: pcre2-10.46
- zstd: v1.5.7
- ubdsrv: v1.6
refactor build:
- gcc
```changes
section: core
type: chore
summary: build libs libnl3 libntlm pcre2 zstd ubdsrv
```
> chore(core): build libs libnl3 libntlm pcre2 zstd ubdsrv

- images/virtualization-artifact/pkg/builder/cvi/cvi.go
- images/virtualization-artifact/pkg/builder/cvi/option.go
- images/virtualization-artifact/pkg/builder/vd/option.go
- images/virtualization-artifact/pkg/builder/vd/vd.go
- images/virtualization-artifact/pkg/builder/vm/option.go
- tests/e2e/config/config.go
- tests/e2e/framework/client.go
- tests/e2e/framework/framework.go
- tests/e2e/object/const.go
- tests/e2e/object/cvi.go
- tests/e2e/object/vd.go
- tests/e2e/object/vm.go
- tests/e2e/tests_suite_test.go
add e2e framework
```changes
section: core
type: feature
summary: add e2e framework
```
> feat: add e2e framework

- build/components/versions.yml
- images/packages/libaio/README.md
- images/packages/libaio/werf.inc.yaml
- images/packages/lvm2/werf.inc.yaml
- images/qemu/werf.inc.yaml
- images/virt-launcher/werf.inc.yaml
build libs:
- libaio: libaio-0.3.113
```changes
section: core
type: chore
summary: build libaio
```
> chore(core): build libaio

- tests/e2e/framework/client.go
> tests: support auth plugins

- tests/e2e/vm_disk_resizing_test.go
> chore: skip disk resizing test
