deckhouse/virtualization

images/virtualization-controller/Taskfile.dist.yaml, images/virtualization-controller/hack/mirrord-config.json, images/virtualization-controller/hack/mirrord.sh
Add two task for local development. 
1. mirrord:run 
2. mirrord:wipe
Run your local code in the real-time context of your kubernetes cluster.
Testing controllers and webhooks.
=> feat: add mirrord tasks

images/virtualization-controller/pkg/sdk/framework/helper/resource.go, images/virtualization-controller/pkg/sdk/framework/two_phase_reconciler/reconciler_core.go
- Use level 4 for trace messages like UpdateMetadata and UpdateStatus.
- Add messages to distinguish reconcile steps.
- Add message with reconcile result to see if requeue was requested.
UpdateMetadata and UpdateStatus are too noisy for default debug log level.
Developer should change VERBOSITY to 4 to see more detailed huge logs.
=> fix: mute noisy log messages by default

docs/internal/vm_power_state.md, images/virt-launcher/scripts/domain-monitor.sh, images/virt-launcher/scripts/virt-launcher-monitor-wrapper.sh, images/virt-launcher/werf.inc.yaml, images/virtualization-controller/pkg/common/kvvm/util.go, images/virtualization-controller/pkg/controller/powerstate/kvvm_request.go, images/virtualization-controller/pkg/controller/powerstate/operations.go, images/virtualization-controller/pkg/controller/powerstate/shutdown_reason.go, images/virtualization-controller/pkg/controller/vm_reconciler.go, images/virtualization-controller/pkg/controller/vmop/vmop_reconciler.go, werf.yaml
Make VM's Pod a one-shot Pod. Use runPolicy Manual and restart Pod via KVVMI deletion.
Executing `sudo reboot` inside the VM should be equal to executing virtctl restart/deleting KVVMI in controller.
VM after `sudo restart` should be created with new settings.
1. Use disruption mode Manual
2. patch VM
3. enter VM console, run reboot
4. check that rebootId is absent, and the recreated VM has new settings.
=> feat(vm): always replace Pod on VM restart

images/virtualization-controller/pkg/controller/vm_reconciler.go, images/virtualization-controller/pkg/controller/vm_reconciler_state.go
Fixed bug with deleting labels and annotations
When deleting labels and annotations from virtual machine, they are not deleted from Pod
=> fix(vm): fixed annotations and labels propagation

api/core/v1alpha2/virtual_machine.go, api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go, images/virtualization-artifact/pkg/controller/cpu/cpu_reconciler.go, images/virtualization-artifact/pkg/controller/cpu/cpu_reconciler_state.go, images/virtualization-artifact/pkg/controller/vm_reconciler_state.go, images/virtualization-artifact/pkg/controller/vm_reconciler_test.go, images/virtualization-artifact/pkg/controller/vmchange/comparators.go, templates/virtualization-controller/rbac-for-us.yaml
Fixed bugs
- Fix non-compliance with the specification and the go-structure for VMCPU
- Fixed vmcpu reconciliation (ShouldReconcile method)
- Added Node resource to rbac
- Fixed vmcpu phase update for type: model 
Bugs are fixed
=> fix(vmcpur): fixed reconciliation bugs and rbac

api/client/kubeclient/async.go, api/client/kubeclient/client.go, api/client/kubeclient/config.go, api/client/kubeclient/request.go, api/client/kubeclient/streamer.go, api/client/kubeclient/vm.go, api/client/kubeclient/websocket.go
rename pkg kubecli to kubeclient
=> fix(client): rename pkg kubecli to kubeclient

images/virtualization-artifact/pkg/controller/vmchange/comparators.go
Set proper default for modelName comparator.
Wrong default (empty string) leads to excess change in restartAwaitingChanges.
=>  fix(vm): set default for modelName in comparators

crds/virtualmachine.yaml, tests/e2e/Taskfile.yaml
This reverts commit ba34ffd05ed19f7e62966138d3bb6636718cf4b6.
Restore the original value of the terminationGracePeriodSeconds parameter
The problematic requires a different approach to solving restart problems
=> fix(crd): restore the original value of the terminationGracePeriodSeconds parameter

images/virtualization-artifact/pkg/controller/monitoring/final_report.go, images/virtualization-artifact/pkg/controller/monitoring/progress.go, images/virtualization-artifact/pkg/controller/monitoring/progress_test.go, images/virtualization-artifact/pkg/util/util.go
The size format in our status does not correspond to the standard one in Kubernetes
```
status:
downloadSpeed:
avg: 38 MB/s
size:
stored: 406 MB
unpacked: 2.4 GB
```
It must be like this
```
status:
downloadSpeed:
avg: 38Mi/s
size:
stored: 406Mi
unpacked: 2.4Gi
```
=> fix(vmi,cvmi): normalize size format

.github/actions/remove-unwanted-software/action.yml, .github/workflows/build_dev.yml, .github/workflows/build_prod.yml
- Initial 20Gb of free space is not enough for building kubevirt and cdi.
- Remove preinstalled Docker images and some huge packages: android, codeql, swift, etc. to get extra ~20Gb of free space.
- Update arduino/setup-task to v2 to use Node 20.
Initial 20Gb of free space is not enough for building kubevirt and cdi.
Kubevirt and CDI components are successfully built after changing patches.
=> fix: free some space on Github-hosted runners

images/virtualization-artifact/pkg/apiserver/api/install.go, images/virtualization-artifact/pkg/apiserver/registry/vm/storage/storage.go, images/virtualization-artifact/pkg/apiserver/server/config.go
adding the same table-converter as "virtualmachines.virtualization.deckhouse.io" to "virtualmachines.subresources.virtualization.deck house.io".
```bash                                                                                                                                                                                                                                
❯ kubectl get virtualmachines.virtualization.deckhouse.io 
NAME   PHASE     NODENAME   IPADDRESS    AGE
test   Pending              10.66.10.1   6s
❯ kubectl get virtualmachines.subresources.virtualization.deckhouse.io 
NAME   PHASE     NODENAME   IPADDRESS    AGE
test   Pending              10.66.10.1   10s
```
The resource "virtualmachines.subresources.virtualization.deckhouse.io" has a higher priority than …
=> feat(apiserver): implement table-converter

.github/workflows/validation.yaml
Added condition for skip job doc_changes and no_cyrillic validations.
Added labels:
validation/skip/no_cyrillic
validation/skip/doc_changes
In some cases, we need to skip checking the Cyrillic alphabet or document changes.
=> ci: add skip labels for doc_changes and no_cyrillic validations

templates/pre-delete-hook/job.yaml
fix wrong templates
```
❯ helm uninstall virtualization 
Error: unable to build kubernetes object for pre-delete hook virtualization/templates/pre-delete-hook/job.yaml: error validating "": error validating data: ValidationError(Job.spec.template.spec.tolerations[8]): unknown field "resources" in io.k8s.api.core.v1.Toleration
```
manifest:
```
❯ helm get hooks virtualization | yq '.spec.template.spec'
restartPolicy: Never
serviceAccountName: virtualization-pre-delete-hook
containers:
- name: virtualization-pre-delete-hook
image: ...
tolerations:
- key: node-role.kubernetes.io/master
...
- key: drbd.linbit.com/ignore-fail-over
resources:
requests:
cpu: 10m
memory: 150Mi
```
=> chore(templates): fix pre-delete-hook

images/kube-api-proxy/pkg/proxy/handler.go
Replace Accept header with aggregated discovery request with legacy discovery header (plain application/json). 
It is a workaround before implementing rewriter for the kind=APIGroupDiscoveryList
=> fix: force legacy discovery for Kubernetes 1.27+

images/virtualization-artifact/Taskfile.dist.yaml, images/virtualization-artifact/hack/mirrord.sh
add container-name flag for mirrord
task mirrord do not work if there is more than 1 container in the deployment
=> chore: add container-name flag for mirrord

images/virt-artifact/patches/014-delete-apiserver.patch, images/virt-artifact/patches/README.md
Add a patch to avoid creating kubevirt Apiservice.
=> chore(virt-operator): delete kubevirt ApiService

tests/performance/virtualization-dashboard.yaml
Dashboard name cannot be the same as folder.
=> fix(observability): fix dashboard title in tests

images/virtualization-artifact/hack/mirrord.sh, images/virtualization-artifact/pkg/controller/vmop/vmop_reconciler.go, images/virtualization-artifact/pkg/controller/vmop/vmop_reconciler_state.go
wait for the desired state of the vm
=> feat(controller, vmop): wait for the desired state of the vm

images/pre-delete-hook/entrypoint.sh, templates/cdi/cdi.yaml, templates/kubevirt/kubevirt.yaml
=> feat(module): rename core resources

images/virt-artifact/patches/013-virt-api-rate-limiter.patch, images/virt-artifact/patches/README.md, templates/kubevirt/kubevirt.yaml
When migrating a big number of virtual machines (>50), we encounter a bottleneck in virt-api in the form of a rate limiter that prevents migration completion.
A patch has been updated to virt-api, enabling the configuration of Burst for the rate limiter via an environment variable VIRT_API_RATE_LIMITER_BURST.
=> fix(core, kubevirt): add ability to configure burst for virt-api rate limiter

hooks/lib/hooks/manage_tenant_secrets.py
Module name is shown incorrectly in Deckhouse queue. "None" instead of "virtualization".
=> refactor(module): fix module name in webhook

images/cdi-artifact/werf.inc.yaml, images/virt-artifact/werf.inc.yaml
- Fail build if patch is not applied
Wrong patch do not stop build.
Before:
```
│ │ virt-artifact/setup  Apply /patches/001-bundle-extra-images.patch ... OK
│ │ virt-artifact/setup  Apply /patches/002-fix-vcpu-count-issue.patch ... OK
│ │ virt-artifact/setup  Apply /patches/003-macvtap-binding.patch ... OK
│ │ virt-artifact/setup  Apply /patches/007-tolerations-for-strategy-dumper-job.patch ... OK
│ │ virt-artifact/setup  Apply /patches/011-virt-api-authentication.patch ... OK
│ │ virt-artifact/setup  Apply /patches/012-support-kubeconfig-env.patch ... OK
│ │ virt-artifact/setup  Apply /patches/013-virt-api-rate-limiter.patch ... OK
│ │ virt-artifact/setup  Apply /patches/014-delete-apiserver.patch ... OK
│ │ virt-artifact/setup  Apply /patches/016-rename-install-strategy-labels.patch ... …
```
=> chore(ci): fix false positive patch applying

templates/dvcr/ nodegroupconfiguration.yaml
Fix the order of configuration steps to ensure that DVCR credentials are configured before merging containerd configurations.
We currently have a bashible step `032_configure_containerd.sh` with a weight of 32. This step merges the containerd configurations, which requires correct DVCR (Docker V2 Container Registry) credentials. To solve the problem where DVCR credentials must be configured in advance, this PR introduces a lower weight configuration step that runs before the containerd configuration step.
=> fix(core, dvcr):  configure dvcr creds before contatinerd config

images/base-ubuntu-jammy/werf.inc.yaml, images/kube-api-proxy/werf.inc.yaml, images/pre-delete-hook/werf.inc.yaml, images/virtualization-api/werf.inc.yaml, images/virtualization-controller/werf.inc.yaml, images/vmi-router/werf.inc.yaml
Use alt-linux instead of ubuntu as runtime environment.
=> chore(core): replace ubuntu base image with alt-linux

images/virtualization-artifact/pkg/controller/vmop/vmop_reconciler.go
Fix panic in UpdateStatus for non existing VM
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x210 pc=0x1785af0]
goroutine 459 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:116 +0x1fa
panic({0x1923d80, 0x2b55c10})
/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/deckhouse/virtualization-controller/pkg/controller/vmop.(*Reconciler).UpdateStatus(0xc000297c10?, {0x1e3c078?, 0xc002a8e3c0?}, {{{0xc000297c10?, 0x1e4f0f8?}, {0xc0006406c0?, 0x1e23f20?}}}, 0xc002a8e3f0, {{0x1e442e0, …
```
=> fix(vmop): fix panic if VM is not exist

images/kube-api-proxy/pkg/log/body.go, images/kube-api-proxy/pkg/log/differ.go, images/kube-api-proxy/pkg/proxy/handler.go, images/kube-api-proxy/pkg/proxy/stream_handler.go
++ add ns/name into message from differ
++ log full patches on all resources
++ log full rewritten query
++ log full original watch event in case of rewrite error
=> refactor(kube-api-rewriter): extra changes to #112

crds/virtualmachine.yaml
Set min max for blockdevicerefs list.
The blockDeviceRefs list can't be empty.
=> fix(vm): set min max for blockdevicerefs list

.github/workflows/ dev_build_precache.yml
We need not only to build a cache but also publish images
Prevent the case when, after cleaning the register, the deckhouse cannot push the virtualization module image pre-alpha or main
=> Chore(ci): fix cache build for main and pre-alpha

images/dvcr-artifact/werf.inc.yaml, images/dvcr-importer/werf.inc.yaml, images/dvcr-uploader/werf.inc.yaml, images/dvcr/werf.inc.yaml, images/kube-api-proxy/werf.inc.yaml, images/pre-delete-hook/werf.inc.yaml, images/virt-exportproxy/werf.inc.yaml, images/virt-launcher/werf.inc.yaml, images/virtualization-api/werf.inc.yaml, images/virtualization-controller/werf.inc.yaml, images/vmi-router/werf.inc.yaml
- dvcr-importer // alt-p10
- dvcr-uploader // alt-p10
- dvcr // scratch
- kube-api-proxy // scratch
- pre-delete-hook // alt-p10
- virtualization-api // scratch
- virtualization-controller // scratch
- vmi-router // scratch
Target - distroless images.
=> chore(core): use scratch and alt-p10 as base images

crds/embedded/cdi.yaml, crds/embedded/kubevirt.yaml, images/kube-api-proxy/pkg/kubevirt/kubevirt_rules.go, images/kube-api-proxy/pkg/rewriter/discovery.go, images/pre-delete-hook/entrypoint.sh, templates/cdi/cdi-operator/rbac-for-us.yaml, templates/cdi/cdi.yaml, templates/kubevirt/kubevirt.yaml, templates/kubevirt/virt-operator/rbac-for-us.yaml, templates/pre-delete-hook/rbac-for-us.yaml, templates/virtualization-controller/rbac-for-us.yaml
- DVP is a product name, use more generic prefix
- Change configuration CRDs for KubeVirt and CDI.
- Change manifests in templates: RBAC and configurations.
- Change pre-delete-hook.
=> refactor(kube-api-rewriter): remove dvp prefixes

images/kube-api-proxy/pkg/rewriter/resource.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter_test.go
- Add ResourceOrList tranformer around ownerReferences rewriter.
Fix KubeVirt error: "Failure while starting VMI: controllerrevisions.apps "revision-start-vm-NNNN-N" already exists'" when restarting VM
1. Create VM with runPolicy AlwaysOn
2. Restart virt-controller (scale replicas=0, scale replicas=1)
3. Restart VM from inside (d8 v console, sudo reboot)
4. VM should terminate and then start.
=> refactor(kube-api-rewriter): rewrite ownerReferences for Lists

templates/kubevirt/kubevirt.yaml
Set the parameters of the Qemu/KVM domain of the d8 virtual machine.
For automation purposes, we must unambiguously determine that the VM is running under the d8-virtualization module
```
root@linux-vm-virt-node:~# dmidecode -H 0x100
Getting SMBIOS data from sysfs.
SMBIOS 3.0.0 present.
Table at 0x7FFFFD90.
Handle 0x0100, DMI type 1, 27 bytes
System Information
Manufacturer: Flant
Product Name: DeckhouseVirtualizationPlatform
Version: pc-q35-8.2
Serial Number: Not Specified
UUID: dcbdb049-9d5f-5ff7-bd48-0aa6343bb1ed
Wake-up Type: Power Switch
SKU Number: Not Specified
Family: Deckhouse
```
=> refactor(core): set the parameters of the Qemu/KVM domain of the d8 virtual machine

images/virtualization-artifact/hack/mirrord.sh
Change the image virtualization-controller to alpine.
The virtualization controller is based on a scratch image and does not support cmd bash or sleep. That's why  tasks using mirrord are failed.
=> chore(dev): use alpine for mirrord

hooks/generate_secret_for_dvcr.py, hooks/lib/password_generator/htpasswd.py, hooks/test_generate_secret_for_dvcr.py, lib/python/requirements.txt, openapi/values.yaml, templates/dvcr/secret.yaml, werf.yaml
Generate htpasswd for dvcr using hook.
Func htpasswd in helm always generates a new hash, so the update helm-chart is equal to restarting dvcr.
Generating htpasswd from an hook solves this problem.
=> feat(core, dvcr): generate htpasswd from hook

images/virtualization-artifact/pkg/controller/cvi/internal/source/http.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vi/internal/source/http.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go
Errors from the pod were ignored during the transition of the image to the Ready phase. Fixed this.
=> fix(vi,cvi): fix pod errors handling

api/core/v1alpha2/finalizers.go, images/virtualization-artifact/pkg/controller/cvi/cvi_controller.go, images/virtualization-artifact/pkg/controller/cvi/internal/attachee.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go, images/virtualization-artifact/pkg/controller/vi/internal/attachee.go, images/virtualization-artifact/pkg/controller/vi/vi_controller.go
Added AttacheeHandler for VI and CVI. Without them, the protection finalizers set by the virtual machine would not be removed.
=> fix(cvi,vi): add attachee handlers

images/virtualization-artifact/pkg/controller/service/condition.go, images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/service/errors.go, images/virtualization-artifact/pkg/controller/vd/internal/source/blank.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go
=> fix(vd): copy error from data volume

api/core/v1alpha2/image_status.go, api/core/v1alpha2/zz_generated.deepcopy.go, api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go, images/virtualization-artifact/pkg/controller/common/util.go, images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/vd/internal/source/blank.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go
- Fixed the display of CD-ROM when calling `kubectl get vd` (previously, a false value was shown as empty).
- Now we wait for the PVC to reach the `Bound` phase to set the actual value for disk Capacity.
=> fix(vd,vi,cvi): fix capacity and cdrom

images/virtualization-artifact/pkg/controller/cvi/cvi_reconciler.go, images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go, images/virtualization-artifact/pkg/controller/vi/vi_reconciler.go, images/virtualization-artifact/pkg/controller/watchers/cvi_enqueuer.go, images/virtualization-artifact/pkg/controller/watchers/cvi_filter.go, images/virtualization-artifact/pkg/controller/watchers/object_ref_watcher.go, images/virtualization-artifact/pkg/controller/watchers/vd_enqueuer.go, images/virtualization-artifact/pkg/controller/watchers/vi_enqueuer.go, images/virtualization-artifact/pkg/controller/watchers/vi_filter.go
Added a Watchers to trigger a resource reconciliation if its DataSourceReady condition was False.
=> fix(vd,vi,cvi): add object ref watchers

api/core/v1alpha2/virtual_machine.go, api/core/v1alpha2/zz_generated.deepcopy.go, api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go, crds/doc-ru-virtualmachine.yaml, crds/virtualmachine.yaml, images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/provisioning.go
fix secret keys for provisioning. [userData, userdata]
add observedGeneration to VirtualMachine.Status
remove OwnerReference from pvc when DataVolume is removed
=> fix(vm):  lifecycle vm

images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/dvcr_data_source.go, images/virtualization-artifact/pkg/controller/monitoring/final_report.go, images/virtualization-artifact/pkg/controller/service/protection_service.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go
- When cloning from cvi/vi, there are no import statistics in the pod, statistics must be taken from controller.DVCRDataSource
- Fixed a hanging of the onwer ref in protection service, if nothing was hung, then we will not patch it.
=> fix(vd,vi,cvi): fix object ref datasource

images/virtualization-artifact/pkg/controller/vm/internal/cpu.go
fix panic in CPU handler when VMCPU does not exist
=> fix(vm): panic in cpu handler

images/virtualization-artifact/pkg/controller/ipam/claim_reconciler.go
=> fix(vmip): double lease

images/virtualization-artifact/pkg/controller/cvi/internal/datasource_ready.go, images/virtualization-artifact/pkg/controller/service/protection_service.go, images/virtualization-artifact/pkg/controller/vd/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vd/internal/source/blank.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go, images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go, images/virtualization-artifact/pkg/controller/vi/internal/datasource_ready.go
- OwnerRef Version should be `owner.GetObjectKind().GroupVersionKind().GroupVersion().String() `, but not `owner.GetObjectKind().GroupVersionKind().Version`
- Reconciliation event at the end of the DataVolume import
- Add missed ClusterVirtualImage reason for VI DatasourceReady condition
- Added logs for vd controller
=> fix(vd): add stats reconciliation

werf.yaml
Exclude python tests hooks from image
Tests should not be included in the final image
No such warning messages:
`{"level":"warning","msg":"File '/deckhouse/external-modules/virtualization/dev/hooks/lib/tests/testing.py' is skipped: no executable permissions, chmod +x is required to run this hook","time":"2024-07-01T12:20:20Z"}
`
=> chore(ci): remove python tests from image bundle

images/kube-api-proxy/pkg/rewriter/affinity.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter_test.go
- Rewrite metadata in patches for all resources.
- Rewrite labelSelector in url queries.
- Proper rewriter for affinity: more fields to rewrite.
- Fix error "syncing labels to pod: the server rejected our request due to an error in our request" when main controller sends metadata patch for pods.
- Fix error when cache is empty when watching with labelSelector.
- Full rewrite for affinity.
Main controller updates Pod metadata without issues.
=> refactor(kube-api-rewriter): fix patch rewriter, fix labelSelector rewriter

images/virtualization-artifact/pkg/controller/vm/internal/agent.go, images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/provisioning.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_metadata.go, images/virtualization-artifact/pkg/controller/vm/vm_controller.go, images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go
Add sync metadata handler.
We need to synchronize metadata such as labels and annotations from the virtual machine to child resources.
=> fix(vm): add sync metadata handler

crds/virtualmachine.yaml
Fix vm crd sysprep for windows
Fix error when create vm with sysprep
```
The VirtualMachine "win-vm" is invalid: 
* <nil>: Invalid value: "": "spec.provisioning" must validate one and only one schema (oneOf). Found none valid
* spec.provisioning.type: Unsupported value: "SysprepRef": supported values: "Sysprep"
```
VM with sysprep create successfully
=> chore(api/vm): fix vm crd

images/virtualization-artifact/pkg/controller/vm/internal/provisioning.go
controller panic if using sysprep
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x16d10f4]
...
(*ProvisioningHandler).Handle(0xc0000cddd0?, {0x1da3f90, 0xc000153b00}, {0x1dab240, 0xc0002d0800})
/usr/local/go/src/virtualization-controller/pkg/controller/vm/internal/provisioning.go:101 +0x554
=> fix(vm): controller panic if using sysprep

images/virtualization-artifact/pkg/controller/vm/internal/provisioning.go
fix(vm): do not check keys for sysprep secret
=> fix(vm): do not check keys for sysprep secret

images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go, images/virtualization-artifact/pkg/controller/vmchange/comparators.go
force the startup of a VM with an AlwaysOnUnlessStoppedManually policy when creating
A VM with an AlwaysOnUnlessStoppedManually policy is created stopped
=> fix(vm): force the startup of a VM with an AlwaysOnUnlessStoppedManually policy when creating

images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go, images/virtualization-artifact/pkg/controller/vmchange/comparators.go
Clean irrelevant changes from status.
Sync info for block devices from KVVMI.
Wrong status
=> fix(vm): fix blockdevices status and restartawaitingchanges

crds/embedded/kubevirt.yaml, images/kube-api-proxy/pkg/kubevirt/kubevirt_rules.go, templates/cdi/cdi-operator/rbac-for-us.yaml
- operator.kubevirt.io to operator.kubevirt.internal.virtualization.deckhouse.io
- allow operator to update renamed validatingwebhookconfiguration cdi-internal-virtualization-objecttransfer-api-validate
CDI installation failed because of wrong rbac.
=> refactor(core): lost renames in templates

images/virt-artifact/patches/004-backport-10001-from-upstream.patch, images/virt-artifact/patches/README.md
Backport PR 10001 from upstream
Fix errors "Failed to create metric for VMIs phase" in virt-controller.
No errors about VMIs metrics in virt-controller logs.
=> refactor(kubevirt): backport fix for VMIs metric

images/kube-api-proxy/pkg/rewriter/metadata.go
- Support patches with paths like "/metadata/annotations/annoName", "/metadata/labels/group.io~1labelName"
No errors about PDB in virt-controller logs:
```
{"component":"virt-controller","kind":"","level":"info","msg":"shrinking pdb vm/kubevirt-internal-virtualization-disruption-budget-qzp7n due to migration completion","name":"cloud-alpine","namespace":"vm","pos":"disruptionbudget.go:549","timestamp":"2024-07-05T18:49:33.610935Z","uid":"af3bf7f8-abf3-4760-b572-463bc338b70a"}
```
Rename in patch diff in proxy logs:
```
2024-07-05 18:48:04.503 DEBUG Request PATCH: changes after rewrite for /// proxy.name="kube-api" request="PATCH /apis/policy/v1/namespaces/vm/poddisruptionbudgets/kubevirt-internal-virtualization-disruption-budget-qzp7n" resource="poddisruptionbudgets"
body.diff:
@ …
```
=> refactor(kubevirt): add rename for specific label/annotation/finalizer in JSON patches

images/virtualization-artifact/pkg/controller/service/condition.go, images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/vd/internal/resizing.go, images/virtualization-artifact/pkg/controller/vd/internal/resizing_test.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go, images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go
When resizing a PVC directly, the VD status did not previously update with this information. It will now be updated.
=> fix(vd): synchronize PVC status changes with VD status updates

images/virtualization-artifact/pkg/controller/vd/internal/source/blank.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go
Set the Ready or Lost phase on each reconciliation of the virtual disk.
The VD resizes only when the PVC is resizing.
=> fix(vd): set ready phase

images/virtualization-artifact/pkg/controller/cvi/internal/attachee.go, images/virtualization-artifact/pkg/controller/service/resource.go, images/virtualization-artifact/pkg/controller/vd/internal/attachee.go, images/virtualization-artifact/pkg/controller/vd/internal/datasource_ready.go, images/virtualization-artifact/pkg/controller/vd/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vd/internal/mock.go, images/virtualization-artifact/pkg/controller/vd/internal/source/blank.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vi/internal/attachee.go
Do not add protection to a resource that is in the process of being deleted.
=> fix(vd): protection for deleted resource

templates/virtualization-controller/deployment.yaml
- add env: section to proxy container in virtualization-controller
logLevel: debug should enable debug for proxy container in virtualization-controller
=> chore(core): fix debug level for proxy in virtualization-controller

images/virtualization-artifact/pkg/controller/vm/internal/sync_metadata.go
Clear annotations and labels from child resources after removing them from the vm.
We need to sync metadata with child resources, but for now we can only add labels and annotations.
=> fix(vm): clear annotations and labels from child resources after removing them from the vm

images/vmi-router/controllers/vmirouter_reconciler.go, images/vmi-router/netlinkmanager/manager.go
fix reconsile VM. refactor DeleteRoute. 
vm-router panics when we delete a virtual machine.
=> fix(vm): fix vm-router panics when we delete a virtual machine. 

images/cdi-artifact/patches/010-rename-apigroups-in-starred-rbac.patch, images/cdi-artifact/patches/README.md, images/virt-artifact/patches/016-rename-apigroups-in-starred-rbac.patch, images/virt-artifact/patches/README.md
Temporary fix to stop stop continuous updating of ClusterRoles. '*' in resources field prevent proper restoring of apiGroup in Role/ClusterRole. We should rename each apiGroup to unique value, and not to one.
This PR reduces Reconcile loops and noise in logs for each reconcile:
```
{"component":"virt-operator","level":"info","msg":"ClusterRole kubevirt-internal-virtualization-controller updated","pos":"rbac.go:83","timestamp":"2024-07-10T15:48:23.123929Z"}
```
=> refactor(core): replace * with resource to stop continuous updating of ClusterRoles

templates/_kube_api_rewriter.tpl, templates/cdi/_helpers.tpl, templates/cdi/cdi-operator/deployment.yaml, templates/kubevirt/_helpers.tpl, templates/kubevirt/virt-operator/deployment.yaml, templates/virtualization-controller/deployment.yaml
- Add defaultMode, so virt-operator and cdi-operator see no changes in deployments after patching.
- API server returns defaultMode field and operators detect changes.
Reduce Reconcile loops.
We can patch Deployment and Daemonset comparators in operators, but it is simpler to add defaultMode in templates and configs.
=> refactor(core): stop continuous updating of deployments

images/kube-api-proxy/pkg/rewriter/admission_review.go, images/kube-api-proxy/pkg/rewriter/crd.go, images/kube-api-proxy/pkg/rewriter/metadata.go, images/kube-api-proxy/pkg/rewriter/resource.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter.go
- Add rewrite for JSON patch path /metadata/ownerReferences
Patch from mutating hook may leave original kind and apiGroup in ownerReferences and resource may be deleted, e.g. VirtualMachineInstance.
=> refactor(kube-api-rewriter): fix rewriting metadata for CRD patching

images/kube-api-proxy/pkg/proxy/stream_handler.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter.go
Add rewriter for BOOKMARK WatchEvents. This rewriter restores only kind and apiVersion.
Stop errors in stream handler, prevent re-establising watch on each CRD event by the client, prevent excessive Lists.
```
main controller:
W0710 11:55:53.470204       1 reflector.go:347] pkg/controller/virtinformers.go:348: watch of *v1.CustomResourceDefinition ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: couldn't get version/kind; json parse error: unexpected end of JSON input") has prevented the request from succeeding
proxy:
{"time":"2024-07-10T13:13:34.143132596Z","level":"ERROR","msg":"Watch event 'BOOKMARK': transform error","request":"GET /apis/apiextensions.k8s.io/v1/customresourcedefinitions","resource":"customresourcedefini …
```
=> refactor(kube-api-rewriter): fix errors related to BOOKMARK WatchEvents

images/kube-api-proxy/pkg/log/differ.go, images/kube-api-proxy/pkg/proxy/handler.go
Print debug diff only if rewritten buffer is not nil.
Fix false negative error in logs:
```
2024-07-10 16:22:54.207 ERROR Request: non-empty body [668] produces empty rewrite proxy.name="kube-api" request="POST /api/v1/namespaces/d8-virtualization/events" resource="events"
```
No non-empty body errors for Events.
=> refactor(kube-api-rewriter): fix "non-empty body produces empty rewrite"

images/cdi-artifact/Taskfile.yaml, images/cdi-artifact/patches/009-remove-upload-apiservice.patch, images/cdi-artifact/patches/README.md, images/kube-api-proxy/Taskfile.dist.yaml, images/kube-api-proxy/local/proxy.yaml, images/kube-api-proxy/pkg/kubevirt/kubevirt_rules.go, images/kube-api-proxy/pkg/proxy/handler.go, images/kube-api-proxy/pkg/proxy/stream_handler.go, images/kube-api-proxy/pkg/rewriter/affinity.go, images/kube-api-proxy/pkg/rewriter/app_test.go, images/kube-api-proxy/pkg/rewriter/crd.go, images/kube-api-proxy/pkg/rewriter/discovery.go, images/kube-api-proxy/pkg/rewriter/list.go, images/kube-api-proxy/pkg/rewriter/metadata.go, images/kube-api-proxy/pkg/rewriter/prefixed_name_rewriter.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter_test.go, images/kube-api-proxy/pkg/rewriter/rules.go, images/kube-api-proxy/pkg/rewriter/rules_test.go, images/virt-artifact/Taskfile.yaml, images/virt-artifact/patches/015-rename-core-resources.patch, images/virt-artifact/patches/016-rename-install-strategy-labels.patch, images/virt-artifact/patches/018-rename-devices-kubevirt-io.patch, images/virt-artifact/patches/README.md, templates/kubevirt/kubevirt.yaml
- Rewrite app.kubernetes.io/managed-by labels value
- Rewrite names for validatingwebhooks, mutatingwebhooks in Kubevirt.
- Add deduplication and anti-shadowing algorithms: delete original resources from discovery and CRD list, prefix original labels on restore, un-prefix on rename.
- Rename devices on nodes and change device plugin socket path, so virt-handlers can live together.
- Remove upload.cdi.kubevirt.io ApiService.
DVP can work together with original CDI and KubeVirt in the same cluster.
Working scenarios:
1. Ensure DVP is installed
2. Install CDI and KubeVirt, enable LiveMigration in Kubevirt CR.
3. Launch VM in DVP and in original KubeVirt. Ensure PVCs are created and both VMs are in the Running state.
4. Migrate both VMs. Ensure both are migrated.
5. Uninstall KubeVirt and …
=> refactor(core): more renames to not overlap with original Kubevirt and CDI

images/virtualization-artifact/pkg/controller/vd/internal/source/blank.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go
fix panic if pvc is not exist
we don't likes panic
=> fix(vd): fix panic if pvc is not exist

api/core/v1alpha2/events.go, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_utils.go, images/virtualization-artifact/pkg/controller/vd/internal/attachee.go, images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vmbda/internal/watcher/kvvmi_watcher.go
the virtual disk must be attached to only one virtual machine
we do not support shared disks for virtual machines
=> feat(vm):  VD must be attached to only one virtual machine

werf.yaml
Get rid of huge deprecation warning after build.
=> chore(module): change last artifact to image in werf.yaml

images/virt-artifact/patches/019-remove-deprecation-warnings-from-crds.patch, images/virt-artifact/patches/README.md
Make DeprecationWarning fields empty for all KubeVirt CRDs.
Virtualization-controller don't use deprecated versions. Deprecation warning are distracting in our case.
No deprecation warning in `kubectl -n ns get all` output.
=> refactor(kube-api-rewriter): remove deprecation warnings from CRDs

api/core/v1alpha2/block_device.go, api/core/v1alpha2/vmcondition/condition.go, api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go, crds/doc-ru-virtualmachine.yaml, crds/virtualmachine.yaml, images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vm/internal/state/state.go, images/virtualization-artifact/pkg/controller/vmbda/vmbda_webhook.go
Add the `attached`, `hotplugged` and `virtualMachineBlockDeviceAttachmentName` fields to the status block device refs
Renamed ReasonBlockDevicesAttachmentReady and ReasonBlockDevicesAttachmentNotReady reasons
=> feat(vm): add the attached field to the status block device refs

api/core/v1alpha2/finalizers.go, images/virtualization-artifact/pkg/controller/powerstate/shutdown_reason.go, images/virtualization-artifact/pkg/controller/vm/internal/pod.go, images/virtualization-artifact/pkg/controller/vm/internal/state/state.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go, images/virtualization-artifact/pkg/controller/vm/vm_controller.go
Add pod  handler
We should protect the pods because we need to receive a termination message.
=> feat(vm): add pod handler

images/virt-launcher/werf.inc.yaml
Remove files in /usr/share/OVMF in virt-launcher image to mimic file structure in original KubeVirt image.
- Windows 11 should not alert "this PC is not compatible" and proceed installation with sysprep.
- KubeVirt should generate xml template with OVMF_CODE.secboot.fd nvram template as original KubeVirt.
=> fix(kubevirt): restructure edk2-ovmf files

images/virtualization-artifact/pkg/controller/vmip/internal/lifecycle_handler.go, images/virtualization-artifact/pkg/controller/vmip/internal/protection_handler.go
Added waiting for the virtual machine to complete.
Fix bug with sticking VirtualMachineIPAddres in 'Bound' phase after deleting the virtual machine.
=> fix(vmip): sticking in bound phase

api/core/v1alpha2/vmipcondition/condition.go, images/virtualization-artifact/pkg/controller/service/errors.go, images/virtualization-artifact/pkg/controller/service/ip_address_service.go, images/virtualization-artifact/pkg/controller/service/ip_address_service_test.go, images/virtualization-artifact/pkg/controller/vmip/internal/iplease_handler.go, images/virtualization-artifact/pkg/controller/vmip/internal/lifecycle_handler.go, images/virtualization-artifact/pkg/controller/vmip/internal/protection_handler.go, images/virtualization-artifact/pkg/controller/vmip/vmip_controller.go, images/virtualization-artifact/pkg/controller/vmip/vmip_webhook.go, images/virtualization-artifact/pkg/controller/vmiplease/internal/retention_handler.go
- Add handling case, when trying to create VirtualMachineIPAddress outside the range specified in the module settings
- Add reason "VirtualMachineIPAddressOutOfTheValidRange" for "Bound" condition
- Refactor ip_address_service  with the use of net.IPNet to netip.Addr 
- Fix frequent reconciles for an object with the 'Released' status
- Add write to events, when the selected VirtualMachineIPLease belongs to a different namespace
=> feat(vmip): validate IP address range and improve IP address service

images/kube-api-proxy/Taskfile.dist.yaml, images/kube-api-proxy/local/proxy.yaml, images/kube-api-proxy/pkg/rewriter/discovery.go, images/kube-api-proxy/pkg/rewriter/discovery_test.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter.go, images/kube-api-proxy/pkg/rewriter/rules.go
- Fix APIResourcesList rewriter: Keep version in groupVersion, do not replace with PreferredVersion to prevent duplicates in Kubernetes <=1.26.
- Fix APIGroupList rewriter: Rewrite response instead of reconstructing group description from rules.
- Add test for APIGroupList restoring.
- Use localhost:5000 for local proxy deployment.
Error on Kubernetes 1.26:
```
{"level":"error","ts":"2024-07-26T15:36:03Z",
"logger":"controller-runtime.source",
"msg":"failed to get informer from cache",
"error":"cdi.kubevirt.io/, Kind=CDI matches multiple kinds
[cdi.kubevirt.io/v1beta1, Kind=CDI cdi.kubevirt.io/v1beta1, 
Kind=CDI cdi.kubevirt.io/v1beta1, Kind=CDI cdi.kubevirt.io/v1beta1, 
Kind=CDI cdi.kubevirt.io/v1beta1, Kind=CDI cdi.kubevirt.io/v1beta1, 
Kind=CDI cdi.kubevirt.io/v1beta1, Kind=CDI …
```
=> refactor(kube-api-rewriter): fix APIResourcesList rewriter

api/client/kubeclient/client.go, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_test.go, tests/performance/shatal/internal/shatal/creator.go
* fix panic when generating kvvm with affinity
* fix virtclient. Add VirtualMachineClass and remove old VirtualMachineCpuModel
* fix shatal
=> fix(vm): fix panic and virtClient

images/virtualization-artifact/pkg/controller/vmip/internal/iplease_handler.go, images/virtualization-artifact/pkg/controller/vmip/vmip_reconciler.go
Remove from controller requeue when waiting for VirtualMachineIPAddressLease
=> refactor(vmip): remove requeue

images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_utils.go
- Add bootOrder field to all disks in KVVM.
Qemu uses Seabios firmware when bootloader is set to BIOS. Unlike UEFI, Seabios doesn't scan devices and boot only from the first attached hdd. bootOrder should be set on each disk to tell qemu to boot from other disks.
CDROM position is not important, VM always boots from the first HDD:
```
spec:
blockDeviceRefs:
- kind: VirtualDisk
name: ubuntu-iso-boot-root
- kind: ClusterVirtualImage
name: ubuntu-22-04-server-iso
bootloader: BIOS
```
```
spec:
blockDeviceRefs:
- kind: ClusterVirtualImage
name: ubuntu-22-04-server-iso
- kind: VirtualDisk
name: ubuntu-iso-boot-root
bootloader: BIOS
```
The result is this:
Set HDD as a first disk and a CDROM as a second to boot from HDD after installer reboots VM:
```
spec:
blockDeviceRefs:
- kind: VirtualDisk …
```
=> fix(vm): proper boot from VirtualImage and ClusterVirtualImage

images/libguestfs/werf.inc.yaml
edk-ovmf is updated in Sisyphus branch, use p11 to get pinned version.
Quick workaround to fix 0.11.0 build.
=> fix(ci): use p11 branch for additional packages for libguestfs image

templates/user-authz-cluster-roles.yaml
Fix the misconfiguration for the Admin role
=> fix(module): fix RBAC for Admin

.github/workflows/release_release-please.yml
- Use action from googleapis organization, google-github-actions/release-please-action is deprecated and archived.
- Get rid of this warning in "[Release please](https://github.com/deckhouse/virtualization/actions/workflows/release_release-please.yml)" workflow:
=> refactor(ci): update release-please-action

images/virtualization-artifact/pkg/controller/indexer/indexer.go, images/virtualization-artifact/pkg/controller/vmip/internal/state/state.go
- fix the issue of creating a lease duplicate
- fix the issue of lease sticking
=> fix(vmip): create double lease

images/virtualization-artifact/pkg/controller/vm/internal/pod.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_metadata.go
remove pod finalizers after pod completion
=> fix(vm):  remove pod finalizers after pod completion

images/virtualization-artifact/cmd/virtualization-controller/main.go, images/virtualization-artifact/pkg/common/common.go, images/virtualization-artifact/pkg/config/load_import_settings.go, images/virtualization-artifact/pkg/controller/cvi/cvi_controller.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/http.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/sources.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/upload.go, images/virtualization-artifact/pkg/controller/service/importer_service.go, images/virtualization-artifact/pkg/controller/service/uploader_service.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go, images/virtualization-artifact/pkg/controller/vi/internal/source/http.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vi/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vi/vi_controller.go, openapi/config-values.yaml, openapi/doc-ru-config-values.yaml, templates/cdi/cdi.yaml, templates/virtualization-controller/_helpers.tpl
- Disk and image controllers can now handle 'quota exceeded' errors and update the condition with a corresponding message.
- A new field in the module configuration, `importerResourceRequirements`, specifies the requests and limits for importers.
- These values are applied to both our importers and CDI importers.
- The default values are taken from the previous CDIConfig.
=> feat(api): add importer's requests and limits for virtualization config

images/vm-route-forge/cmd/vm-route-forge/app/options/options.go, images/vm-route-forge/cmd/vm-route-forge/app/root.go, images/vm-route-forge/internal/cache/cache.go, images/vm-route-forge/internal/controller/route/ebpf.go, images/vm-route-forge/internal/controller/route/netlink.go, images/vm-route-forge/internal/controller/route/route_controller.go, images/vm-route-forge/internal/controller/route/ticker.go, images/vm-route-forge/internal/controller/route/util.go, images/vm-route-forge/internal/controller/route/watch.go, images/vm-route-forge/internal/netlinkmanager/manager.go, images/vm-route-forge/internal/netlinkwrap/funcs_linux.go, images/vm-route-forge/internal/netlinkwrap/funcs_others.go
add route Watcher interface (Watcher tracks routes on the host)
add a new Watcher implementation - ticker
We needs to track routes on the host. Therefore, a new interface is being introduced. Now there are 2 implementations, ticker and netlink
=> feat(vm-route-forge): add route interface

images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go, images/virtualization-artifact/pkg/controller/vm/internal/stats.go, images/virtualization-artifact/pkg/controller/vm/internal/stats_test.go
add ut for statistic handler
we don't have any ut to check generated stats for vm
=> fix(vm): add unittests for statistic handler

images/virtualization-artifact/pkg/controller/ipam/ipam.go, images/virtualization-artifact/pkg/controller/vmip/internal/state/state.go
- The function of getting the VirtualMachine name from the VirtuslMachineIPAddress name has been redesigned
- Fix panic that occurs if name VirtualMachineIPAddress is shorter than 6 characters
=> fix(vmip): changes to the resource name generation algorithm

templates/kubevirt/service-monitor.yaml, templates/virtualization-controller/service-monitor.yaml
Rename and relabel all internal virtualization metrics
Ensures clearer, more intuitive, and standardized metric names and labels, improving monitoring, ease of integration, and operational efficiency.
All metrics are now prefixed with `d8_virtualization_*`
=> chore(module): relabel internal vitualization metrics

images/virtualization-artifact/pkg/controller/vmip/internal/state/state.go
- Fix bug of creating two VirtualMachineIPAddress with the same name in different namespaces
=> fix(vmip): fix bug of creating two VirtualMachineIPAddress with the same name in different namespaces

api/core/v1alpha2/vmbdacondition/condition.go, images/virtualization-artifact/pkg/controller/service/attachment_service.go, images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/block_device_refs_validator.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/ipam_validator.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/meta_validator.go, images/virtualization-artifact/pkg/controller/vm/vm_webhook.go, images/virtualization-artifact/pkg/controller/vmbda/internal/life_cycle.go
1. For vmbda, added a message to the condition that indicates a disk conflict if disk is already added to the virtual machine spec
2. Fixed an issue that prevented adding a disk to the spec when the vmbda with that disk was deleted for the virtual machine.
3. Failed phase is no longer final for vmbda (it can transition to Pending).
4. New validator for VM: BlockDeviceSpecRefsValidator, which prevents duplicate spec.BlockDeviceRef entries.
5. VM validators have been moved to internal/validators.
=> fix(vmbda): write to condition message if disk is already attached to vm spec

images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/vd/internal/source/blank.go, images/virtualization-artifact/pkg/controller/vd/internal/source/errors.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go
Write error to Ready condition, if pvc.persistentVolumeClaim.size is smaller than source image virtual size
=> fix(vd): write error to condition if pvc size is smaller than virtual size of source image

api/core/v1alpha2/vmipcondition/condition.go, images/virtualization-artifact/pkg/controller/vmip/internal/iplease_handler.go, images/virtualization-artifact/pkg/controller/vmip/internal/lifecycle_handler.go, images/virtualization-artifact/pkg/controller/vmiplease/internal/retention_handler.go
- Add requeue after 30s
- Fix message in recording event
- Add log for case, when create VirtualMachineIPAddress in different namespace
Fix bug with create VirtualMachineIPAddress in different namespace, when VirtualMahineIPAddressLease 'Released'
=> fix(vmip): fix bug with create VirtualMachineIPAddress in different namespace, when VirtualMahineIPAddressLease 'Released'

api/core/v1alpha2/virtual_machine_class.go, crds/virtualmachineclasses.yaml
Fix .spec.sizingPolicy.memory fields: `perCore` and `step` are not required
=> fix(vmclass) fix sizingPolicy fields

images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go
added processing of an empty phase for a VM and KVVM
Phase "" does not exist
`virtualization-controller-85dd874684-26cqc virtualization-controller {"time":"2024-08-12T14:46:13.571098442Z","level":"ERROR","msg":"Reconciler error","controller":"vm-controller","namespace":"testcases","name":"vm-c-and-a","reconcileID":"2d2a1740-56cb-44f7-84b5-63bce1eff661","err":"error updating status subresource: VirtualMachine.virtualization.deckhouse.io \"vm-c-and-a\" is invalid: status.phase: Unsupported value: \"\": supported values: \"Pending\", \"Running\", \"Degraded\", \"Terminating\", \"Stopped\", \"Stopping\", \"Starting\", \"Migrating\", \"Pause\""}`
=> fix(vm): added processing of an empty phase for a VM and KVVM

templates/nodegroupconfiguration-redos.yaml
When selinux is enabled on RedOS, `selinux-policy` and `container-selinux` packages must be installed on the system for virtualization to work properly.
When selinux is enabled, virt-handler will not be able to run on nodes and creating virtual machines will not be possible
Virtualmachine can be started if selinux is enabled.
> Package `selinux-policy` require restart system, if not previously installed
=> chore(core): install necessary packages for redos when selinux enabled

templates/nodegroupconfiguration-aio-max-nr.yaml
Increase aio-max-nr on servers where enabled virtualization
On sets with a large number of VMs, the machines can't schedule, the kernel needed to tune.
aio-max-nr=1048576
A VM can be scheduled and started
=> chore(core): set aio-max-nr kernel param

crds/virtualdisk.yaml, images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/vd/internal/source/blank.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go
Remove PV protection and deletion by controller
=> fix(vd): remove pv protection

images/virtualization-artifact/pkg/controller/monitoring/final_report.go, images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/service/internal/size.go, images/virtualization-artifact/pkg/controller/service/internal/size_test.go, images/virtualization-artifact/pkg/controller/service/stat_service.go, images/virtualization-artifact/pkg/controller/service/stat_service_test.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vd/internal/validators/pvc_size_validator.go, images/virtualization-artifact/pkg/controller/vd/internal/validators/spec_changes_validator.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go, images/virtualization-artifact/pkg/controller/vd/vd_webhook.go, images/virtualization-artifact/pkg/controller/vm/vm_webhook.go, images/virtualization-artifact/pkg/util/util_test.go
To support importing images into virtual disks, now automatically increase the image size when creating the image, rather than increasing the disk size when creating the disk (adjust a percentage of the size to all images for creating a CDI scratch pvc).
=> feat(api): adjust image size

api/core/v1alpha2/vmipcondition/condition.go, api/core/v1alpha2/vmiplcondition/condition.go, images/virtualization-artifact/pkg/controller/conditions/builder.go, images/virtualization-artifact/pkg/controller/conditions/manager.go, images/virtualization-artifact/pkg/controller/conditions/stringer.go, images/virtualization-artifact/pkg/controller/service/condition.go, images/virtualization-artifact/pkg/controller/vm/internal/agent.go, images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vm/internal/class.go, images/virtualization-artifact/pkg/controller/vm/internal/ipam.go, images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/provisioning.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go, images/virtualization-artifact/pkg/controller/vmclass/internal/discovery.go, images/virtualization-artifact/pkg/controller/vmclass/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vmclass/internal/util.go, images/virtualization-artifact/pkg/controller/vmip/internal/iplease_handler.go, images/virtualization-artifact/pkg/controller/vmip/internal/lifecycle_handler.go, images/virtualization-artifact/pkg/controller/vmip/internal/state/state.go, images/virtualization-artifact/pkg/controller/vmip/vmip_webhook.go, images/virtualization-artifact/pkg/controller/vmiplease/internal/lifecycle_handler.go, images/virtualization-artifact/pkg/controller/vmiplease/internal/retention_handler.go
1. Ensure for all controllers that LastTransitionTime reflects the last time the condition transitioned from one status to another (not just any condition update), in accordance with the Kubernetes documentation.
2. Get rid of the deprecated Reason method and NewConditionBuilder function. Use the renamed Reason2 method and NewConditionBuilder2 function instead.
3. The conditions.Manager is now deprecated. It is recommended to use conditions.SetCondition instead.
No motivation was found to use conditions.Manager over directly updating conditions. Since conditions.Manager is deprecated, it is recommended to use conditions.SetCondition instead.
=> fix(vd): ensure last transition time for conditions

images/virtualization-artifact/pkg/controller/vd/internal/source/errors.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vd/internal/validators/iso_source_validator.go, images/virtualization-artifact/pkg/controller/vd/vd_webhook.go
Deny disks creation with iso data source (object ref or http):
1. write error message to Faield condition
2. validate image format in webhook
=> feat(vd): deny iso source

images/virtualization-artifact/hack/dlv-controller.Dockerfile, images/virtualization-artifact/hack/dlv.sh
replace busybox image with musl on glibc
dlv cannot be started
=> chore(dev): replace busybox image with musl on glibc

images/virt-artifact/patches/017-fix-vmi-subresource-url.patch
Add `addvolume/removevolume` rules to ClusterRole of virt-controller.
=> fix(vmbda): fix sa rules

images/virtualization-artifact/hack/dlv.sh
fix uuidgen for mac
the generated repository name must be in lowercase
=> chore(dev): fix uuidgen for mac

images/virtualization-artifact/pkg/apiserver/api/install.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/add_volume.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/console.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/freeze.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/portforward.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/remove_volume.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/stream.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/unfreeze.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/vnc.go, images/virtualization-artifact/pkg/apiserver/registry/vm/storage/storage.go, images/virtualization-artifact/pkg/apiserver/server/config.go, images/virtualization-artifact/pkg/apiserver/server/informer.go
impl delete method for subresource virtualmachine on apiserver
`kubectl delete virtualmachine` causes an error because a subresource with the same name is used
```bash
❯ kubectl get vm 
NAME          PHASE     NODE                   IPADDRESS    AGE
linux-vm-01   Running   dev-rnd-virtlab-yb-1   10.66.10.1   58s
❯ kubectl delete virtualmachine linux-vm-01 
virtualmachine.subresources.virtualization.deckhouse.io "linux-vm-01" deleted
❯ kubectl get vm 
NAME          PHASE         NODE                   IPADDRESS    AGE
linux-vm-01   Terminating   dev-rnd-virtlab-yb-1   10.66.10.1   74s
```
=> fix(vm): impl delete method for subresource virtualmachine on apiserver

images/virtualization-artifact/Taskfile.dist.yaml, images/virtualization-artifact/hack/dlv-apiserver.Dockerfile, images/virtualization-artifact/hack/dlv.sh, images/virtualization-artifact/pkg/apiserver/registry/vm/storage/storage.go, images/virtualization-artifact/pkg/apiserver/registry/vm/storage/util.go
fix panic with nil labelselector
=> fix(vm): fix panic with nil labelselector

images/virtualization-artifact/pkg/controller/common/util.go, images/virtualization-artifact/pkg/controller/kvbuilder/dv.go, images/virtualization-artifact/pkg/controller/service/disk_service.go
override pvc parameters using annotations in StorageClass
=> feat(vd): override virtualdisk's pvc parameters via StorageClass annotations

images/vm-route-forge/Taskfile.yaml, images/vm-route-forge/internal/controller/route/route_controller.go
Add a check that the node on which the VM will be running has been identified
We have too many logs when there is no node defined for the VM to run.
```
vm-route-forge-dfw4s vm-route-forge 2024-09-09T16:14:36Z    ERROR    vm-route-forge    re-enqueuing VirtualMachine console-review/cooing-wildfowl-erinn    {"controller": "routeController", "error": "ciliumNode has no CiliumInternalIP specified"}
vm-route-forge-dfw4s vm-route-forge vm-route-forge/internal/controller/route.(*Controller).worker.func1
vm-route-forge-dfw4s vm-route-forge     /app/images/vm-route-forge/internal/controller/route/route_controller.go:252
vm-route-forge-dfw4s vm-route-forge vm-route-forge/internal/controller/route.(*Controller).worker
vm-route-forge-dfw4s vm-route-forge …
```
=> fix(vm-route-forge): add check to ensure VM host node is identified

api/core/v1alpha2/cluster_virtual_image.go, api/core/v1alpha2/cvicondition/condition.go, crds/clustervirtualimages.yaml, crds/doc-ru-clustervirtualimages.yaml, images/virtualization-artifact/pkg/controller/cvi/internal/datasource_ready.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/errors.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/interfaces.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/mock.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/service/importer_service.go, images/virtualization-artifact/pkg/controller/vi/internal/source/interfaces.go, images/virtualization-artifact/pkg/controller/vi/internal/source/mock.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vi_on_pvc.go
Add creating an ClusterVirtualImage from a VirtualDisk, provided that the VirtualDisk is not connected to a VirtualMachine or to a disabled VirtualMachine.
=> feat(cvi): create from vd

images/virtualization-artifact/pkg/controller/cvi/cvi_controller.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/interfaces.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/mock.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/service/importer_service.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go
Fixed an error inside the CleanUp call that caused the finalizer not to be removed from ClusterVirtualImage
=> fix(cvi): fix cleanup for resources

images/vm-route-forge/internal/controller/route/route_controller.go, images/vm-route-forge/internal/netlinkmanager/manager.go
add routes for subnets in blackhole
=> feat(vm-route-forge): add routes for subnets in blackhole

images/virtualization-artifact/pkg/controller/gc/cron_source.go, images/virtualization-artifact/pkg/controller/vm/gc.go, images/virtualization-artifact/pkg/controller/vmop/gc.go, templates/virtualization-controller/_helpers.tpl
* leave only last 10 resources
* replace ttl for vmop with 24h
* replace ttl for vmi migration with 24h
* replace schedule for vmop with every hour
* replace schedule for vmi migration with every hour
=> feat(gc): leave only last 10 resources

images/virtualization-artifact/pkg/controller/vm/internal/statistic.go
round the runtimeOverhead to Mi
Displaying the parameter in bytes is not human readable
=> feat(vm): round the runtimeOverhead to Mi

CONTRIBUTING.md, images/base-alt-p10/werf.inc.yaml, images/virt-launcher/werf.inc.yaml, images/virtualization-artifact/werf.inc.yaml, werf.yaml
We don't need base images, builder and artifacts in images_digests.json
Reduce the size of transferred data to the customer's container registry
Example:
```
kubectl -n d8-system exec -ti -c deckhouse deploy/deckhouse -- deckhouse-controller global values -o json | jq .modulesImages.digests.virtualization -r           
{
"cdiApiserver": "sha256:90f7f47801ebe97a8cdf6b147c490c739f04a80a64dbad6def99361e58395101",
"cdiCloner": "sha256:64bf203e560e4eb0f9a6cd40226131bf15fac98673ddd9521f6ebe24de570378",
"cdiController": "sha256:6373e5c470f7fd24918ed2aee976c35ea79ec10864ee9be10ee931f605ccdaf6",
"cdiImporter": "sha256:956132fffe289407cdbb48cbe5c87bbf1474b54a77d5668dfc1b8d43635e61b9",
"cdiOperator": "sha256:f82083faf236e2a0d8b8c777d3aedaabdc7634a643bf44077ba54a7ba19e36ee",
"cdiUploadproxy": …
```
=> chore(module): remove builders and artifacts from images_digests.json

images/virtualization-artifact/pkg/controller/common/util.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/interfaces.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/mock.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/upload.go, images/virtualization-artifact/pkg/controller/service/stat_service.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vi/internal/source/interfaces.go, images/virtualization-artifact/pkg/controller/vi/internal/source/mock.go, images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go
Wait for uploader to be ready to process user's upload
=> fix(api): wait for uploader to be ready to process user's upload

images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/vi/internal/source/http.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/vi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vi/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go
This PR fixes the problem where creating a VirtualImage (VI) from a VirtualDisk (VD) caused the application to panic.
=> fix(vi): fix panic when creating vi from vd

api/core/v1alpha2/virtual_machine_ip_address.go, crds/doc-ru-virtualmachineipaddresses.yaml, crds/virtualmachineipaddresses.yaml, images/virtualization-artifact/pkg/controller/common/util.go, images/virtualization-artifact/pkg/controller/indexer/indexer.go, images/virtualization-artifact/pkg/controller/ipam/ipam.go, images/virtualization-artifact/pkg/controller/vm/internal/ipam.go, images/virtualization-artifact/pkg/controller/vm/internal/state/state.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/ipam_validator.go, images/virtualization-artifact/pkg/controller/vmchange/comparators.go, images/virtualization-artifact/pkg/controller/vmip/internal/lifecycle_handler.go, images/virtualization-artifact/pkg/controller/vmip/internal/protection_handler.go, images/virtualization-artifact/pkg/controller/vmip/internal/state/state.go, images/virtualization-artifact/pkg/controller/vmip/vmip_controller.go, images/virtualization-artifact/pkg/controller/vmip/vmip_reconciler.go
This PR introduces several critical fixes and enhancements to the VirtualMachine controller and VirtualMachineIPAddress management, including:
- Fix IP address updates for running VirtualMachines.
- Add 'Attached' phase for VirtualMachineIPAddress.
- Enable automatic IP assignment when switching a VirtualMachine from a specified IP to none.
- Allow multiple VirtualMachines to share the same IP address, with the first one occupying it and others in 'Pending' - state until the IP is available.
- Improve condition values in the VirtualMachine controller for more accurate state management.
- Add indexing for VirtualMachineIPAddress resources to improve discovery efficiency.
- Remove VirtualMachine name labels from VirtualMachineIPAddress resources.
=> fix(vm,vmip): improve VMIP management

images/virtualization-artifact/pkg/controller/vmop/vmop_controller.go, images/virtualization-artifact/pkg/monitoring/metrics/vmop/collector.go, images/virtualization-artifact/pkg/monitoring/metrics/vmop/data_metric.go, images/virtualization-artifact/pkg/monitoring/metrics/vmop/metrics.go, images/virtualization-artifact/pkg/monitoring/metrics/vmop/scraper.go, images/virtualization-artifact/pkg/monitoring/metrics/vmop/unsafe.go, monitoring/prometheus-rules/internal-virtualization-virt-hander.yaml, monitoring/prometheus-rules/vmop.yaml
Add metrics for VMOP
`d8_virtualization_virtualmachineoperation_status_phase`
With base labels` ["name", "namespace", "uid"]`
we need more metrics
=> feat(vmop): add metrics

images/virtualization-artifact/pkg/controller/vmip/internal/protection_handler.go
Fix the problem: protection finalizer of VirtualMachineIPAddress does not removed when VirtualMachine deleted.
=> fix(vmip): fix deleting unattached vmip

images/virtualization-artifact/pkg/controller/supplements/generator.go
The UID is now used for generating the name of ingress and service instead of the name of the original resource (vd, vi, cvi). 
According to DNS rules, the service name cannot be longer than 63 characters, whereas the name of the original resource can be longer.
A functional uploader when the name of vd/vi/cvi is of considerable length
=> fix(vd,vi,cvi): fix vd uploader service creating

images/virt-artifact/werf.inc.yaml
Fix go version in file WORKSPACE and root go.mod
Fix [PR 372](https://github.com/deckhouse/virtualization/pull/372)
Kubvirt binaries are builded on go 1.22.7
=> refactor(core): edit go version in kubevirt and workspace file

images/virtualization-artifact/pkg/controller/common/util.go, images/virtualization-artifact/pkg/controller/ipam/ipam.go, images/virtualization-artifact/pkg/controller/service/ip_address_service.go, images/virtualization-artifact/pkg/controller/vm/internal/state/state.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go
This PR introduces several fixes:
- Fix the issue with creating duplicate VirtualMachineIPAddresses when creating a VirtualMachine with an automatically assigned IP address.
- Fix the functionality of the 'need restart' option in the VirtualMachine status.
- Add IP address validation when manually creating a VirtualMachineIPAddress of type 'Static' (the first and last addresses in the CIDR can no longer be specified).
=> fix(vmip): add validating ip address for VMIP with type 'Static'

crds/clustervirtualimages.yaml, crds/virtualdisks.yaml, crds/virtualimages.yaml, crds/virtualmachines.yaml
Setting the maximum length for the names of the following resources: vm, vd, vi, cvi
We are resolving issues with the creation of sub-resources
=> chore(vm,vd,vi,cvi): set max name length to 128

images/virtualization-artifact/pkg/controller/vd/internal/validators/pvc_size_validator.go
This PR includes a fix for the issue that prevents resizing in the Spec VirtualDisk when the VirtualDisk is in  "Pending" or "Provisioning" phases.
=> fix(vd): allow to change size in spec for not ready vd

docs/USER_GUIDE_RU.md
Add documentation with examples for vm snapshot and vm restore resources
=> docs(module): add docs for vm snapshot and restore

images/virtualization-artifact/pkg/controller/service/size_policy_service.go, images/virtualization-artifact/pkg/controller/service/size_policy_service_test.go
Fix Virtual Machine validation of matching Virtual Machine Class requirements when no Sizing Policy not provided.
Virtual Machines was failing validation when no sizing policy provided. That's incorrect behavior.
Correct validation process)
=> fix(vm): fix the virtual machine matching with the virtual machine class during validation when no sizing policy is provided

base-images/alt_image_versions.yml, images/README.md, images/dvcr-artifact/pkg/datasource/datasource.go, images/libguestfs/werf.inc.yaml, images/virt-api/werf.inc.yaml, images/virt-artifact/werf.inc.yaml, images/virt-controller/werf.inc.yaml, images/virt-exportproxy/werf.inc.yaml, images/virt-exportserver/werf.inc.yaml, images/virt-handler/werf.inc.yaml, images/virt-launcher/werf.inc.yaml, images/virt-operator/werf.inc.yaml, werf.yaml
Switch to building kubevirt components on go and werf instead of building in bazel and werf
We need to simplify the build, make it more predictable and possible in closed environments
All pods with prefix `virt-` in `d8-virtualization` will be restarted
All VM `'firmware'` will be updated by vm migration
=> refactor(ci): get rid of bazel build

templates/kubevirt/kubevirt.yaml
Disable creating of `guest-console-log` container for a virtual machine pod.
=> feat(vm): disable serial console log

images/virt-artifact/patches/022-cleanup-error-pods.patch, images/virt-artifact/patches/README.md
add cleanup-error-pods.patch
After unsuccessful migrations, so many pods will remain in the failure phase. Clear them by saving the last 3.
=> chore(core): add cleanup-error-pods.patch

images/kube-api-proxy/pkg/rewriter/core_test.go, images/kube-api-proxy/pkg/rewriter/prefixed_name_rewriter.go
Use TrimPrefix for remove prefixes.
virt-handler generates node patches to set labels with kvm capabilities. To run it with original kubevirt, preserving original label names with the prefix was introduced. This patch fix restoring names in the patch rewriter.
There should no errors 422 Uprocessable entity in logs.
=> refactor(kube-api-rewriter): remove prefix from preserved original names in metadata

images/virt-api/werf.inc.yaml, images/virt-artifact/werf.inc.yaml, images/virt-handler/werf.inc.yaml, images/virt-operator/werf.inc.yaml
Fix virt-operator and virt-api: `warning: could not resolve current working directory: stat .: permission denied`
Add `sysctl` to virt-handler image
=> refactor(ci): change image to base-alt-p11 for virt-api virt-operator, add sysctl to virt-handler

images/kube-api-proxy/go.mod, images/kube-api-proxy/go.sum
Update google.golang.org/protobuf v1.31.0 to 1.33.0
Fix MEDIUM CVE-2024-24786
golang-protobuf: encoding/protojson, internal/encoding/json: infinite loop in protojson.Unmarshal when unmarshaling certain forms of...
https://avd.aquasec.com/nvd/cve-2024-24786
=> refactor(kube-api-rewriter): fix CVE-2024-24786

docs/ADMIN_GUIDE.md, docs/ADMIN_GUIDE_RU.md, docs/USER_GUIDE.md, docs/USER_GUIDE_RU.md, images/virtualization-artifact/pkg/common/common.go, images/virtualization-artifact/pkg/controller/service/uploader_service.go, images/virtualization-artifact/pkg/controller/uploader/uploader_ingress.go, images/virtualization-artifact/pkg/controller/uploader/uploader_service.go
Use default http port for uploader service
=> fix(cvi,vi,vd): use default http port for uploader service

tests/e2e/complex_test.go, tests/e2e/go.mod, tests/e2e/go.sum, tests/e2e/kubectl/kubectl.go, tests/e2e/sizing_policy_test.go, tests/e2e/testdata/complex-test/kustomization.yaml, tests/e2e/testdata/complex-test/vd/kustomization.yaml, tests/e2e/testdata/complex-test/vm/overlays/vm-a-not-b/kustomization.yaml, tests/e2e/testdata/complex-test/vm/overlays/vm-a-not-b/vm.vmclass.patch.yaml, tests/e2e/testdata/complex-test/vm/overlays/vm-b-not-a/kustomization.yaml, tests/e2e/testdata/complex-test/vm/overlays/vm-b-not-a/vm.vmclass.patch.yaml, tests/e2e/testdata/complex-test/vm/overlays/vm-c-and-a/kustomization.yaml, tests/e2e/testdata/complex-test/vm/overlays/vm-c-and-a/vm.vmclass.patch.yaml, tests/e2e/testdata/complex-test/vmc.yaml, tests/e2e/testdata/connectivity/kustomization.yaml, tests/e2e/testdata/connectivity/resources/kustomization.yaml, tests/e2e/testdata/connectivity/resources/vm-connectivity-a-svc.yaml, tests/e2e/testdata/connectivity/resources/vm-connectivity-a.yaml, tests/e2e/testdata/connectivity/resources/vm-connectivity-b-svc.yaml, tests/e2e/testdata/connectivity/resources/vm-connectivity-b.yaml, tests/e2e/testdata/vm-disk-attachment/overlays/automatic-with-hotplug/kustomization.yaml, tests/e2e/testdata/vm-disk-attachment/overlays/automatic-with-hotplug/vd-attach.yaml, tests/e2e/util_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_connectivity_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_migration_test.go
- make ginkgo contexts more readable;
- make test cases independent;
- adopt tests to updated API;
- adopt tests for different storage class volume binding modes.
API was changed and require to adopt tests for running them in development clusters because of E2E cluster has different configuration.
E2E tests can be running in development clusters and result should be succeeded.
=> test(api): refactor e2e tests

templates/kubevirt/service-monitor.yaml, templates/pre-delete-hook/job.yaml, templates/virtualization-controller/service-metrics.yaml
Remove field dublicates in resources.
kubeconform report before:
```
ERROR     Job virtualization-pre-delete-hook
error unmarshalling resource: error converting YAML to JSON: yaml: unmarshal errors:
line 21: key "labels" already set in map
ERROR     ServiceMonitor virtualization-virt-handler
error unmarshalling resource: error converting YAML to JSON: yaml: unmarshal errors:
line 235: key "namespaceSelector" already set in map
line 238: key "selector" already set in map
line 19: key "spec" already set in map
INVALID   Service virtualization-controller-metrics
- /spec/ports/0:
additionalProperties 'clusterIP', 'type' not allowed
------- Summary -------
valid: 97
skipped: 0
no schema: 0
errors: 2
invalid: 1
```
kubeconform report after:
```
...
VALID     Job virtualization-pre-delete-hook …
```
=> chore(module): helm templates cleanup

images/virtualization-artifact/pkg/common/patch/patch.go, images/virtualization-artifact/pkg/controller/service/resource.go
- Make Update method detect changes in annotations and labels.
- Change metadata with JSON patch using test+replace technique.
Reconciler should be able to change more metadata field in the changed object.
Also, fix label update for the vmop reconciler.
=> fix(vmop): patch /metadata/labels for reconciled object

.github/workflows/dev_module_build-on-self-hosted-runner.yml, .github/workflows/dev_module_build.yml, .github/workflows/dev_validation.yaml
Switch from Merge commit to HEAD SHA to prevent rebuilding images that have not been modified in the current branch
Improve CI/CD
=> refactor(ci): switch from merge commit to head sha commit in builds

crds/embedded/cdi.yaml, crds/embedded/virtualmachineinstances.yaml
- Add comments to prevent accidental adding status subresource in InternalVirtualizationCDI and InternalVirtualizationVirtualMachineInstance.
Some resources for KubeVirt and CDI store status field as "main" fields, not as a subresource. Set status to subresource will break update operation for these resources.
=> chore(core): add comments to prevent accidental adding status subresource

images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle.go
- VM name may exceed 63 characters limit on the label value
- UID is more robust for the purpose to get all related VMOPs.
- UID is already set for VMIP resources.
We need a way to fetch all VMOPs related to a particular VM (think of UI).
=> refactor(vmop): change vm label from name to uid

images/virtualization-artifact/pkg/controller/vd/internal/validators/spec_changes_validator.go
Allow change Virtual Disk spec after connect to Virtual Machine while Virtual Disk is not ready
=> feat(vd): Allow change Virtual Disk spec after connect to Virtual Machine while Virtual Disk is not ready

images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/vd/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vd/internal/mock.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_cvi.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vdsnapshot.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vi_dvcr.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vi_pvc.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go
1. Refactored the virtual disk controller. SourceHandlers now return reconcile.Result. 
2. If a "quota exceeded" error appears, we make additional attempts with a one-minute interval. If after 30 minutes it still doesn't succeed, the phase is set to Failed.
=> feat(vd): requeue for exceeded quota error

Taskfile.yaml
- add doc-ru linter to check the differences between crd and the RU version of crd
- add task `lint` to run all linters
We need to make sure that all changes are reflected in all language versions of crd
A tool that allows you to display the difference in crd
=> chore(lint): add doc-ru linter

images/virtualization-artifact/pkg/controller/vmclass/internal/discovery.go, images/virtualization-artifact/pkg/controller/vmclass/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vmclass/internal/util.go
freeze features after first discovery
=> feat(vmclass): freeze features after first discovery

images/kube-api-proxy/Taskfile.dist.yaml, images/kube-api-proxy/local/Dockerfile, images/kube-api-proxy/local/proxy.yaml, images/kube-api-proxy/pkg/rewriter/admission_configuration.go, images/kube-api-proxy/pkg/rewriter/admission_policy.go, images/kube-api-proxy/pkg/rewriter/discovery.go, images/kube-api-proxy/pkg/rewriter/rbac.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter.go, images/kube-api-proxy/pkg/rewriter/rule_rewriter_test.go, images/kube-api-proxy/pkg/rewriter/target_request.go
- Fix array construction for discovery rewrite in v1.30.
- Add rewriting for ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding.
Make kube-api-rewriter compatible with Kubernetes 1.29+
Module works in Kubernetes 1.29+
=> fix(kube-api-rewriter): fix discovery and ValidatingAdmissionPolicy rewrite

api/core/v1alpha2/events.go, api/core/v1alpha2/vmcondition/condition.go, images/dvcr-artifact/pkg/retry/retry.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go
1. Refactored SyncKvvmHandler.
2. Added a warning that restarting the virtual machine can be dangerous, as not all dependencies may be ready yet.
3. Fixed the bug with outdated changes in .status.restartAwaitingChanges.
4. Improved error messages for the user.
5. Removed the use of the deprecated conditions.Manager.
6. Retry in importer pod now lasts not for 3 seconds, but for [about 1 minute](https://github.com/deckhouse/virtualization/pull/477/files#diff-7cbd42bcec757d74b1b2159d6a27f8504fbc982f21b77d580adc1ac56ec99b94L39).
=> feat(vm): notify user if the virtual machine cannot be restarted immediately

images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go
Do not show DVCR URL in PVC stored VirtualImage in status.
We don't need to see intermediate DVCR URL in PVC stored VirtualImage.
Correct status of VirtualImage.
=> fix(vi): hide dvcr url in pvc stored vi

Taskfile.yaml
Fix output for doc-ru linter
We need to know the name of file with changes
```
/src/crds/clustervirtualimages.yaml # <---
{"count":1,"operations":[{"path":"/spec/versions/v1alpha2/schema/openAPIV3Schema/properties/spec/properties/dataSource/properties/http/properties/insecureSkipVerify","op":"delete"}]}
/src/crds/virtualdisks.yaml # <---
{"count":0,"operations":[]}
```
=> chore(module): fix doc-ru linter output

.github/workflows/dev_validation.yaml
Add "dorny/paths-filter" action to detect changes in helm templates related files.
No need to run helm templates validation for any change in the repo.
helm templates validation is skipped for changes in Go sourcres.
=> refactor(ci): run helm-templates validation on related changes only

.github/workflows/e2e_main.yaml, tests/e2e/README.md, tests/e2e/Taskfile.yaml, tests/e2e/complex_test.go, tests/e2e/disks_test.go, tests/e2e/ginkgoutil/decorators.go, tests/e2e/ipam_test.go, tests/e2e/sizing_policy_test.go, tests/e2e/tests_suite_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_connectivity_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_label_annotation_test.go, tests/e2e/vm_migration_test.go, tests/e2e/vm_test.go
- STOP_ON_FAILURE=yes env to stop test on first failure
- Taskfile changes:
- Rename run to run:ci, run_local to run.
- Remove dedicated task run_one.
- Get Ginkgo version from go.mod, remove hardcoded envs from workflow and Taskfile.
- Change "ginkgo" task from install to check behaviour: warn about ginkgo absence and version mismatch.
- Restructure e2e documentation:
- Restructure.
- Add documentation for FOCUS and STOP_ON_FAILURE env.
- Add cluster connection settings priority.
- Run tests without cleanup for debugging purposes.
- More consistent configuration.
- I can see resources in cluster in erroneous state if error occurs in test.
FOCUS env effect:
```
$ task run
ginkgo -v --skip-file vm_test.go --skip-file vm_label_annotation_test.go --skip-file ipam_test.go --skip-file …
```
=> refactor(e2e): support stopping on failure

images/virt-artifact/patches/023-replace-expressions-for-validating-admission-policy.patch, images/virt-artifact/patches/README.md
add replace expressions for validating admission policy patch
Replace the expressions for the ValidatingAdmissionPolicy kubevirt-node-restriction-policy.
This is necessary because of the kube-api-rewriter that changes the labels.
=> refactor(core): add replace expressions for validating admission policy patch

images/virtualization-artifact/pkg/controller/cvi/internal/deletion.go, images/virtualization-artifact/pkg/controller/vd/internal/deletion.go, images/virtualization-artifact/pkg/controller/vdsnapshot/internal/deletion.go, images/virtualization-artifact/pkg/controller/vi/internal/deletion.go, images/virtualization-artifact/pkg/controller/vm/internal/deletion_handler.go, images/virtualization-artifact/pkg/controller/vmbda/internal/deletion.go, images/virtualization-artifact/pkg/controller/vmclass/internal/deletion.go, images/virtualization-artifact/pkg/controller/vmip/internal/protection_handler.go, images/virtualization-artifact/pkg/controller/vmiplease/internal/protection_handler.go, images/virtualization-artifact/pkg/controller/vmop/internal/deletion.go
- Add log.Info before removing cleanup finalizer.
- Change confusing message "Delete %SOME_RESOURCE%" to "Deletion observed".
"Delete %SOME_RESOURCE%" message leads to a wrong assumption that controller deletes that %SOME_RESOURCE%.
=> refactor(api): unified deletion message when removing cleanup finalizer

templates/kubevirt/kubevirt.yaml
Remove FeatureGate VMExport from kubevirt config.
Remove patches related to exportproxy.
We scaled exportproxy to 0 replicas with patches to disabled unneeded component. Without VMExport feature virt-operator doesn't create Deployment at all.
=> feat(core, kubevirt): disable kubevirt exportproxy 

images/kube-api-rewriter/pkg/rewriter/core.go, images/kube-api-rewriter/pkg/rewriter/events.go, images/kube-api-rewriter/pkg/rewriter/events_test.go, images/kube-api-rewriter/pkg/rewriter/gvk.go, images/kube-api-rewriter/pkg/rewriter/rbac_test.go, images/kube-api-rewriter/pkg/rewriter/resource.go, images/kube-api-rewriter/pkg/rewriter/rule_rewriter.go, images/kube-api-rewriter/pkg/rewriter/target_request.go
- Add rewriter for Event resources
- Combine similar rewriters RewriteApiGroupAndKind and RewriteApiVersionAndKind into RewriteGVK with group version field argument.
- Fix rbac_test after renames in #475
- Stop confusing API consumers.
- Make `kubectl describe intvirtvmi/name` to display events.
Before:
```
$ kubectl -n ns describe intvirtvmi/vm-name
...
Events:             <none>
```
After:
```
$ kubectl -n ns describe intvirtvmi/vm-name
...
Type    Reason            Age   From                         Message
----    ------            ----  ----                         -------
Normal  SuccessfulCreate  25m   disruptionbudget-controller  Created PodDisruptionBudget kubevirt-internal-virtualization-disruption-budget-76t76
Normal  SuccessfulCreate  25m   virtualmachine-controller    Created …
```
=> refactor(kube-api-rewriter): add rewriter for Event resources

images/virtualization-artifact/pkg/controller/service/disk_service.go, tests/e2e/util_test.go
Align the method for getting the default StorageClass with how the default StorageClass is defined in k8s
Currently if there are multiple default StorageClasses, we take the random one, the behavior in k8s is different, the last annotated default StorageClass is taken
Take the last annotated default StorageClass
=> feat(vi-vd): get newest default StorageClass

images/virtualization-artifact/hack/dlv.sh
Running the task ```dlv:build-push`` doesn't work on macs with Apple processor
Running the ``dlv:build-push`` task on macs with Apple processor does not work due to running docker build with the default platform
Running the ``dlv:build-push`` task with specified linux/x86_64 platform
=> chore(dev): run dlv build task on m1 mac

crds/clustervirtualimages.yaml
Currently, when specifying ObjectRef in ClusterVirtualImage to namespace scoped VirtualDisk and VirtualImage resources lack validation for the presence of namespace, its minimum and maximum lengths
If namespace is absent, ObjectRef cannot be found and its presence and correctness must be validated in the manifest.
Adding validation of namespace presence, its minimum and maximum length, but only for ObjectRefs like VirtualImage and VirtualDisk.
=> feat(cvi): namespace validation for vi/vd ObjectRef

api/core/v1alpha2/virtual_machine_class.go, api/scripts/update-codegen.sh, crds/clustervirtualimages.yaml, crds/virtualmachineclasses.yaml
Change backup label from `backup.deckhouse.io/cluster-config=""` to `backup.deckhouse.io/cluster-config="true"` in virtualmachineclass, clustervirtualimage.
Usually, the logic of processing such resources is based on the `"true"` value, not empty string.
=> chore(crds): fix backup.deckhouse.io/cluster-config label

images/virtualization-artifact/pkg/controller/vmbda/internal/block_device_limiter.go
Fix `VirtualMachineBlockDeviceAttachement` block device attached count condition processing.
=> fix(vmbda): fix block device attached count condition processing

images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go
Use "optional" policy for "invtsc" cpu feature.
The problem with invtsc feature occurs when vmclass "Discovery" is used or feature is specified explicitly.
When "required" policy set for "invtcs" feature, kubevirt adds nodeSelector to schedule VM to the node with the lowest tsc frequency. This nodeSelector ignores other rules and not what user expects. This PR changes policy to "optional" to respect other rules in the nodeSelector.
Example of the label in the nodeSelector:
```
scheduling.node.virtualization.deckhouse.io/tsc-frequency-3407964000: "true"
```
=> fix(vm): create a kvvm with an optional cpu feature invtsc

api/core/v1alpha2/virtual_disk.go, api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go, api/scripts/update-codegen.sh, crds/virtualdisks.yaml
Generate VirtualDisk CRD by controller-gen
CRD automation
Minimal changes in virtualdisks.yaml
=> feat(vd): crd generation

images/virtualization-artifact/cmd/virtualization-controller/main.go, images/virtualization-artifact/pkg/controller/cvi/cvi_controller.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go, images/virtualization-artifact/pkg/controller/vdsnapshot/vdsnapshot_controller.go, images/virtualization-artifact/pkg/controller/vi/vi_controller.go, images/virtualization-artifact/pkg/controller/vm/vm_controller.go, images/virtualization-artifact/pkg/controller/vmbda/vmbda_controller.go, images/virtualization-artifact/pkg/controller/vmclass/vmclass_controller.go, images/virtualization-artifact/pkg/controller/vmip/vmip_controller.go, images/virtualization-artifact/pkg/controller/vmiplease/vmiplease_controller.go, images/virtualization-artifact/pkg/controller/vmop/vmop_controller.go, images/virtualization-artifact/pkg/controller/vmop/vmop_webhook.go, images/virtualization-artifact/pkg/controller/vmrestore/vmrestore_controller.go, images/virtualization-artifact/pkg/controller/vmsnapshot/vmsnapshot_controller.go, images/virtualization-artifact/pkg/logger/logger.go
Adding ability to enable debug log mode in specific controllers
Debug logs only for specific controllers
New ENV LOG_DEBUG_CONTROLLER_LIST with lists of controllers to be logged in DEBAG mode, multiple controllers must be separated by comma, names must be taken from ControllerName
=> chore(logger): different loggers for controllers

crds/embedded/cdi.yaml
Remove spec.names.categories for Cluster scoped CRD "InternalVirtualizationCDI".
- It is confusing that CDI config is listed when namespaced objects are requested (kubectl -n vmns get intvirt)
- Original CRD "CDI" has no categories.
=> refactor(cdi): Remove categories from cluster scoped CRD InternalVirtualizationCDI

tests/e2e/complex_test.go, tests/e2e/config/config.go, tests/e2e/disks_test.go, tests/e2e/ipam_test.go, tests/e2e/kubectl/kubectl.go, tests/e2e/sizing_policy_test.go, tests/e2e/tests_suite_test.go, tests/e2e/util_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_connectivity_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_label_annotation_test.go, tests/e2e/vm_migration_test.go, tests/e2e/vm_test.go
- exclude namespace in resource deletion step;
- refactor `apply` and `delete` kubectl commands;
- handle errors in clean up phase;
- add resource deletion step in each test case.
When test case is completed it's resources should be deleted.
To catch errors when virtualization resources cannot be deleted correctly.
All resources in E2E tests should be deleted correctly in each test case.
=> test(api): add resource deletion step in e2e test cases

images/virtualization-artifact/pkg/controller/vm/internal/block_device.go
Do not attach `VirtualDisk` if it already attached to another `VirtualMachine`.
=> fix(vm): do not attach VirtualDisk if it already attached to another VirtualMachine

api/core/v1alpha2/vmcondition/condition.go, images/virtualization-artifact/pkg/controller/vm/internal/agent.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/life_cycle.go
Wrap guest agent conditions reasons
Kubevirt delete VirtualMachineInstanceUnsupportedAgent if its supported, in this case we set incorrect reason and message
Correct guest agent conditions
=> fix(vm): unsupported guest agent reason wrap

tests/performance/virtualization-dashboard.yaml
Update dashboard Virtualization
Since the labels and metrics have been renamed and updated, we need to update them in the dashboard in grafana
Dashboard Virtualization shows correct data
=> chore(observability): update dashboard for perfomance tests

images/cdi-artifact/patches/017-add-format-conversion-for-pvc-cloning.patch, images/cdi-artifact/patches/README.md, images/virtualization-artifact/pkg/controller/vmiplease/internal/retention_handler.go
When cloning via DataVolume from PVC to PVC, there was no format conversion. 
The target PVC should have a raw type for Block and a qcow2 type for Filesystem. 
The patch adds this conversion.
=> fix(vd): patch cdi to convert image format

api/core/v1alpha2/virtual_image.go, api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go, crds/virtualimages.yaml
update CEL for vi
Fix creating vi with pvc, dataSource for vi wtih pvc doen't required
```
Error: 1 error occurred:
* VirtualImage.virtualization.deckhouse.io "performance" is invalid: [spec.dataSource: Required value, <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]
```
=> fix(vi): update CEL

images/virtualization-artifact/pkg/controller/service/snapshot_service.go, images/virtualization-artifact/pkg/controller/vdsnapshot/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/life_cycle.go
Unfreeze vm fs after snapshot
Currently, with multiple disks and their snapshots, we do not unfreeze the fs
fs unfreeze after all snapshots done
=> fix(vm): unfreeze fs after snapshot

api/core/v1alpha2/vmcondition/condition.go, images/virtualization-artifact/pkg/controller/conditions/stringer.go, images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go
Wrap reason for VirtualMachineInstanceReady condition
Remove deprecated code
Same behavior, but with our types
=> refactor(vm): wrap KVMI ready reasons

templates/kube-rbac-proxy/_helpers.tpl
Explicitly set default fields in the customization patch for kube-rbac-proxy.
Prevent infinite patching of cdi-apiserver and cdi-deployment by the cdi-operator. cdi-operator don't respect default values from Kubernetes API.
=> fix(template): add missing fields to kube-rbac-proxy

api/core/v1alpha2/cvicondition/condition.go, api/core/v1alpha2/vdcondition/condition.go, api/core/v1alpha2/vicondition/condition.go, images/virtualization-artifact/pkg/controller/cvi/cvi_reconciler.go, images/virtualization-artifact/pkg/controller/cvi/internal/datasource_ready.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/errors.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/service/errors.go, images/virtualization-artifact/pkg/controller/vd/internal/inuse.go, images/virtualization-artifact/pkg/controller/vd/internal/inuse_test.go, images/virtualization-artifact/pkg/controller/vd/internal/validator/iso_source_validator.go, images/virtualization-artifact/pkg/controller/vd/internal/validator/pvc_size_validator.go, images/virtualization-artifact/pkg/controller/vd/internal/validator/spec_changes_validator.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go, images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go, images/virtualization-artifact/pkg/controller/vd/vd_webhook.go, images/virtualization-artifact/pkg/controller/vi/internal/datasource_ready.go, images/virtualization-artifact/pkg/controller/vi/internal/source/errors.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vi/vi_reconciler.go, images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vm/internal/block_devices_test.go, images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go, images/virtualization-artifact/pkg/controller/watchers/cvi_filter.go, images/virtualization-artifact/pkg/controller/watchers/object_ref_watcher.go, images/virtualization-artifact/pkg/controller/watchers/vd_enqueuer.go, images/virtualization-artifact/pkg/controller/watchers/vi_filter.go
- Add conditon 'InUse" for VirtualDisk. This condition indicate:
-  that the VirtualDisk may be used for create ClusterVirtualImage or VirtualImage
- that the VirtualDisk may be attached to running VirtualMachine
Fix problem with lock VirtualImage and ClusterVirtual image in phase 'Pending' after stopping or deleting VirtualMachine, when used needed VirtualDisk in them.
=> fix(cvi,vi): unlock pending vi/cvi from vd ref

images/cdi-artifact/patches/019-optimize-csi-clone.patch, images/cdi-artifact/patches/README.md
1. Cloning PVC to PVC for provisioner `rbd.csi.ceph.com` now works via `csi-clone` instead of `snapshot`.
2. With `csi-clone`, it's possible to specify the same or a larger capacity for the target PVC immediately, with no need to postpone resizing.
=> feat(cdi): configure clone strategy of storage profile

images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go
Fix method that checking KubeVirt Virtual Machine pod has start errors.
=> fix(vm): fix pod start error check

images/cdi-artifact/patches/021-fallback-to-host-clone-for-lvm-thick.patch, images/cdi-artifact/patches/README.md, templates/cdi/cdi-operator/rbac-for-us.yaml
When cloning from PVC to PVC, it's necessary to select a cloning strategy. By default, the cloning strategy `snapshot` is selected.
However, `replicated.csi.storage.deckhouse.io` and `local.csi.storage.deckhouse.io` can create snapshots only when using LVM Thin.
To avoid errors, for LVM Thick, it's necessary to use `copy` cloning strategy (`csi-clone` is also unavailable since the CSI itself creates a snapshot when using `csi-clone`).
=> fix(cdi): change clone strategy fot sds provisioners

.github/workflows/nightly_e2e_tests_main.yaml, tests/e2e/Taskfile.yaml
Send message to LOOP on nightly e2e test runs.
We need this to have a better view of nightly e2e tests' results.
Messages would be sent to LOOP every night on every e2e test.
=> feat(ci): send nightly e2e test to loop

images/virtualization-artifact/pkg/controller/service/snapshot_service.go, images/virtualization-artifact/pkg/controller/vdsnapshot/internal/deletion.go, images/virtualization-artifact/pkg/controller/vdsnapshot/internal/interfaces.go, images/virtualization-artifact/pkg/controller/vdsnapshot/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vdsnapshot/internal/life_cycle_test.go, images/virtualization-artifact/pkg/controller/vdsnapshot/internal/mock.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/interfaces.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/life_cycle_test.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/mock.go
- Fix unfreeze of virtual machines
- Fix VolumeSnapshot deletion
- Improve processing of concurrent snapshots
=> fix(vdsnapshot,vmsnapshot): unfreeze virtual machines

images/virt-artifact/patches/028-inject-placement-anynode.patch, images/virt-artifact/patches/README.md
By default, the virtual-operator adds a nodePlacement with the RequireControlPlanePreferNonWorker.
But we set up the placement ourselves, so we replace the policy with AnyNode.
=> fix(kubevirt, core): inject-placement-anynode

tests/e2e/Taskfile.yaml
Print ginkgo output for nightly e2e tests
Fix PR #593
=> fix(ci): print ginkgo output for nightly e2e tests to stderr

tests/e2e/Taskfile.yaml
Change grep for RESULT variable to get the test results correctly.
Fix #593 
Correct message in LOOP
=> fix(ci): fix grep in nightly e2e tests

api/core/v1alpha2/events.go, api/core/v1alpha2/virtual_machine_class.go, api/core/v1alpha2/vmcondition/condition.go, images/virtualization-artifact/pkg/common/annotations/annotations.go, images/virtualization-artifact/pkg/controller/conditions/builder.go, images/virtualization-artifact/pkg/controller/kvbuilder/last_applied_spec.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go, images/virtualization-artifact/pkg/controller/vm/internal/watcher/vmclass_watcher.go, images/virtualization-artifact/pkg/controller/vmchange/compare.go, images/virtualization-artifact/pkg/controller/vmchange/compare_test.go, images/virtualization-artifact/pkg/controller/vmchange/vmclass_change.go
- add annotation to save vmclass spec that was used to generate current kvvm.
We need to detect changes in vmclass to set status that VM needs a restart to apply destructive changes from the vmclass spec.
=> feat(vm): add specchanges for vmclass

tests/e2e/Taskfile.yaml
Add EXIT_CODE env for GitHub Actions to use as indicator of run's success
Fix #593
=> fix(ci): fix false positive e2e CI runs

api/core/v1alpha2/events.go, images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vmop/internal/operation.go, images/virtualization-artifact/pkg/controller/vmop/vmop_controller.go
Adding VMOP events
Adding events is aimed at improving problem finding and tracking the causes of state changes
New events on VMOP resources
=> refactor(vmop): events

api/core/v1alpha2/events.go, images/virtualization-artifact/pkg/controller/vi/internal/source/http.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/vi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vi/internal/storageclass_ready.go, images/virtualization-artifact/pkg/controller/vi/internal/storageclass_ready_test.go, images/virtualization-artifact/pkg/controller/vi/vi_controller.go
Adding VirtualImage events
Adding events is aimed at improving problem finding and tracking the causes of state changes
New events on VirtualImage resources
=> refactor(vi): add events

api/core/v1alpha2/events.go, images/virtualization-artifact/pkg/controller/vd/internal/attachee.go, images/virtualization-artifact/pkg/controller/vd/internal/datasource_ready.go, images/virtualization-artifact/pkg/controller/vd/internal/datasource_ready_test.go, images/virtualization-artifact/pkg/controller/vd/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vd/internal/life_cycle_test.go, images/virtualization-artifact/pkg/controller/vd/internal/resizing.go, images/virtualization-artifact/pkg/controller/vd/internal/resizing_test.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_cvi.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vdsnapshot.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vi_dvcr.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vi_pvc.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vd/internal/storageclass_ready.go, images/virtualization-artifact/pkg/controller/vd/internal/storageclass_ready_test.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go
Adding VirtualDisk events
Adding events is aimed at improving problem finding and tracking the causes of state changes
New events on VirtualDisk resources
=> refactor(vd): events

images/virtualization-artifact/pkg/controller/cvi/cvi_controller.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/http.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/upload.go
Adding ClusterVirtualImage events
Adding events is aimed at improving problem finding and tracking the causes of state changes
New events on ClusterVirtualImage resources
=> refactor(cvi): add events

.github/workflows/nightly_e2e_tests_main.yaml, tests/e2e/Taskfile.yaml
Unconditionally send to Loop results of e2e tests, even if they are failed or not ran at all.
Fixes #593
=> chore(ci): add unconditional send to loop

images/kube-api-rewriter/pkg/proxy/handler.go
wrap api error with NewInternalError
Passthrough api error
=> fix(kube-api-rewriter): respond with correct error

templates/kubevirt/service-monitor.yaml
fix internal metrics for kv v1.3.1
=> refactor(module): fix internal metrics for kv v1.3.1

werf.yaml
Fix register module issue
We need to fix an issue:
```
register hooks search and register hooks: module hook --config invalid: get shell hook config: exit status 1
```
=> fix(module) fix register module issue

images/virt-artifact/patches/029-use-OFVM_CODE-for-linux.patch, images/virt-artifact/patches/README.md, images/virtualization-artifact/pkg/common/annotations/annotations.go, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go
Add `029-use-OFVM_CODE-for-linux.patch` to allow non-Windows configurations with more than 12 CPUs.
Kubevirt uses OVFM_CODE.secboot.fd in 2 combinations: OVFM_CODE.secboot.fd + OVFM_VARS.secboot.fd when secboot is enabled and OVFM_CODE.secboot.fd + OVFM_VARS.fd when secboot is disabled.
It works fine with original CentOS based virt-launcher in both secboot modes.
We use ALTLinux based virt-launcher and it fails to start Linux VM with more than 12 CPUs in secboot disabled mode.
Kubevirt uses flags to detect firmware combinations in converter.EFIConfiguration, so we can't set needed files directly. But there is combination for SEV: OVFM_CODE.cc.fd + OVMF_VARS.fd that works for Linux, because OVFM_CODE.cc.fd is actually a symlink to OVFM_CODE.fd. So, we set true for the second flag to force …
=> fix(core, kubevirt): virt-launcher with efi and cpu >= 12 not starting

tests/e2e/kubectl/kubectl.go
When tests run on Github runner some requests are failed because of timeout on the `apply` operation.
=> test(api): increase `kubectl apply` timeout

images/virt-artifact/patches/030-hide-target-pod-during-migration-via-cilium-label.patch, images/virt-artifact/patches/README.md
During the VM migration process, two pods with the same address are created and packets are randomly delivered to them. 
To force delivery of packages to only one VM pod, the special label `network.deckhouse.io/hidden-pod` for target pod were added.
When the migration completes, the label is removed and the target pod becomes accessible via network.
=> fix(core): hide target pod during migration via cilium label

api/core/v1alpha2/vdcondition/condition.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/errors.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vd/internal/inuse.go, images/virtualization-artifact/pkg/controller/vd/internal/inuse_test.go, images/virtualization-artifact/pkg/controller/vi/internal/source/errors.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vm/internal/block_devices_test.go
This PR addresses two issues related to the update generation in conditions for the VirtualDisk module. It fixes the update generation process and changes the status of in-use conditions from "Unknown" to "False".
By fixing the update generation and clarifying the status of in-use conditions, this PR ensures that the system behaves predictably and accurately reflects the actual state of conditions.
After these changes, condition statuses will be updated correctly, and in-use conditions will no longer show as "Unknown".
=> fix(vd): fix condition status updates in VirtualDisk

hooks/module_config_validator.py, images/virtualization-artifact/cmd/virtualization-controller/main.go, images/virtualization-artifact/pkg/controller/moduleconfig/api/deep_copy.go, images/virtualization-artifact/pkg/controller/moduleconfig/api/moduleconfig.go, images/virtualization-artifact/pkg/controller/moduleconfig/api/register.go, images/virtualization-artifact/pkg/controller/moduleconfig/cidrs_validator.go, images/virtualization-artifact/pkg/controller/moduleconfig/moduleconfig_webhook.go, images/virtualization-artifact/pkg/controller/moduleconfig/remove_cidrs_validator.go, images/virtualization-artifact/pkg/controller/moduleconfig/util.go, images/virtualization-artifact/pkg/controller/validator/validator.go, templates/virtualization-controller/validation-webhook.yaml
Add a webhook for ModuleConfig Virtualization
It is forbidden to delete used CIDRs
=> feat: add webhook for validating module config virtualization

hooks/module_config_validator.py
=> fix(hooks): fix module-config hook

api/core/v1alpha2/virtual_disk.go, crds/virtualdisks.yaml
Add InUse condition to brief output
Make vd info more useful
`kubectl get vd -o wide`
=> feat(vd) add InUse condition to brief output

images/cdi-artifact/patches/020-manage-provisioner-tolerations.patch
For the tmp pvc, the owner reference was missing, which could be used to find the target pvc. 
However, the AdjustWorkloadNodePlacement fn relies on this.
Added the owner reference for tmp pvc.
=> fix(vd): add owner ref for tmp pvc created in cdi

crds/embedded/virtualmachineinstances.yaml, crds/embedded/virtualmachines.yaml, images/virt-artifact/patches/032-hotplug-container-disk.patch, images/virt-artifact/patches/README.md
Add patch for hotplug container-disk
The `container-disk` is a program written in C used within KubeVirt to facilitate the mounting of container-based disk images into virtual machines. Its core function is to start up and create a UNIX socket within a specific directory. The program terminates when the socket is removed or upon receiving a `SIGTERM` signal.
- A sidecar container, running the `container-disk` image, is created alongside the `virt-launcher` pod.
- An init-container in the `virt-launcher` pod copies the `container-disk` program to a shared `emptyDir` volume. This setup allows the sidecar to execute the program.
- The `container-disk` program creates a socket in the `emptyDir` volume.
- This shared volume allows the `virt-handler` to locate the socket on the host machine at: …
=> feat(core, kubevirt): add patch for hotplug container-disk

images/virtualization-artifact/pkg/controller/service/disk_service.go
The check was lost on nil.
The function thinks that there is already an importer under the cdi, but it is not there yet.
=> fix(vd): handle nil importer pod

api/core/v1alpha2/events.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/life_cycle_test.go, images/virtualization-artifact/pkg/controller/vmsnapshot/vmsnapshot_controller.go, images/virtualization-artifact/pkg/controller/vmsnapshot/vmsnapshot_reconciler.go
Add events when `VirtualMachineSnapshot`:
- waits for dependent resources;
- is started;
- is failed;
- is completed.
It improves user experience in the snapshotting process of `VirtualMachine`.
=> feat(vmsnapshot): add new events

images/virtualization-artifact/pkg/controller/uploader/uploader_ingress.go
Add annotations to disable buffering for ingress used in image uploads
=> fix(vi, cvi):  Add annotations to disable buffering for ingress used in image uploads

tests/e2e/complex_test.go, tests/e2e/kubectl/resource.go, tests/e2e/util_test.go, tests/e2e/vm_migration_test.go
Replace intvirtvmim with vmop.
We should not use internal virtualization resources in the E2E tests and now there is the `ValidatingAdmissionPolicy` virtualization-restricted-access-policy on it.
=> test(api): replace intvirtvmim with vmop

images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go
do not detect vmclass specification changes if vmclass is not found
=> fix(vm):  do not detect vmclass specification changes if vmclass is not found

templates/admission-policy.yaml
allow crud over internal resources for sa in kube-system and d8 system namespaces
=> fix(vm): allow crud over internal resources for sa in kube-system and d8 system namespaces

tests/e2e/Taskfile.yaml
Fix e2e message and status in pipeline on non-zero exit codes.
Fix #593
=> test(ci): fix e2e false positive on failure of resource deletion

tests/e2e/README.md, tests/e2e/affinity_toleration_test.go, tests/e2e/complex_test.go, tests/e2e/config/cleanup.go, tests/e2e/config/config.go, tests/e2e/config/reusable.go, tests/e2e/sizing_policy_test.go, tests/e2e/tests_suite_test.go, tests/e2e/util_test.go, tests/e2e/vd_snapshots_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_connectivity_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_label_annotation_test.go, tests/e2e/vm_migration_test.go
The environment variable REUSABLE used to reuse resources created previously.
By default, it retains all resources created during the e2e test after its completion (no cleanup by default in this mode).
Use the `WITH_POST_CLEANUP=yes` environment variable to clean up resources created or used during the test.
When a test starts, it will reuse existing virtual machines created earlier, if they exist.
If no virtual machines were found, they will be created.
For example, run test in reusable mode:
```bash
REUSABLE=yes task run
```
! Only the following e2e tests are supported in REUSABLE mode. All other tests will be skipped.
- "Virtual machine configuration"
- "Virtual machine migration"
- "VM connectivity"
- "Complex test"
WithPostCleanUpEnv defines an environment variable used to explicitly …
=> test(vm): add reusable mode to use previously created virtual machines for e2e tests

images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_utils.go, tests/e2e/Taskfile.yaml
This pull request introduces the SetMetadata method to the KVVM Builder. Previously, we did not set metadata in the KVVM template during creation, as it was synchronized later using a dedicated handler. While this approach worked for syncing metadata, it caused an issue with the initial pod scheduling.
Without setting metadata upfront, some required labels were missing during the initial pod scheduling phase. These labels are critical for features like pod affinity and anti-affinity rules. As a result, the initial scheduling could make incorrect decisions, potentially leading to rule violations or suboptimal placement.
By introducing the SetMetadata method, this PR ensures that metadata is properly set in the template during the initial build phase, preventing such scheduling issues.
=> fix(vm): Improve KVVM Builder. Add method SetMetadata

images/virtualization-artifact/pkg/controller/cvi/cvi_webhook.go, images/virtualization-artifact/pkg/controller/k8s-validation/validate-k8s-utils.go, images/virtualization-artifact/pkg/controller/vd/internal/validator/name_validator.go, images/virtualization-artifact/pkg/controller/vd/vd_webhook.go, images/virtualization-artifact/pkg/controller/vi/vi_webhook.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/affinity_validator.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/affinity_validator_test.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/topology_spread_validator.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/validators_test.go, images/virtualization-artifact/pkg/controller/vm/vm_webhook.go
Add VirtualMachine specification validation by affinity and topologySpreadConstraints.
Add block devices name validation (must no contains dots).
=> feat(api): add specification validation for correct VMI creation

images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go
VI on DVCR from VD datasource not creating, cycle provisioning. VI on PVC from VD provisioning not starting.
VI from VD datasource creating
=> fix(vi): create from vd

images/virtualization-artifact/pkg/apiserver/registry/vm/rest/console.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/freeze.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/migrate.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/portforward.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/stream.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/unfreeze.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/vnc.go
Allow vmbda to be deleted when VirtualMachine is not running
=> fix(vmbda): allow vmbda to be deleted when VirtualMachine is not running

tests/e2e/Taskfile.yaml
Add color output to nightly e2e tests and fix exit code problem. As of now, PIPESTATUS can't capture exit codes from command substitution `$()`, and this PR addresses that.
Color output improves readability.
The exit code part fixes #667.
Color output in nightly e2e tests.
Proper failure on non-zero exit codes from ginkgo.
=> fix(ci): add color output to nightly e2e tests & fix exit code

tests/e2e/affinity_toleration_test.go, tests/e2e/util_test.go, tests/e2e/vm_disk_resizing_test.go
There is a situation where tests fail when deleting a namespace and namespaced resources with one kustomization command.
=> test(api): fix e2e cleanup operations

api/core/v1alpha2/cluster_virtual_image.go, api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go, crds/clustervirtualimages.yaml, crds/doc-ru-clustervirtualimages.yaml, images/virtualization-artifact/pkg/controller/cvi/cvi_controller.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/errors.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vdsnapshot.go
Add the ability to create a ClusterVirtualImage from a VirtualDiskSnapshot.
User should be able to create a new CVI from VDSnapshot.
New ObjectRef type
=> feat(cvi): snapshot objectRef

api/core/v1alpha2/cluster_virtual_image.go, api/core/v1alpha2/virtual_image.go, api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go, base-images/deckhouse_image_versions.yml, crds/clustervirtualimages.yaml, crds/doc-ru-virtualimages.yaml, crds/virtualimages.yaml, docs/USER_GUIDE.md, docs/USER_GUIDE_RU.md, images/bounder/werf.inc.yaml, images/virtualization-artifact/cmd/virtualization-controller/main.go, images/virtualization-artifact/pkg/common/consts.go, images/virtualization-artifact/pkg/config/load_import_settings.go, images/virtualization-artifact/pkg/controller/bounder/bounder.go, images/virtualization-artifact/pkg/controller/bounder/bounder_test.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vdsnapshot.go, images/virtualization-artifact/pkg/controller/service/bounder_service.go, images/virtualization-artifact/pkg/controller/supplements/generator.go, images/virtualization-artifact/pkg/controller/vi/internal/source/errors.go, images/virtualization-artifact/pkg/controller/vi/internal/source/interfaces.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/vi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vi/vi_controller.go, templates/virtualization-controller/_helpers.tpl
```changes
section: vi
type: feature
summary: add the ability to create a VirtualImage from a VirtualDiskSnapshot.
```
Add the ability to create a VirtualImage from a VirtualDiskSnapshot.
User should be able to create a new VI from VDSnapshot.
New ObjectRef type
=> feat(vi): add snapshot objectRef

tests/e2e/config/config.go, tests/e2e/d8/d8.go, tests/e2e/default_config.yaml, tests/e2e/images_creation_test.go, tests/e2e/testdata/images-creation/cvi/cvi_containerimage.yaml, tests/e2e/testdata/images-creation/cvi/cvi_http.yaml, tests/e2e/testdata/images-creation/cvi/cvi_objectref_cvi.yaml, tests/e2e/testdata/images-creation/cvi/cvi_objectref_vd.yaml, tests/e2e/testdata/images-creation/cvi/cvi_objectref_vdsnapshot.yaml, tests/e2e/testdata/images-creation/cvi/cvi_objectref_vi.yaml, tests/e2e/testdata/images-creation/cvi/kustomization.yaml, tests/e2e/testdata/images-creation/kustomization.yaml, tests/e2e/testdata/images-creation/ns.yaml, tests/e2e/testdata/images-creation/transformer.yaml, tests/e2e/testdata/images-creation/vd/kustomization.yaml, tests/e2e/testdata/images-creation/vd/vd-alpine-http.yaml, tests/e2e/testdata/images-creation/vdsnapshot/kustomization.yaml, tests/e2e/testdata/images-creation/vdsnapshot/vdsnapshot.yaml, tests/e2e/testdata/images-creation/vi/kustomization.yaml, tests/e2e/testdata/images-creation/vi/vi_containerimage.yaml, tests/e2e/testdata/images-creation/vi/vi_http.yaml, tests/e2e/testdata/images-creation/vi/vi_objectref_cvi.yaml, tests/e2e/testdata/images-creation/vi/vi_objectref_vd.yaml, tests/e2e/testdata/images-creation/vi/vi_objectref_vdsnapshot.yaml, tests/e2e/testdata/images-creation/vi/vi_objectref_vi.yaml, tests/e2e/testdata/images-creation/vi/vi_pvc_objectref_vi.yaml, tests/e2e/tests_suite_test.go, tests/e2e/vd_snapshots_test.go, tests/e2e/vm_configuration_test.go
Add images creation e2e tests.
Test to create VI and CVI's from various sources.
New e2e tests, with all available data sources.
=> test(images): images creation e2e

tests/e2e/tests_suite_test.go
Empty namespaces remain after E2E tests.
Namespaces will be deleted correctly after each E2E tests.
```changes
section: ci
type: fix
summary: cleanup namespaces after e2e tests
```
=> test(ci): fix e2e namespace cleanup operation

images/virt-artifact/patches/033-fix-virt-controller-tests.patch, images/virt-artifact/patches/README.md
Fix unit tests for virt-controller.
Use to run tests:
ginkgo -succinct /home/dmitrii/Base/Flant/kubevirt/pkg/virt-controller/...
Our patches introduce significant changes to the kubevirt codebase, so it is strictly necessary to keep kubevirt unit tests up to date to minimize the likelihood of bugs.
The tests are passed.
=> test(kubevirt): fix virt-controller tests

api/core/v1alpha2/events.go, images/virtualization-artifact/pkg/controller/vmip/internal/iplease_handler.go, images/virtualization-artifact/pkg/controller/vmip/internal/lifecycle_handler.go, images/virtualization-artifact/pkg/controller/vmip/vmip_controller.go
The `VirtualMachineIPAddress` controller has been updated to use the new event registration API.
Events for connecting and disconnecting `VirtualMachineIPAddress` to a `VirtualMachine` have been introduced.
Events related to `VirtualMachineIPLease` have been added.
```changes
section: vmip
type: feature
summary: add new events
```
=> feat(vmip): add new events

api/core/v1alpha2/events.go, api/core/v1alpha2/vmclasscondition/condition.go, images/virtualization-artifact/pkg/controller/vm/internal/watcher/vmclass_watcher.go, images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go, images/virtualization-artifact/pkg/controller/vmclass/internal/deletion.go, images/virtualization-artifact/pkg/controller/vmclass/internal/discovery.go, images/virtualization-artifact/pkg/controller/vmclass/internal/discovery_test.go, images/virtualization-artifact/pkg/controller/vmclass/internal/internal_test.go, images/virtualization-artifact/pkg/controller/vmclass/internal/validators/policy_changes_validator.go, images/virtualization-artifact/pkg/controller/vmclass/internal/watcher/vm_watcher.go, images/virtualization-artifact/pkg/controller/vmclass/vmclass_controller.go, images/virtualization-artifact/pkg/controller/vmclass/vmclass_reconciler.go, images/virtualization-artifact/pkg/controller/vmclass/vmclass_webhook.go, images/virtualization-artifact/pkg/logger/logger.go
Using new events api.
Add event when list of available nodes changed.
Add event when sizing policies changed.
```changes
section: vmclass
type: feature
summary: add events about available nodes and sizing policies changed
```
=> feat(vmclass): add events about available nodes and sizing policies changed

Taskfile.yaml, images/virt-api/debug/dlv.Dockerfile, images/virt-artifact/patches/034-allow-update-kvvmi-for-virtualization-sas.patch, images/virt-artifact/patches/035-allow-change-serial-on-kvvmi.patch, images/virt-artifact/patches/README.md, images/virt-artifact/werf.inc.yaml, images/virtualization-artifact/cmd/virtualization-controller/main.go, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/add_volume.go, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_utils.go, images/virtualization-artifact/pkg/logger/attrs.go, images/virtualization-artifact/pkg/migration/README.md, images/virtualization-artifact/pkg/migration/migration.go, images/virtualization-artifact/pkg/migration/qemu_max_length_36.go
Previously, we set the disk serial to match the disk name, relying on Kubernetes to ensure the uniqueness of names. However, after this [commit](https://github.com/qemu/qemu/commit/75997e182b695f2e3f0a2d649734952af5caf3ee) on QEMU, we can no longer do this, as QEMU no longer truncates the serial to 36 characters and now returns an error. We must handle the truncation ourselves. However, truncation does not guarantee uniqueness, so we switched to generating an MD5 hash of the disk name. The MD5 hash is easy to reproduce and fits the required 32-character length.
To ensure a successful migration, existing `kvvm` and `kvvmi` resources need to be patched to reflect the new serial format.
```changes
section: vm  
type: fix  
summary: Disk serials are now generated using the MD5 hash of the …
```
=> fix(kubevirt): migration disk serial

images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vdsnapshot.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot.go
Fix for VI/CVI with VDSnapshot ObjectRef, when provisioning becomes failed with immediate storage class. 
Correct CVI/VI operation
VI/CVI can be successfully created from images on immediate storage class
```changes
section: images
type: fix
summary: vi/cvi can be successfully created from images on immediate storage class
```
=> fix(images): vdsnapshot immediate disk provisioning

images/virt-artifact/patches/031-hotplug-container-disk.patch
This PR enhances the unmounting process for hotplugged container disks by introducing improvements that ensure a more reliable and thorough cleanup.
1. Added the removal of mount point files after unmounting to clean up leftover artifacts.
2. Updated the unmounting logic to rely not only on our managed mount records (stored in files) but also on the actual state of mount points.  
- The implementation now actively checks the real mount points on the system to verify their state and ensures they are properly unmounted.
These changes make the unmounting process more robust and help prevent stale mount points from causing issues.
```changes
type: fix
summary: Improve unmounting process by cleaning up mount point files and verifying actual mount states
```
=> fix(kubevirt): improve unmount for hotplug container disks

api/core/v1alpha2/vdcondition/condition.go, api/core/v1alpha2/vicondition/condition.go, images/virtualization-artifact/pkg/controller/vd/internal/source/blank.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_cvi.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vi_dvcr.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vi_pvc.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go, images/virtualization-artifact/pkg/controller/vi/internal/source/http.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/vi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vi/internal/source/sources.go, images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go, templates/admission-policy.yaml
Show error if can not connect to `DVCR`.
```changes
section: api
type: feature
summary: provide dvcr connection error from DataVolume
```
=> feat(api): provide ImagePullError from DataVolume to VirtualDisk and VirtualImage

api/client/kubeclient/vm.go, api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go, api/subresources/types.go, api/subresources/v1alpha2/types.go, api/subresources/v1alpha2/zz_generated.conversion.go, images/virt-artifact/patches/036-enhance-SCSI-disk-serial-validation.patch, images/virt-artifact/patches/README.md, images/virtualization-artifact/pkg/apiserver/registry/vm/rest/add_volume.go, images/virtualization-artifact/pkg/common/testutil/testutil.go, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_utils.go, images/virtualization-artifact/pkg/controller/service/attachment_service.go, images/virtualization-artifact/pkg/migration/README.md, images/virtualization-artifact/pkg/migration/disk_cache.go, images/virtualization-artifact/pkg/migration/qemu_max_length_36.go, images/virtualization-artifact/pkg/migration/qemu_max_length_36_test.go
Disk serials are now generated using the MD5 hash of the disk uid instead of the disk name itself. This prevents errors caused by recent QEMU changes enforcing a strict 36-character limit on serial numbers.
```changes
section: vm  
type: fix  
summary: Disk serials are now generated using the MD5 hash of the disk uid instead of the disk name itself. This prevents errors caused by recent QEMU changes enforcing a strict 36-character limit on serial numbers.
```
=> fix(vm): set disk serial by uid resource

images/virt-artifact/patches/031-hotplug-container-disk.patch, images/virt-artifact/werf.inc.yaml
Fix hotplug container disk mounter blocking the queue when virt-handler attempts to reconcile ghost records.
```changes
type: fix 
summary: Fix hotplug container disk mounter blocking the queue when virt-handler attempts to reconcile ghost records.
```
=> fix(kubevirt): unblock queue when exist ghost records

images/cdi-cloner/werf.inc.yaml, images/cdi-controller/werf.inc.yaml
Fix (PR #700) import path cdi images (cloner,controller)
```changes
section: ci
type: fix
summary: fix import path for cdi images (cloner,controller)
```
=> chore(ci): fix-distroless-cdi

images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vm/internal/block_devices_test.go, images/virtualization-artifact/pkg/controller/vm/internal/state/state.go
It adds hotplugged images to the VirtualMachine status.
VirtualMachine status will be contains all type of hotplugged VirtualImages. 
```changes
section: vm
type: feature
summary: VirtualMachine.Status.BlockDeviceRefs contains hotplugged images
```
=> feat(vm): add hotplug images to `VirtualMachine` status

images/virtualization-artifact/pkg/controller/vdsnapshot/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/life_cycle.go
Introduces a new error message that appears when a virtual machine is unable to freeze its filesystem because the agent is not ready to perform this operation.
```changes
section: vm
type: feat
summary: introduces a new error message that appears when a virtual machine is unable to freeze its filesystem because the agent is not ready to perform this operation.
```
=> feat(api): add message to snapshot condition about virtual machine cannot be frozen

images/virt-api/werf.inc.yaml, images/virt-artifact/werf.inc.yaml
Change virt-api base image to distroless.
We want our images to be distroless-based
```changes
section: ci
type: chore
summary: move to distroless virt-api
```
=> chore(ci): move to distroless virt-api

tests/e2e/affinity_toleration_test.go, tests/e2e/complex_test.go, tests/e2e/sizing_policy_test.go, tests/e2e/tests_suite_test.go, tests/e2e/util_test.go, tests/e2e/vd_snapshots_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_connectivity_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_label_annotation_test.go, tests/e2e/vm_migration_test.go
This pull request enhances the reliability of our end-to-end (E2E) tests by updating the verification process for virtual machine (VM) readiness. Instead of merely waiting for the VM to reach the "running" phase, the test now explicitly checks the VM's status and optionally confirms the successful launch of the QEMU agent. This change aims to reduce false positives and ensure that the VM is fully operational and ready for subsequent testing steps. Adjustments are reflected in the affected test scripts to incorporate these additional validation checks.
```changes
section: e2e
type: feat
summary:  verifying vm launching by qemu agent ready status
```
=> feat(e2e): verifying vm launching by qemu agent ready status

images/virtualization-artifact/pkg/controller/service/attachment_service.go
add serial for hotplug vi, cvi
```changes
section: vmbda
type: fix
summary: add serial for hotplug vi, cvi
```
=> fix(vmbda): add serial for vi, cvi

images/virtualization-artifact/pkg/common/blockdevice/block_device.go, images/virtualization-artifact/pkg/controller/cvi/cvi_webhook.go, images/virtualization-artifact/pkg/controller/vd/internal/validator/name_validator.go, images/virtualization-artifact/pkg/controller/vi/vi_webhook.go, tests/e2e/testdata/images-creation/cvi/cvi_objectref_cvi.yaml, tests/e2e/testdata/images-creation/cvi/cvi_objectref_vd.yaml, tests/e2e/testdata/images-creation/cvi/cvi_objectref_vdsnapshot.yaml, tests/e2e/testdata/images-creation/cvi/cvi_objectref_vi.yaml, tests/e2e/testdata/images-creation/vi/vi_objectref_cvi.yaml, tests/e2e/testdata/images-creation/vi/vi_objectref_vd.yaml, tests/e2e/testdata/images-creation/vi/vi_objectref_vdsnapshot.yaml, tests/e2e/testdata/images-creation/vi/vi_objectref_vi.yaml, tests/e2e/testdata/images-creation/vi/vi_pvc_objectref_vi.yaml
Add validation for short block device names.
Disk and volume name in kubevirt can be a valid container name (len 63) since disk name can become a container name which will fail to schedule if invalid.
We add prefix "vd-" for the vd name, so max len of vd is reduced to 60.
We and kubevirt add prefixes  "vi-", "volume" and suffix "-init", so max len for vi and is reduced to 49.
We and kubevirt add prefixes "cvi-", "volume" and suffix "-init", so max len for cvi and is reduced to 48.
```changes
section: api
type: fix
summary: reduce max len of block devices to avoid errors during vm creation
```
=> fix(api): add validation for short block device names

images/distroless/werf.inc.yaml
Fix path to CA certificates.
Add envs for locale and `PATH`
To run the binary without fuul path to file, we need to have a PATH environment variable in the image
Prevent warning like `warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8): No such file or directory`
```changes
section: ci
type: chore
summary: fix distroless image certificate path, add envs
```
=> chore(ci): fix distroless image certificate path, add envs

templates/kubevirt/virt-operator/rbac-for-us.yaml
Add validatingadmissionpolicies, validatingadmissionpolicybindings to rbac for virt-operator
```changes
section: core
type: fix
summary: Add validatingadmissionpolicies, validatingadmissionpolicybindings to rbac for virt-operator (required for kubernetes v1.30 )
```
=> fix(core): add policies to rbac

images/virt-handler/werf.inc.yaml
Change virt-handler image to distroless
We want our images to be distroless-based
```changes
section: core
type: chore
summary: virt-handler image to distroless
```
=> chore(core): virt-handler to distroless

images/virtualization-artifact/pkg/controller/vi/internal/watcher/vm_watcher.go, images/virtualization-artifact/pkg/controller/vi/vi_reconciler.go
Fix the possible hanging on the Terminating state for the virtual image that was attached to a virtual machine.
There was no watcher for virtual machines, so the virtual image could not synchronize its finalizers with the current state in the cluster.
Add watcher to fix it.
```changes
section: vi 
type: fix
summary: fix the possible hanging on the Terminating state for the virtual image that was attached to a virtual machine
```
=> fix(vi): add watcher for vm to reconcile protection finalizers

images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vmop/vmop_reconciler.go
Resolved an issue where the VMOP (Virtual Machine Operation) resource remained stuck in the 'InProgress' state. The problem was reproducible only for the 'Evict' and 'Migrate' operation types.
```changes
section: vmop
type: fix
summary: Resolve resource hang in 'InProgress' state for Evict/Migrate
```
=> fix(vmop): resolve resource hang in 'InProgress' state for Evict/Migrate

api/core/v1alpha2/events.go, images/virtualization-artifact/pkg/common/annotations/annotations.go, images/virtualization-artifact/pkg/common/kvvm/kvvm.go, images/virtualization-artifact/pkg/controller/service/vm_operation.go, images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go, images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go, images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vmop/internal/operation.go
This change introduces a "Pending" phase for virtual machines (VMs) that have an invalid specification and are in the restart process. Previously, if a VM was rebooted while having an invalid spec, it would start with the old spec.
This update is necessary to ensure that VMs do not continue to operate with outdated or invalid configurations after a restart.
With this change, when a VM with an invalid spec is restarted, it will enter a "Pending" phase, allowing for corrective actions before proceeding with the boot process. 
```changes
section: vm
type: fix
summary: move the vm to a pending phase instead of starting it if it has invalid specs during start/restart to prevent the use of outdated specifications
```
=> fix(vm): fix VM restart behavior with invalid spec

images/virtualization-artifact/pkg/controller/vi/internal/watcher/vm_watcher.go
Add watcher for virtv2 virtual machines
```changes
section: vi
type: fix
summary: add watcher for virtv2 virtual machines
```
=> fix(vi): add watcher for virtv2 virtual machines

tests/e2e/config/config.go, tests/e2e/default_config.yaml, tests/e2e/go.mod, tests/e2e/image_hotplug_test.go, tests/e2e/testdata/image-hotplug/base/cfg/cloudinit.yaml, tests/e2e/testdata/image-hotplug/base/kustomization.yaml, tests/e2e/testdata/image-hotplug/base/transformer.yaml, tests/e2e/testdata/image-hotplug/base/vd-root.yaml, tests/e2e/testdata/image-hotplug/base/vm.yaml, tests/e2e/testdata/image-hotplug/cvi/cvi-alpine-http.yaml, tests/e2e/testdata/image-hotplug/cvi/cvi-ubuntu-2204-iso.yaml, tests/e2e/testdata/image-hotplug/cvi/kustomization.yaml, tests/e2e/testdata/image-hotplug/kustomization.yaml, tests/e2e/testdata/image-hotplug/ns.yaml, tests/e2e/testdata/image-hotplug/overlays/image-hotplug/kustomization.yaml, tests/e2e/testdata/image-hotplug/transformer.yaml, tests/e2e/testdata/image-hotplug/vi/kustomization.yaml, tests/e2e/testdata/image-hotplug/vi/vi-alpine-http.yaml, tests/e2e/testdata/image-hotplug/vi/vi-pvc-alpine-http.yaml, tests/e2e/tests_suite_test.go, tests/e2e/util_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go
- refactor e2e disk attachment test case
- refactor e2e disk resizing test case
It fixes test cases where we use blockDeviceId and adds a new test case for the image attachment flow.
```changes
section: images
type: test
summary: "It fixes test cases where we use blockDeviceId and adds a new test case for the image attachment flow."
```
=> test(images): add e2e image attachment test case

images/bounder/werf.inc.yaml, images/virtualization-artifact/pkg/controller/bounder/bounder.go, images/virtualization-artifact/pkg/controller/service/bounder_service.go, images/virtualization-artifact/pkg/controller/vi/internal/mock.go, images/virtualization-artifact/pkg/controller/vi/internal/source/interfaces.go, images/virtualization-artifact/pkg/controller/vi/internal/source/mock.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot_cr.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot_cr_test.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot_pvc.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vdsnapshot_pvc_test.go, images/virtualization-artifact/pkg/controller/vi/internal/source/step/ready_cr_step.go, images/virtualization-artifact/pkg/controller/vi/internal/source/step/ready_pvc_step.go
Bug fixes related to VirtualImage and VDSnapshot ObjectRef:
- Added CMD for Bounder image
- Introduced finalizer for Bounder
- Cleaned up resources after Bounder completes its work
- Removed temporary PVC for DVCR target
```changes
section: vi
type: fix
summary: bug fixes related to VirtualImage and VDSnapshot ObjectRef
```
=> feat: enhance CMD instruction for the Bounder image

images/virt-artifact/patches/037-set-ReadOnlyRootFilesystem-to-virt-launcher.patch, images/virt-artifact/patches/README.md
Set ReadOnlyRootFilesystem to virt-launcher.
Add patch `037-set-ReadOnlyRootFilesystem-to-virt-launcher.patch`, this patch enables ReadOnlyRootFilesystem for the virt-launcher compute pod.
Since libvirt and QEMU require writable directories, five emptyDir volumes are added and mounted to:
- /var/run
- /var/log
- /etc/libvirt
- /var/lib/libvirt/
- /var/cache/libvirt
This ensures compatibility while maintaining a read-only root filesystem for improved isolation and security.
```changes
type: feat
summary: Set readOnly for file system in virtual machine pods.
```
=> feat(kubevirt): set ReadOnlyRootFilesystem to virt-launcher

tests/e2e/go.mod, tests/e2e/vm_disk_resizing_test.go
- Fix race condition between `ready` and `resizing` phases
- Use Virtualization API constants in code
- Improve context descriptions
```changes
section: vd
type: test
summary: "No changes for user experience." 
```
=> test(vd): refactor disk-resizing e2e test case

api/core/v1alpha2/vmcondition/condition.go, images/virtualization-artifact/pkg/controller/service/snapshot_service.go, images/virtualization-artifact/pkg/controller/vdsnapshot/internal/watcher/kvvmi_watcher.go, images/virtualization-artifact/pkg/controller/vm/internal/filesystem.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/watcher/vm_watcher.go, tests/e2e/vd_snapshots_test.go, tests/e2e/vm_label_annotation_test.go
Rename `FilesystemReady` condition to `FilesystemFrozen`.
```changes
section: vm
type: fix
summary: rename filesystemReady condition to filesystemFrozen
```
=> fix(vm): rename filesystemReady condition to filesystemFrozen

tests/e2e/sizing_policy_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_migration_test.go
This PR fixes a panic occurring in E2E tests due to improper error handling in `Expect` statements.  
The issue was caused by passing `err` directly as an additional argument:  
```go
Expect(err).NotTo(HaveOccurred(), err)
```  
Since `err` is an interface (`error`), `fmt.Sprintf()` attempted to format it incorrectly, leading to a type assertion panic:  
```go
interface conversion: interface {} is *errors.errorString, not string
```  
To resolve this, `err` is now explicitly converted to a string using `err.Error()`, ensuring proper formatting and avoiding panics.  
- Fixes test stability by preventing runtime panics.  
- Ensures error messages are correctly formatted and displayed.  
- Improves the reliability of test failure diagnostics.  
```changes
section: test
type: fix
summary: fix …
```
=> test: fix panic caused by incorrect error formatting

images/virt-artifact/patches/037-set-ReadOnlyRootFilesystem-to-virt-launcher.patch
add limits for init container `etc-libvirt-init`
```changes
type: fix
summary: add limits for init container `etc-libvirt-init` 
```
=> fix(kubevirt): add limits for init container `etc-libvirt-init`

tests/e2e/sizing_policy_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_migration_test.go
Fix e2e panics caused by nil pointer of optional assert description.
```changes
section: test
type: fix
summary: "fix panic caused by incorrect error formatting"
```
=> test(api): fix e2e panics

images/virtualization-artifact/pkg/common/network_policy/network_policy.go, images/virtualization-artifact/pkg/controller/service/disk_service.go, images/virtualization-artifact/pkg/controller/service/importer_service.go, images/virtualization-artifact/pkg/controller/service/uploader_service.go, images/virtualization-artifact/pkg/controller/uploader/uploader_pod.go
Create a network policy for the uploader to avoid restrictions during import to dvcr
Give uploader pod access to dvcr when using projects
When uplodaer is created, a NetworkPolicy with egress rules will be created
```changes
section: api
type: feat
summary:  create a network policy for the uploader to avoid restrictions during import to dvcr
```
=> feat(vi): add network policy creation in UploaderService

images/virtualization-artifact/pkg/controller/vm/internal/filesystem.go, tests/e2e/vd_snapshots_test.go
Fix filesystem frozen condition blinks.
```changes
section: vm
type: fix
summary: "fix filesystem frozen condition blinks"
```
=> fix(vm): fix filesystem frozen condition blinks

images/virt-artifact/patches/037-set-ReadOnlyRootFilesystem-to-virt-launcher.patch, images/virt-artifact/patches/README.md
Add new emptydirs mounted to `/tmp` and  `/var/lib/swtpm-localca` for virt-launcher 
```bash
[root@vm-win11-1 /]# cat /var/log/swtpm/libvirt/qemu/dprytkov_vm-win11-1-swtpm.log
Starting vTPM manufacturing as tss:tss @ Thu 27 Feb 2025 09:59:05 AM UTC
Could not create temporary directory for certs: Failed to create file “/tmp/swtpm_setup.certs.JGNM22”: Read-only file system
```
```changes
section: core
type: fix
summary: Add new emptydirs mounted to `/tmp` and  `/var/lib/swtpm-localca` for virt-launcher 
```
=> fix(kubevirt): Add new emptydirs mounted to `/tmp` and  `/var/lib/swtpm-localca` for virt-launcher 

api/core/v1alpha2/virtual_machine.go, tests/e2e/affinity_toleration_test.go, tests/e2e/complex_test.go, tests/e2e/image_hotplug_test.go, tests/e2e/sizing_policy_test.go, tests/e2e/tests_suite_test.go, tests/e2e/util_test.go, tests/e2e/vd_snapshots_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_connectivity_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_label_annotation_test.go, tests/e2e/vm_migration_test.go
Power state checks were added:
- starting Virtual Machine by VirtualMachineOperation
- stopping Virtual Machine by VirtualMachineOperation
- restarting Virtual Machine by VirtualMachineOperation
- restarting Virtual Machine by ssh
- restarting a Virtual Machine by terminating pods
```changes
section: vm
type: test
summary: "added power state checks"
```
=> test(vm): add powerstate check

tests/e2e/util_test.go, tests/e2e/vm_label_annotation_test.go
Fixed an issue where the resource state was not awaited and an immediate check was performed in the test for annotation and labeling.
```changes
section: vm
type: test
summary: "fixed an issue where the resource state was not awaited and an immediate check was performed in the test for annotation and labeling" 
```
=> test(vm): fix "no waiting" error

images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go
Watch events for PVC creation are missed: VD could have gotten stuck in Provisioning instead of WaitForFirstConsumer
```changes
section: vd
type: fix
summary: watch pvc creation events
```
=> fix(vd): watch pvc creation events

images/dvcr-artifact/cmd/dvcr-cleaner/cmd/delete.go, images/dvcr-artifact/cmd/dvcr-cleaner/cmd/ls.go
add yes flag to dvcr-cleaner
```changes
section: dvcr
type: feat
summary: add yes flag to dvcr-cleaner
```
=> feat: add yes flag to dvcr-cleaner

images/libvirt/install-libvirt.sh, images/virt-launcher/werf.inc.yaml
Added `findmnt` and `nft` to libvirtd dependencies – These tools are necessary for proper functionality and compatibility with libvirtd.
Created a symlink `ln -s var/run run` – This ensures compatibility and resolves potential issues with paths expecting /run to exist as a symlink to /var/run.
Some virtual machines can't start, error in logs like: `Still missing PID for vm /run/libvirt/qemu/vm.pid no such file or directory`
```changes
section: core
type: fix
summary: fix symlinks and add missing binaries virt-launcher
```
=> fix(core): fix symlinks and add missing binaries virt-launcher

images/libvirt/patches/001-disable-ro-and-admin-servers.patch, images/libvirt/patches/README.md, images/libvirt/werf.inc.yaml, images/virt-artifact/patches/038-disable-unnecessary-libvirt-sockets.patch, images/virt-artifact/patches/README.md
Disable unnecessary libvirt servers
This patch introduces new flags to enhance the security and control of QEMU services:
- Adds `--no-admin-srv` and `--no-ro-srv` flags to `virtqemud`.
- Adds `--no-admin-srv` flag to `virtlogd`.
These flags allow disabling the read-only and admin servers for `virtqemud` and the admin server for `virtlogd`, respectively, providing better control over the services and reducing potential attack surfaces.
When all flags are set, the following sockets will be disabled:
- `/var/run/libvirt/virtlogd-admin-sock`
- `/var/run/libvirt/virtqemud-admin-sock`
- `/var/run/libvirt/virtqemud-sock-ro`
This patch disables unnecessary libvirt sockets by running `virtqemud` and `virtlogd` with additional flags to prevent their creation. Specifically, we disable the admin and …
=> feat(core): disable unnecessary libvirt servers

images/virt-artifact/patches/037-set-ReadOnlyRootFilesystem-to-virt-launcher.patch, images/virt-launcher/werf.inc.yaml
Previously, an init container was used to copy `/etc/libvirt` to `emptyDir` because the filesystem was mounted with `ReadOnlyRootFilesystem`, but we needed write access.  
With this change:  
- The init container has been removed.  
- During the build process, `/etc/libvirt` is now copied to `/etc/libvirt-init`.  
- A new `setupLibvirt` function has been added to `virt-launcher`, which copies the files back to `/etc/libvirt` if `/etc/libvirt-init` exists.  
This eliminates the need for an extra init container while preserving the required functionality.
```changes
type: refactor
summary: Remove init container etc-libvirt-init and handle setup in virt-launcher
```
=> refactor(kubevirt): Remove init container `etc-libvirt-init` and handle setup in virt-launcher

images/virt-launcher/werf.inc.yaml
Swtpm configs and gnutls-utils was added to virt-laucher, for correct launch windows vm and vm with UEFI
Without these components, the vm with UEFI will not migrate
```changes
section: core
type: fix
summary:  add swtpm configs and gnutls-utils to virt-launcher image
```
=> fix(core): add swtpm configs and gnutls-utils to virt-launcher image

images/virtualization-artifact/pkg/controller/vm/internal/validators/cpu_count_validator.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/cpu_count_validator_test.go
Fix bug that is triggered by the absence of the escape in the positive case and failing to continue on switch case
```changes
section: vm
type: fix
summary: correct CPU core validation logic for range checks
```
=> fix(vm): correct CPU core validation logic for range checks

tests/e2e/complex_test.go, tests/e2e/util_test.go
A race condition occurs between checking the `stopped` and `running` phases.
```changes
section: vm
type: test
summary:  "Fix a race condition in the `VirtualMachine` restarting  test case."
```
=> test(vm): fix a race condition in the vm restarting test case

images/virt-launcher/werf.inc.yaml
Improved code readability virt-launcher build
```changes
section: core
type: refactor
summary: improve code readability virt-launcher image build
```
=> refactor(core): virt-launcher

images/virt-launcher/werf.inc.yaml
Add mknod binary to virt-launcher image
Without mknod the script node-labeller.sh crashes with an error 
```
usr/bin/node-labeller.sh: line 24: mknod: command not found
```
and as a consequence pod virt-handler does not start.
virt-handler started successful
```changes
section: core
type: fix
summary: add mknod binary to virt-launcher image
```
=> fix(core): virt-launcher add missing mknod

tests/e2e/affinity_toleration_test.go, tests/e2e/kubectl/kubectl.go, tests/e2e/testdata/affinity-toleration/vm/base/vm.yaml, tests/e2e/testdata/affinity-toleration/vm/kustomization.yaml, tests/e2e/testdata/affinity-toleration/vm/overlays/vm-a-not-b/vm.vmclass.patch.yaml, tests/e2e/testdata/affinity-toleration/vm/overlays/vm-b-not-a/kustomization.yaml, tests/e2e/testdata/affinity-toleration/vm/overlays/vm-b-not-a/vm.vmclass.patch.yaml, tests/e2e/testdata/affinity-toleration/vm/overlays/vm-c-and-a/kustomization.yaml, tests/e2e/testdata/affinity-toleration/vm/overlays/vm-c-and-a/vm.vmclass.patch.yaml, tests/e2e/testdata/affinity-toleration/vm/overlays/vm-d/kustomization.yaml, tests/e2e/testdata/affinity-toleration/vm/overlays/vm-d/vm.vmclass.patch.yaml, tests/e2e/testdata/affinity-toleration/vm/overlays/vm-node-affinity/kustomization.yaml, tests/e2e/testdata/affinity-toleration/vm/overlays/vm-node-selector/kustomization.yaml, tests/e2e/util_test.go, tests/e2e/vm_connectivity_test.go
- Improve Ginkgo contexts
- Add node selector configuration case
- Add node affinity configuration case
- Add virtual machine and pod affinity configuration case
- Add virtual machine and pod anti-affinity configuration case
This extends the affinity and toleration test cases.
```changes
section: vm
type: test
summary: "This extends the affinity and toleration test cases."
```
=> test(vm): refactor affinity and toleration test case

templates/virtualization-audit/validation-webhook.yaml
Add rules for ValidatingWebhookConfiguration
```changes
section: 
type: 
summary: 
```
=> feat(audit): add webhook rules

images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go
User required sockets count for MaxSockets in VM spec
In some cases with Windows 11 that's cause bugs
```changes
section: vm
type: fix
summary: correct maximum CPU sockets assignment in domain specification 
```
=> fix(vm): correct maximum CPU sockets assignment in domain specification 

images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state_test.go
This pull request addresses issues related to starting virtual machines after changes in their power settings. Specifically, it fixes the following scenarios:
- AlwaysOff to AlwaysOn: Resolves the problem that prevented virtual machines from starting automatically when their setting is changed from "AlwaysOff" to "AlwaysOn".
- AlwaysOff to AlwaysOnUnlessStoppedManually: Corrects the issue that hindered the automatic start of virtual machines when transitioning from "AlwaysOff" to "AlwaysOnUnlessStoppedManually".
```changes
section: vm
type: fix
summary: fix start VM after change run policy from AlwaysOff
```
=> fix(vm): fix start vm after change run policy from AlwaysOff 

api/core/v1alpha2/cvicondition/condition.go, api/core/v1alpha2/vdcondition/condition.go, api/core/v1alpha2/vicondition/condition.go, images/virtualization-artifact/pkg/controller/conditions/builder.go, images/virtualization-artifact/pkg/controller/cvi/cvi_reconciler.go, images/virtualization-artifact/pkg/controller/cvi/internal/datasource_ready.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/errors.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vd/internal/inuse.go, images/virtualization-artifact/pkg/controller/vd/internal/inuse_test.go, images/virtualization-artifact/pkg/controller/vi/internal/datasource_ready.go, images/virtualization-artifact/pkg/controller/vi/internal/source/errors.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vi/vi_reconciler.go, images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vm/internal/block_devices_test.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go, images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go
• Optimize the operation of the handler inUse.
• Improve the message in the BlockDeviceReady condition for the VM.
• Remove the phase 'Stopped' during startup when launching a VirtualMachine with the run policies AlwaysOn and AlwaysOnUnlessStopManually.
```changes
section: vd
type: refactor
summary: refactor handle inUse condition 
```
=> refactor(vd): refactor handle inuse condition

hooks/migrate_delete_renamed_validation_admission_policy.py, images/virt-artifact/patches/015-rename-core-resources.patch
- Rename internal resources: ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding.
- Add afterHelm hook to delete orphan resources.
Kubevirt installs ValidatingAdmissionPolicy in Kubernetes >=1.30.
Rename this ValidatingAdmissionPolicy resource to not conflict with the original Kubevirt installation.
1. Original Kubevirt installs successfully.
2. No VAP with original name after module update:
Before:
```
...
kubevirt-node-restriction-binding                    kubevirt-node-restriction-policy               <unset>    3m24s
```
After:
```
NAME                                                       VALIDATIONS   PARAMKIND   AGE
...
kubevirt-internal-virtualization-node-restriction-policy   6             <unset>     27m
```
```changes
section: core
type: fix
summary: Rename internal …
```
=> fix(core): rename ValidatingAdmissionPolicy to not conflict with original kubevirt

images/virtualization-artifact/.golangci.yaml, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm_utils.go, images/virtualization-artifact/pkg/controller/service/attachment_service.go, images/virtualization-artifact/pkg/controller/vm/internal/block_device.go, images/virtualization-artifact/pkg/controller/vm/internal/block_devices_test.go, images/virtualization-artifact/pkg/controller/vm/internal/state/state.go, images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go, images/virtualization-artifact/pkg/controller/vmbda/internal/deletion.go, images/virtualization-artifact/pkg/controller/vmbda/internal/errors.go, images/virtualization-artifact/pkg/controller/vmbda/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vmbda/internal/watcher/kvvmi_watcher.go, images/virtualization-artifact/pkg/controller/vmbda/internal/watcher/vm_watcher.go
1. BlockDeviceHandler was violating the contract regarding the setting of `.status.blockDeviceRefs`.
BlockDeviceHandler was populating `.status.blockDeviceRefs` based on what was in `.spec` and from the existing vmbda in the cluster, which led to problems. 
`.status.blockDeviceRefs` should reflect not only the block devices expected to be attached as per the spec but also those that are present in kvvm (these two sets of block devices may not match). Fixed this.
2. The log level of conflict error (“the object has been modified; please apply your changes to the latest version and try again”) for virtual machines is now set to debug, not error.
3. The vmbda will no longer be deleted until detaching is completed.
```changes
section: vm
type: fix
summary: add missed but attached block device …
```
=> fix(vm): ensure detachment happened

.github/workflows/dev_module_build-and-registration.yml, .github/workflows/dev_module_build.yml
Refactor labels for runners
Add additional label `build/self-hosted/regular` for deckhouse runners with 8GB RAM
```changes
section: ci
type: chore
summary: Refactor labels for runners, add additional label build/self-hosted/regular for deckhouse runners with 8GB RAM
```
=> refactor(ci): refactor runners labels

.github/scripts/prs_notifier.mjs
Increase the duration to detect prs that are stuck
```changes
section: ci
type: chore
summary: increase the duration to detect prs that are stuck
```
=> chore(ci): increase the duration to detect prs that are stuck

hooks/migrate_delete_renamed_validation_admission_policy.py
- Use v1beta1 so migration hook can work in Kubernetes 1.28 and 1.29.
Kubernetes subscriptions not support subscribe to nonexistent versions of CRD (yet).  ValidatingAdmissionPolicy/v1 exists in Kubernetes 1.30 and later, so we use v1beta1 for now. We can just delete this hook when v1beta1 will be removed (in 1.36 may be?).
Continuation of #839 
VAP Migration hook works in Kubernetes 1.28 and 1.29
```changes
section: core
type: fix
summary: Fix ValidatingAdmissionPolicy migration hook, it should support Kubernetes 1.28+
```
=> fix(core): use v1beta1 version for ValidatingAdmissionPolicy

monitoring/grafana-dashboards/main/virtual-machine.json
fix OS Windows mountpoint promql
```changes
type: fix
summary: fix OS Windows mountpoint promql
```
=> fix(module): fix OS Windows mountpoint promql

images/virt-artifact/patches/039-get-applied-checksum.patch
fix RBAC: Add Patch Permissions for DS virt-handler on VMI
```changes
section: kubevirt 
type: fix
summary: Add Patch Permissions for DS virt-handler on VMI
```
=> fix(kubevirt):  fix RBAC: Add Patch Permissions for DS virt-handler on VMI

api/core/v1alpha2/cvicondition/condition.go, images/virtualization-artifact/pkg/controller/cvi/cvi_reconciler.go, images/virtualization-artifact/pkg/controller/cvi/internal/datasource_ready.go, images/virtualization-artifact/pkg/controller/cvi/internal/watcher/vdsnapshot_watcher.go, images/virtualization-artifact/pkg/controller/indexer/cvi_indexer.go, images/virtualization-artifact/pkg/controller/indexer/indexer.go, images/virtualization-artifact/pkg/controller/vdsnapshot/internal/watcher/vm_watcher.go
1. Add the omitted watcher for vd snapshots
2. Fix the display of the error for the user if the snapshot is not ready yet
3. Improve watcher for virtual machines
```changes
section: cvi 
type: fix
summary: add the omitted watcher for vd snapshots
```
=> fix(cvi): watch vd snapshot

templates/dvcr/service-monitor.yaml, templates/virtualization-controller/scrape-config.yaml
add CRD check for DVCR ServiceMonitor and ScrapeConfig
We need to be able to do a minimal installation without using prometheus.
```changes
type: fix
summary: add CRD check for DVCR ServiceMonitor and ScrapeConfig
```
=> fix(module): add CRD check for DVCR ServiceMonitor and ScrapeConfig

tests/e2e/util_test.go, tests/e2e/vm_configuration_test.go
Reboot vms with force flag
```changes
section: vm
type: chore
summary: reboot vms with force flag
```
=> test(vm): reboot vms with force

images/virtualization-artifact/pkg/controller/powerstate/kvvm_request.go, images/virtualization-artifact/pkg/controller/powerstate/operations.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state.go
- Add checks for current restarts when attempting to start a VM with AlwaysOn.
- In the sync_powerstate.go handler, add a check for the deletion of the current VM.
- Add a check for the current status of StateChangeRequests when creating a new request.
This PR fix errors with power state operations. For example: 
```
[
{
"controller": "vm-controller",
"name": "head-ec22cb89-vm-automatic-conf",
"namespace": "head-ec22cb89-testcases-vm-configuration",
"msg": "failed to sync powerstate: failed to start VM: unable to complete request: stop/start already underway",
"err": null,
"source": "usr/local/go/src/virtualization-controller/pkg/controller/vm/internal/sync_power_state.go:82"
},
{
"controller": "vm-controller",
"name": "head-ec22cb89-vm-manual-conf",
"namespace": …
```
=> fix(vm): fix errors with power state operations

images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go
Do not display node of stopped  VMs
```changes
section: vm
type: chore
summary: "Do not display node of stopped VMs"
```
=> chore(vm): do not display node of stopped VMs

images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go
Return a named error when VirtualImage not found.
```changes
section: vd
type: fix
summary: "return a named error when VirtualImage is not found to avoid throw handler error"
```
=> fix(vd): fix object ref validation

tests/e2e/sizing_policy_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_connectivity_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_label_annotation_test.go
Fix e2e panic caused wrong assertation.
```changes
section: api
type: fix
summary: "fix e2e panic caused wrong assertation"
```
=> fix(test): fix e2e panic

tests/e2e/util_test.go, tests/e2e/vm_configuration_test.go
We had tests failing because the command ssh `reboot -f` was not executing completely. More precisely, the reboot request was sent, and the virtual machine rebooted successfully, but the SSH session remained active throughout the reboot process and eventually disconnected with a timeout error:
> Error: websocket: close 1006 (abnormal closure): unexpected EOF 
This caused the test to fail. The `-f` flag was causing this behavior. Without it, everything worked fine. I resolved it by rebooting with `nohup reboot -f`.
```changes
section: vm
type: chore
summary: reboot using nohup
```
=> test(vm): reboot using nohup

images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go, tests/e2e/default_config.yaml
Suppressed the output of "internal virtual machine error" when a pod is unschedulable.
```changes
section: vm
type: fix
summary: Suppressed the output of internal virtual machine error when a pod is unschedulable.
```
=> fix(vm): suppressed the output of "internal virtual machine error" when a pod is unschedulable

images/virtualization-artifact/pkg/common/network_policy/network_policy.go, images/virtualization-artifact/pkg/controller/importer/importer_pod.go, images/virtualization-artifact/pkg/controller/service/importer_service.go, images/virtualization-artifact/pkg/controller/service/uploader_service.go, images/virtualization-artifact/pkg/controller/uploader/uploader_pod.go
fix some panics in upload import service
```changes
section: cvi
type: fix
summary: fix some panics in upload service
```
=> fix(cvi, vi): fix some panics in upload import service

tests/e2e/config/config.go, tests/e2e/default_config.yaml, tests/e2e/errlogger/errlogger.go, tests/e2e/tests_suite_test.go
Add regexp log parser
```changes
section: vm
type: feature
summary:  Add regexp log parser
```
=> test: add regexp log parser

.github/workflows/nightly_e2e_tests_main.yaml, tests/e2e/Taskfile.yaml
This change increases the timeout duration for Ginkgo-based end-to-end (e2e) tests.
As the number of e2e tests has grown significantly, the current timeout of 1 hour is no longer sufficient to complete all test cases. This limitation has resulted in incomplete test runs and potential disruptions to the testing process. By extending the timeout, we ensure that all tests have adequate time to execute, regardless of their increasing complexity and count.
The timeout for all e2e tests will be increased to 2 hours . This adjustment will allow the entire test suite to run to completion without premature termination, ensuring reliable and consistent test results.
```changes
section: ci
type: chore
summary: increase timeout for e2e tests
```
=> test: increase e2e tests timeout

images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go
Temporary enable EFI patch for Windows too. It's fix Windows booting with more than 8 cores and EFI bootloader.
```changes
section: vm
type: fix
summary: resolving EFI Boot Issues on Windows Systems with more than 8 cores
```
=> fix(vm): EFI boot with Windows

.github/workflows/nightly_e2e_tests_main.yaml, tests/e2e/affinity_toleration_test.go, tests/e2e/complex_test.go, tests/e2e/image_hotplug_test.go, tests/e2e/images_creation_test.go, tests/e2e/importer_network_policy_test.go, tests/e2e/kubectl/kubectl.go, tests/e2e/sizing_policy_test.go, tests/e2e/util_test.go, tests/e2e/vd_snapshots_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_connectivity_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_label_annotation_test.go, tests/e2e/vm_migration_test.go, tests/e2e/vm_version_test.go
This PR introduces a mechanism to automatically dump all test-related resources into a single YAML file whenever a test fails. This enhancement provides a comprehensive snapshot of the test environment at the time of failure, enabling faster debugging and more efficient issue resolution.
When tests fail, diagnosing the root cause often requires inspecting the state of various resources (e.g., deployments, pods, services, config maps, secrets) in the test environment. However:
Manually gathering these resources is time-consuming and error-prone.
Resource states may change or be deleted before they can be inspected.
Lack of a unified view makes it difficult to reproduce and analyze failures.
This PR addresses these challenges by automating the collection of all relevant resources into a …
=> chore(test): dump resources on error

images/virtualization-artifact/pkg/controller/cvi/internal/deletion.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/http.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/sources.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vd/internal/deletion.go, images/virtualization-artifact/pkg/controller/vi/internal/deletion.go
1. Requeuing with a 0-second delay triggers the rate limiter, which could cause some required requeues to be delayed, leading to block devices getting stuck in the Terminating phase. Overall, requeuing with a 0-second delay is a bad practice that should be avoided
2. cvi CleanUp now also returns `(bool, error)`, just like vd and vi. It's consistent now.
```changes
section: api
type: fix
summary: fix the issue of block devices getting stuck in the Terminating phase.
```
=> fix(api): avoid requeue rate limiter

.github/workflows/dev_module_build.yml
Signed-off-by: Maksim Fedotov <maksim.fedotov@flant.com>
Prevent `pull_request_info` job from running on non-PR events.
Fix #903 
```changes
section: ci
type: fix
summary: prevent pr info job from running on non-PR events
```
=> fix(ci): prevent pr info job from running on non-PR events

tests/e2e/affinity_toleration_test.go, tests/e2e/complex_test.go, tests/e2e/image_hotplug_test.go, tests/e2e/images_creation_test.go, tests/e2e/importer_network_policy_test.go, tests/e2e/sizing_policy_test.go, tests/e2e/util_test.go, tests/e2e/vd_snapshots_test.go, tests/e2e/vm_configuration_test.go, tests/e2e/vm_connectivity_test.go, tests/e2e/vm_disk_attachment_test.go, tests/e2e/vm_disk_resizing_test.go, tests/e2e/vm_label_annotation_test.go, tests/e2e/vm_migration_test.go, tests/e2e/vm_version_test.go
Clarification of the file name for dumps on test failures, now the file name includes the specific case in which the test crashed.
```changes
section: ci
type: chore
summary: improve failed test dump
```
=> chore(test): add additional error dump info

docs/INSTALL.md, docs/INSTALL_RU.md
Fix external link on the Installation page.
Change link from code example. 
```changes
section: docs
type: chore
summary: Change external link from code example on the Installation page. 
```
=> docs: fix external link on Installation page

module.yaml
Add module.yaml
```changes
type: chore
summary: add module.yaml
```
=> chore(module): add module.yaml

.github/workflows/dev_validation.yaml
Set github runner to ubuntu-22.04 for validation ci to resolve issue in helm`MaxDecompressedFileSize in v3.17.3`
_Github runner [ubuntu 22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#package-management) has Helm 3.17.2_
Fix issue for Helm MaxDecompressedFileSize in v3.17.3 breaks existing charts
This kind of error should not appear
```
Error: chart file "pack-06f1f1e37225d4f66574349a84f9965285a33fa6.pack" is larger than the maximum file size 5242880
[51](https://github.com/deckhouse/virtualization/actions/runs/14497617070/job/40669259973?pr=919#step:4:52)helm.go:86: 2025-04-16 16:22:33.394135655 +0000 UTC m=+11.354853839 \[debug\] chart file "pack-06f1f1e37225d4f66574349a84f9965285a33fa6.pack" is larger than the maximum file size 5242880
``` …
=> chore(ci): set github runner to ubuntu-22.04 for validation ci

.github/workflows/dev_build_precache.yml, .github/workflows/dev_module_build-and-registration.yml, .github/workflows/release_module_build-and-registration.yml, .github/workflows/release_module_release-channels.yml
This PR introduces two key updates across multiple GitHub Actions workflows:  
1. Adds `SOURCE_REPO_GIT` environment variable (sourced from secrets) to workflows including `dev_build_precache.yml`, `dev_module_build-and-registration.yml`, and `release_module_*` configurations.  
2. Replaces `ubuntu-latest` runners with self-hosted large runners (`[self-hosted, large]`) for resource-intensive jobs like `prod_ce_setup_build`, `prod_ee_setup_build`, and downstream jobs in release workflows.  
1. **`SOURCE_REPO_GIT` Addition**:  
- Resolves authentication or repository access issues by providing a dedicated Git-specific credential source, ensuring secure and reliable repository operations.  
2. **Self-Hosted Runners**:  
- Reducing execution time.  
**Faster CI/CD Pipelines**: Self-hosted …
=> chore(ci): add env SOURCE_REPO_GIT, change runners for release ci to self-hosted

tests/e2e/complex_test.go, tests/e2e/config/config.go, tests/e2e/default_config.yaml, tests/e2e/kubectl/kubectl.go, tests/e2e/sig_test.go, tests/e2e/testdata/vm-migration-cancel/kustomization.yaml, tests/e2e/testdata/vm-migration-cancel/ns.yaml, tests/e2e/testdata/vm-migration-cancel/transformer.yaml, tests/e2e/testdata/vm-migration-cancel/vi/kustomization.yaml, tests/e2e/testdata/vm-migration-cancel/vi/vi-alpine-http-bios.yaml, tests/e2e/testdata/vm-migration-cancel/vi/vi-alpine-http-uefi.yaml, tests/e2e/testdata/vm-migration-cancel/vm/base/cfg/cloudinit.yaml, tests/e2e/testdata/vm-migration-cancel/vm/base/kustomization.yaml, tests/e2e/testdata/vm-migration-cancel/vm/base/transformer.yaml, tests/e2e/testdata/vm-migration-cancel/vm/base/vd-blank.yaml, tests/e2e/testdata/vm-migration-cancel/vm/base/vd-root.yaml, tests/e2e/testdata/vm-migration-cancel/vm/base/vm.yaml, tests/e2e/testdata/vm-migration-cancel/vm/kustomization.yaml, tests/e2e/testdata/vm-migration-cancel/vm/overlays/migration-bios/kustomization.yaml, tests/e2e/testdata/vm-migration-cancel/vm/overlays/migration-bios/vd.image.patch.yaml, tests/e2e/testdata/vm-migration-cancel/vm/overlays/migration-uefi/kustomization.yaml, tests/e2e/testdata/vm-migration-cancel/vm/overlays/migration-uefi/vd.image.patch.yaml, tests/e2e/testdata/vm-migration-cancel/vm/overlays/migration-uefi/vm.bootloader.patch.yaml, tests/e2e/util_test.go, tests/e2e/vm_migration_cancel_test.go, tests/e2e/vm_migration_test.go
add test vmop migration cancel
```changes
section: vmop
type: feature
summary: add test vmop migration cancel 
```
=> test(vmop): add test vmop migration cancel

.github/workflows/dev_module_build.yml, tests/e2e/Taskfile.yaml
Signed-off-by: Maksim Fedotov <maksim.fedotov@flant.com>
Add following QoL features to e2e:
- add `cleanup` task to automatically remove all resources created by e2e tests.
- add timeout for cleanup job
- move label removal to separate job to fix issues with `e2e/run` label not being removed if the job is cancelled before the start of e2e tests
```changes
section: ci
type: chore
summary: add QoL-features to automatic e2e tests
```
=> chore(ci): add QoL-features to automatic e2e tests

api/core/v1alpha2/events.go, api/core/v1alpha2/vicondition/condition.go, images/virtualization-artifact/pkg/controller/service/vi_storage_class_service.go, images/virtualization-artifact/pkg/controller/service/vi_storage_class_service_test.go, images/virtualization-artifact/pkg/controller/vd/internal/storageclass_ready.go, images/virtualization-artifact/pkg/controller/vi/internal/interfaces.go, images/virtualization-artifact/pkg/controller/vi/internal/mock.go, images/virtualization-artifact/pkg/controller/vi/internal/source/http.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/vi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vi/internal/storageclass_ready.go, images/virtualization-artifact/pkg/controller/vi/internal/storageclass_ready_test.go, images/virtualization-artifact/pkg/controller/vi/vi_controller.go
- handle default storage class from the module config
- fix `StorageClassReady` condition
When a VirtualImage is created without the StorageClass field in its specification and the default storage class is absent from the ModuleConfig, it is not handled after updating the default storage class in the ModuleConfig.
The default storage class field works properly in the reconciliation loop of the VirtualImage resource.
```changes
section: vi,vd 
type: fix
summary: "The `VirtualImageDefaultStorageClass` from the `ModuleConfig` is handled correctly now." 
```
=> fix(vi,vd): fix default storage class usage

tests/e2e/util_test.go
dump intvirt resources
```changes
section: core
type: chore
summary: dump intvirt resources
```
=> tests: dump intvirt resources

images/virtualization-artifact/pkg/controller/vm/internal/watcher/clustervirtualimage_watcher.go, images/virtualization-artifact/pkg/controller/vm/internal/watcher/kvvm_watcher.go, images/virtualization-artifact/pkg/controller/vm/internal/watcher/kvvmi_watcher.go, images/virtualization-artifact/pkg/controller/vm/internal/watcher/pod_watcher.go, images/virtualization-artifact/pkg/controller/vm/internal/watcher/virtualdisk_watcher.go, images/virtualization-artifact/pkg/controller/vm/internal/watcher/virtualimage_watcher.go, images/virtualization-artifact/pkg/controller/vm/internal/watcher/vmip_watcher.go, images/virtualization-artifact/pkg/controller/vm/vm_reconciler.go
move watchers out into a separate package
```changes
section: vm
type: chore
summary: move watchers out into a separate package
```
=> refactor(vm): move watchers out into a separate package

base-images/deckhouse_images.yml, images/virt-handler/werf.inc.yaml, images/virt-launcher/werf.inc.yaml
Replace `cp` and `sleep` to self-build binaries coreutils
- virt-launcher `cp` and `sleep`
- virt-handler `cp`
We want more control when building binary files, as well as making images more secure
```changes
section: core
type: chore
summary: replace binaries with self-build binaries in virt-launcher and virt-handler
```
=> chore(core): replace binaries with self-build binaries in virt-launcher and virt-handler

images/virtualization-artifact/pkg/controller/vmip/internal/lifecycle_handler.go
This PR refactors the lifecycle handler logic for VirtualMachineIPAddress (VMIP) resources to simplify the state management.
Key behavior changes:
- The VMIP phase will now always be updated in each case, rather than only when it differs from the current phase.
- The attachment to a VirtualMachine is now handled as part of the Bound case rather than as a separate condition.
The VirtualMachineIPAddress resource have Bound and Attached conditions with status Unknown.
```changes
section: vmip 
type: fix
summary: Improve Status Reporting
```
=> fix(vmip): fix display of conditions Bound and Attached

images/virtualization-artifact/pkg/controller/vm/internal/block_device_condition.go
This pull request refactors the handling of block device conditions within the VM controller.
- **Message Generation Simplification:**
- Consolidated message generation for disk states by removing redundant functions and using a closure `addUsageMessage` to handle single and multiple disk scenarios more concisely.
- **Issue Fix:**
- Corrected the issue where a stopped VM with a single disk incorrectly displayed the `BlockDevicesReady` status as `False`.
```changes
section: vm
type: fix
summary: Improve BlockDevicesReady's condition message 
```
=> fix(vm): fix display BlockDeviceReady condition's message

images/virtualization-artifact/pkg/builder/vm/option.go, images/virtualization-artifact/pkg/common/kvvm/kvvm.go, images/virtualization-artifact/pkg/controller/powerstate/operations_test.go, images/virtualization-artifact/pkg/controller/vm/internal/statistic_test.go, images/virtualization-artifact/pkg/controller/vm/internal/suite_test.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state_test.go
Сhoose correct active pod
In some cases, we display an incorrect active pod for a VM. For example,
if there was a migration via vmop and it failed, the VM status will show an incorrect pod as active.
```changes
section: vm
type: fix
summary: Choose a correct active pod to show in the VM status
```
=> fix(vm): choose correct active pod

tests/e2e/vm_migration_cancel_test.go
increase timeout for migration abort
```changes
section: vm 
type: fix
summary: increase timeout for migration abort
```
=> test(vm): increase timeout for migration abort

images/virtualization-artifact/pkg/controller/service/restorer/restorer.go
Handle the `vm.spec.provisioning` correctly when its value is nil.
When the `vm.spec.provisioning` is nil, it causes a panic in the controller.
```changes
section: vmrestore
type: fix
summary: "Handle the `vm.spec.provisioning` correctly when its value is empty." 
```
=> fix(vmrestore): handle the nil value `vm.spec.provisioning`

images/virtualization-artifact/pkg/controller/vmop/internal/service/migrate.go
fix panic when migration failed
```changes
section: vmop 
type: fix
summary:  fix panic when migration failed
```
=> fix(vmop): fix panic when migration failed

component_versions/version_map.yml, images/packages/binaries/openssl/werf.inc.yaml, images/virt-launcher/werf.inc.yaml
Build the openssl package and replace it in virt-launcher image.
We want more control when building binary files, as well as making images more secure
```changes
section: core
type: chore
summary: build openssl
```
=> chore(core): build openssl

images/virtualization-artifact/pkg/controller/vmip/internal/iplease_handler.go, images/virtualization-artifact/pkg/controller/vmip/vmip_reconciler.go, images/virtualization-artifact/pkg/controller/vmiplease/internal/lifecycle_handler.go, images/virtualization-artifact/pkg/controller/vmiplease/internal/protection_handler.go, images/virtualization-artifact/pkg/controller/vmiplease/internal/retention_handler.go, images/virtualization-artifact/pkg/controller/vmiplease/vmiplease_reconciler.go
This pull request addresses a critical issue where VirtualMachineIPAddressLease was being created twice during the reconciliation process. 
```changes
section: vmip
type: fix
summary: Fixed double creation of VirtualMachineIPAddressLease
```
=> fix(vmip): fix double create VirtualMachineIPLease

tests/e2e/util_test.go
Fix AfterSuite check for E2E tests.
```changes
section: ci
type: chore
summary: fix after suite for e2e tests.
```
=> chore(test): fix after suite for e2e

templates/admission-policy.yaml, templates/virtualization-controller/validation-webhook.yaml
- Use discovery section instead of clusterConfiguration.
- Module may start before node-manager module, so configuration section may not be in sync with the actual cluster state.
Fix switching kubernetes versions. Newer Deckhouse versions use module.yaml requirements for module order calculation and start virtualization module before node-manager module and queue just stuck forever.
Kubernetes version switch is possible with new Deckhouse versions that support requirements in module.yaml (1.69+).
```changes
type: fix
summary: Fix Kubernetes version switch in newer Deckhouse versions (1.69+).
```
=> fix(module): fix Kubernetes version detection in templates

component_versions/version_map.yml, images/cdi-importer/werf.inc.yaml, images/packages/binaries/nbd/werf.inc.yaml, images/packages/binaries/nbdkit/werf.inc.yaml
Build nbdkit for cdi-importer.
```changes
section: core
type: chore
summary: build nbdkit
```
=> refactor(core): build nbdkit

.github/workflows/dev_module_build.yml
Upload artifacts of failed resources on e2e runs similar to nightly e2e job.
To access failed resources after the run.
```changes
section: ci
type: chore
summary:  upload artifacts on PR e2e tests
```
=> chore(ci): upload artifacts on PR e2e tests

images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state.go, tests/e2e/vm_configuration_test.go
This PR fixes a problem where attempting to stop a VM with unapplied changes would result in the VM restarting instead of stopping.
```changes
section: vm
type: fix
summary: Fix stopping a VM with unapplied changes.
```
=> fix(vm): fix stopping a VM with unapplied changes

images/virt-artifact/patches/050-mount-containerdisk-always-readonly.patch, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go, tests/e2e/testdata/vm-migration/cvi/cvi-cirros.yaml, tests/e2e/testdata/vm-migration/cvi/kustomization.yaml, tests/e2e/testdata/vm-migration/kustomization.yaml, tests/e2e/testdata/vm-migration/vm/kustomization.yaml, tests/e2e/testdata/vm-migration/vm/overlays/with-cvi/kustomization.yaml, tests/e2e/testdata/vm-migration/vm/overlays/with-cvi/vd.image.patch.yaml, tests/e2e/testdata/vm-migration/vm/overlays/with-cvi/vm.bootloader.patch.yaml, tests/e2e/vm_migration_cancel_test.go
After mounting `CVI` and `VI` in read-only mode, we encountered a migration issue:  
"Operation not supported: Cannot migrate empty or read-only disk ..."
This fix ensures proper handling of disk mounting modes during migration to prevent the error.
```changes
section: kubevirt 
type: fix
summary: Fix VM migration with container disks (CVI, VI)
```
=> fix(kubevirt): Fix VM migration with container disks (CVI, VI)

images/virtualization-artifact/pkg/controller/vmclass/internal/deletion.go
Сorrectly remove the InUse condition when the VMClass is not used by any VM
```changes
section: vm
type: fix
summary: Сorrectly remove the InUse condition when the VMClass is not used by any VM
```
=> fix(vmclass): correctly remove the InUse condition when the VMClass is not used by any VM

images/cdi-controller/werf.inc.yaml, images/cdi-importer/werf.inc.yaml, images/dvcr-artifact/werf.inc.yaml, images/virt-handler/werf.inc.yaml, images/virt-launcher/werf.inc.yaml
Replacing statically build linux-utils in the following images:
- cdi-controller
- cdi-importer
- dvcr-artifact
- virt-handler
- virt-launcher
We want more control when building binary files, as well as making images more secure
```changes
section: core
type: chore
summary: replace linux-utils to self-build
```
=> chore(core): replace linux-utils to self-build

component_versions/version_map.yml, images/packages/binaries/glib2/werf.inc.yaml
Build glib2 library.
```changes
section: core
type: chore
summary: build glib2
```
=> chore(core): build glib2

component_versions/version_map.yml, images/packages/binaries/acl/werf.inc.yaml, images/virt-handler/werf.inc.yaml, images/virt-launcher/werf.inc.yaml
Build acl binary for virt-handler.
We want more control when building binaries files, as well as making images more secure
```changes
section: core
type: chore
summary: build acl
```
=> chore(core): build acl

images/virtualization-artifact/pkg/apiserver/registry/vm/rest/add_volume.go, images/virtualization-artifact/pkg/controller/kvbuilder/kvvm.go
Change VM behavior to I/O problems for disks.
Previously, the presence of I/O problems stopped the VM and paused it.
Now, instead of stopping the VM, I/O errors will be reported to the guest OS, allowing the guest system to deal with the problem (e.g., through retry mechanisms,
failover).
```changes
section: vm
type: feature
summary: Report I/O errors to guest OS instead of stopping VM, allowing the guest system to deal with the problem (e.g., through retry mechanisms, failover).
```
=> feat(vm):  set error policy report as default

tests/e2e/util_test.go
fix afterEach dump save for failed e2e tests.
```changes
section: ci
type: chore
summary: fix afterEach dump save for failed e2e tests.
```
=> chore(ci): fix afterEach dump save

images/packages/binaries/acl/werf.inc.yaml
acl is not yet compatible with -D_FORTIFY_SOURCE=3, see
https://savannah.nongnu.org/bugs/index.php?62519
```changes
section: core
type: fix
summary: fix build acl 
```
=> chore(core): fix acl

module.yaml
Update deckhouse requirements.
To enable virtual machine migration, a Deckhouse version of at least 1.68.14 is required.
```changes
section: module 
type: fix
summary: To enable virtual machine migration, a Deckhouse version of at least 1.68.14 is required.
```
=> fix(module): update deckhouse requirements

images/virtualization-artifact/pkg/controller/vd/internal/protection.go, images/virtualization-artifact/pkg/controller/vd/internal/protection_test.go
`vd-protection` will be removed from the virtual disk if the virtual machine is stopped.
This is necessary for the new feature, 'Restore Virtual Machine with Force Option.' Before restoring the virtual machine, it should be stopped to restore the virtual disk.
```changes
section: vd
type: feature
summary: "The `vd-protection` finalizer will be removed from the virtual disk if the virtual machine is stopped."
```
=> feat(vd): remove finalizer from unmounted vd

api/core/v1alpha2/vmcondition/condition.go, images/virtualization-artifact/pkg/controller/vm/internal/agent.go, images/virtualization-artifact/pkg/controller/vm/internal/agent_test.go, images/virtualization-artifact/pkg/controller/vm/internal/firmware.go, images/virtualization-artifact/pkg/controller/vm/internal/firmware_test.go, images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/migrating.go, images/virtualization-artifact/pkg/controller/vm/internal/migrating_test.go, images/virtualization-artifact/pkg/controller/vm/internal/size_policy.go, images/virtualization-artifact/pkg/controller/vm/internal/size_policy_test.go, images/virtualization-artifact/pkg/controller/vm/internal/snapshotting.go, images/virtualization-artifact/pkg/controller/vm/internal/snapshotting_test.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm_test.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_power_state_test.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go, images/virtualization-artifact/pkg/controller/vm/vm_controller.go
This PR refactors how Virtual Machine (VM) conditions are managed to provide more accurate and relevant status information. Key improvements include:
1. **Condition Cleanup**: Removed unused condition types `PodStarted` and simplified the condition set.
2. **Phase-Aware Conditions**:  
- Conditions are now dynamically shown/hidden based on the VM's phase (Running, Stopped, etc.)  
- Example: Agent conditions are hidden when VM is Pending/Starting/Stopped  
3. **Testing**: Added comprehensive unit tests for all condition-handling scenarios.
```changes
section: vm
type: fix
summary: Improve Status Reporting
```
=> fix(vm): add removing VM's conditions by design

images/virtualization-artifact/pkg/controller/livemigration/live_migration_reconciler.go, images/virtualization-artifact/pkg/livemigration/migration_configuration.go
fix live migration with image hotplug
```changes
section: vm 
type: fix
summary: fix live migration with image hotplug
```
=> fix(vm): fix live migration with image hotplug

images/virtualization-artifact/pkg/controller/cvi/internal/source/http.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vdsnapshot.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/cvi/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vd/internal/source/http.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_cvi.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vi_dvcr.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vi_pvc.go, images/virtualization-artifact/pkg/controller/vd/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vd/internal/source/upload.go, images/virtualization-artifact/pkg/controller/vi/internal/source/http.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vd.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref_vi_on_pvc.go, images/virtualization-artifact/pkg/controller/vi/internal/source/registry.go, images/virtualization-artifact/pkg/controller/vi/internal/source/upload.go
Fixed the requeue loss bug during VD/VI/CVI provisioning.
```changes
section: api
type: fix
summary: Fixed the requeue loss bug during VD/VI/CVI provisioning.
```
=> fix(api): fix reque while sync vd/vi/cvi state

images/hooks/cmd/discovery-clusterip-service-for-dvcr/main.go
trim quotes in discovered ClusterIP
```changes
section: vm 
type: fix
summary: trim quotes in discovered ClusterIP
```
=> fix(hooks): trim quotes in discovered ClusterIP

images/cdi-artifact/werf.inc.yaml
- Executing go mod vendor after patching in vendor directory revert such patches.
We have patch on json-patch/v5 in vendor directory. It reverts after go mod vendor.
```changes
section: cdi
type: chore
summary: Apply patches after go mod vendor.
```
=> chore(cdi): restore patching after go mod vendor

images/virtualization-artifact/pkg/controller/vmsnapshot/internal/watcher/vm_watcher.go
When the `VirtualMachine` is not ready for snapshotting because the agent is not ready, the `VirtualMachineSnapshot` stays in the `Pending` phase even after the agent becomes ready.
```changes
section: vmsnapshot
type: fix
summary: "The `VirtualMachineSnapshot` controller properly handles the agent status of the `VirtualMachine`."
```
=> fix(vmsnapshot): reconcile with vm agent ready status

images/virt-artifact/patches/052-add-tini-to-virt-launcher.patch, images/virt-artifact/patches/README.md, images/virt-launcher/werf.inc.yaml
This pr adds [`Tini`](https://github.com/krallin/tini ) as the primary entry point for the `virt-launcher` container.  
Tini is a minimal init system designed specifically for containers — it ensures proper reaping of zombie processes and forwards signals correctly to all child processes.
Now, `virt-launcher` starts like this:
```bash
/usr/bin/tini -- /usr/bin/virt-launcher-monitor [...]
```
This improves container reliability and helps prevent issues caused by leftover processes after virtual machine shutdown.
During normal operation, certain errors may occur that lead to incorrect termination of processes inside the virt-launcher container. As a result, orphaned or zombie processes can be left behind.
```changes
section: vm
type: feature
summary: Add Tini as the init process in …
```
=> feat(kubevirt): add tini to virt-launcher

images/virtualization-artifact/pkg/monitoring/metrics/virtualmachine/data_metric.go
`AwaitingRestartToApplyConfiguration`, `ConfigurationApplied`, `AgentReady` and `FirmwareUpToDate` conditions are no longer displayed to the user unless they contain an issue or some important message for the user. However, this change was not accounted for in the metrics. It's fixed in this pr.
```changes
section: vm 
type: fix
summary: Fix condition based metrics.
```
=> fix(vm): fix condition based metrics

crds/virtualmachines.yaml
Set max embedded cloud-init block size to 2048 bytes
It does't work for embedded cloud-init more than 2048 bytes
```changes
section: vm
type: fix
summary: Set max embedded cloud-init block size to 2048 bytes
```
=> fix(vm): set max embedded cloud-init block size

images/virtualization-artifact/pkg/controller/cvi/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vi/internal/source/object_ref.go, tests/e2e/default_config.yaml
Disable false positive error logs about not ready datasource.
```changes
section: images 
type: fix
summary: Disable false positive error logs about not ready datasource.
```
=> fix(images): disable false positive error logs about not ready datasource

component_versions/version_map.yml, images/packages/binaries/libaudit/werf.inc.yaml
Build libaudit library.
```changes
section: core
type: chore
summary: build libaudit
```
=> chore(ci): build libaudit

images/hooks/cmd/discovery-workload-nodes/main.go, images/hooks/werf.inc.yaml, openapi/values.yaml, templates/kubevirt/kubevirt.yaml
Set the default live migration parameters as follows:
- Migration bandwidth: 5 Gbps (approximately 640 MiB/s)
- Limit one outbound migration stream per node
- The total number of concurrent migrations in a cluster is limited to the number of nodes that are running virtual machines
Previously, the defaults were set to:
- 0.5 Gbps per migration
- 2 outbound migrations per node
- Maximum of 5 concurrent migrations cluster-wide
This setup could lead to several issues:
- Low per-migration bandwidth (0.5 Gbps) slowed down migration operations unnecessarily.
- Multiple outbound migrations per node (2) could cause network contention and resource starvation on the source node.
- Hard limit of 5 total migrations per cluster did not scale well with larger clusters and created bottlenecks during …
=> chore(core): set live migrations defaults

images/virtualization-artifact/pkg/controller/vm/internal/snapshotting.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/life_cycle.go
- In the vm controller, fix the view condition "Snapshotting" for snapshots in the "Failed" phase.
- In the vmsnapshot controller, add a check for requiredConsistency to determine if a freeze is needed. This will address the issue of creating snapshots in VMs that do not have a guest agent installed.
```changes
section: api
type: fix
summary: fix snapshotting process
```
=> fix(api): fix snapshotting process

images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm.go, images/virtualization-artifact/pkg/controller/vm/internal/sync_kvvm_test.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go
When the `VirtualDisk` is restored from the `VirtualDiskSnapshot`, its `PVC` changes and other components of the `VirtualMachine` can be changed too. This information must be updated in the `InternalVirtualizationVirtualMachine` specification.
```changes
section: vm
type: feature
summary: "The `InternalVirtualMachine` will be updated if the `VirtualMachine` is stopped."
```
=> feat(vm): update intvirtvm when vm is stopped

images/virt-artifact/werf.inc.yaml
Switch the project to a new tag of KubeVirt with static analyzer warnings resolved.
Fixed issues in virt-launcher:
- After having been compared to a nil value at rt_wrapper.go:45, pointer 'request.URL' is passed in call to function 'kubevirt.io/kubevirt/pkg/monitoring/metrics/common/client.parseURLResourceOperation' at rt_wrapper.go:49, where it is dereferenced at rt_wrapper.go:67.
- After having been compared to a nil value at client.go:455, pointer 'domainCache' is passed as 2nd parameter in call to function 'kubevirt.io/kubevirt/pkg/virt-launcher/notify-client.eventCallback' at client.go:447, where it is dereferenced at client.go:247.
- After having been compared to a nil value at manager.go:341, pointer 'vmi' is passed as 1st parameter in call to function …
=> chore(core): fix svacer issues in virt-launcher and virt-handler

api/core/v1alpha2/events.go, images/virtualization-artifact/pkg/controller/vmiplease/internal/lifecycle_handler.go, images/virtualization-artifact/pkg/controller/vmiplease/vmiplease_controller.go
Add events for the Bound and Released states of the VirtualMachineIPAddressLease.
```changes
section: core
type: feature
summary: Add events for the Bound and Released states of the VirtualMachineIPAddressLease.
```
=> feat(vmiplease): add events for Bound and Released states

api/core/v1alpha2/vmopcondition/condition.go, images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vmop/internal/lifecycle_test.go, images/virtualization-artifact/pkg/controller/vmop/internal/operation.go, images/virtualization-artifact/pkg/controller/vmop/internal/service/operation.go, images/virtualization-artifact/pkg/controller/vmop/vmop_controller.go
Improved phase handling for the `migrate` and `evict` operations:  
Previously, `vmop` would transition to `InProgress` as soon as the child migration resource was created.  
Now it remains in `Pending` state until the child resource actually starts executing.
Ensures predictable and ordered execution of VM operations, improving system stability and user experience.
Delays phase transition for `migrate` operations until actual execution starts, providing more accurate status tracking and better visibility into operation state.
```changes
section: vmop 
type: feature
summary: Improved phase handling for the `migrate` and `evict` operation
```
=> feat(vmop): improve phase handling for migrate operations

api/core/v1alpha2/cluster_virtual_image.go, api/core/v1alpha2/virtual_disk.go, api/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go, crds/clustervirtualimages.yaml, crds/virtualdisks.yaml
- Sync go source for VD: Use "PVCLost" as phase name for DiskLost phase.
Fixes for "CRD only changes":
- Sync go source for VD: change jsonpath for StorageClass column.
- Sync go source for CVI: add description to UsedInNamespaces fields.
Disk deletion is stuck after changes in #859. Phase was not used before, so we don't catch this problem earlier.
- Disk deletion is working.
- E2E tests are working.
```changes
section: disks
type: chore
summary: Fix const for PVCLost phase, sync Go sources and CRDs (VD, CVI).
```
=> chore(vd): fix phase name for PVCLost phase

templates/descheduler/descheduler.yaml
This PR introduces a descheduler component to automatically rebalance virtual machines (VMs) across cluster nodes. Functionality becomes active only when descheduler module is enabled
- Load-based rebalancing:
- Triggers when node CPU utilization exceeds 80%
- Uses `LowNodeUtilization` policy for balanced resource distribution
- Ensures even workload distribution across cluster nodes
- Affinity/anti-affinity compliance:
- Handles cases where nodes no longer meet `requiredDuringSchedulingIgnoredDuringExecution` rules
- Automatically migrates VMs to compliant nodes when placement constraints are violated
Without active rebalancing, uneven VM distribution can lead to node overutilization (e.g., CPU >80%), causing performance degradation, latency spikes, and potential node failures. 
Changes …
=> feat(core): introduces a descheduler component to automatically rebalance virtual machines (VMs) across cluster nodes

.gitignore, Taskfile.yaml, images/virt-api/debug/dlv.Dockerfile, images/virt-artifact/werf.inc.yaml, images/virt-controller/debug/dlv.Dockerfile, images/virt-handler/debug/dlv.Dockerfile
This PR adds support for hot-plugging PVCs in Filesystem mode in KubeVirt. If the expected disk image file (e.g., disk.img) is missing, KubeVirt will now create it automatically before attaching the volume to a running Virtual Machine.
https://github.com/deckhouse/3p-kubevirt/pull/3
```changes
section: vm
type: feature
summary: support hotplug of PVCs with filesystem volume mode
```
=> feat: support hotplug of PVCs with filesystem volume mode 

images/virtualization-artifact/pkg/controller/vd/internal/source/interfaces.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_cvi.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_cvi_test.go, images/virtualization-artifact/pkg/controller/vd/internal/source/step/create_dv_from_cvi_step.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go
Refactor the cvi data source using step-based design to fix the update of observed generation for a disk in the Ready state if the data source image was deleted.
```changes
section: vd  
type: fix
summary: Fix the update of observed generation for a disk in the Ready state if the data source image was deleted.
```
=> fix(vd): refactor object ref cvi data source

api/core/v1alpha2/finalizers.go, images/virtualization-artifact/pkg/controller/vm/internal/ipam.go
When deleting a virtual machine, the finalizer `vmip-protection` was not always removed from the vmip by vm controller in time. The vmip has its own finalizer `vmip-cleanup`, which prevents its deletion. 
To avoid refactoring the virtual machine's controller, finalizer `vmip-protection` has been deleted.
```changes
section: vmip
type: fix
summary: Fix the removal of the finalizer from VirtualMachineIPAddress when deleting a virtual machine.
```
=> fix(vm): remove vmip protection

images/virtualization-artifact/pkg/common/datavolume/util.go, images/virtualization-artifact/pkg/controller/vd/internal/watcher/pvc_watcher.go, images/virtualization-artifact/pkg/controller/vd/vd_reconciler.go
Enqueue requests from pvc's owner refs recursively
Previously, subscribing to a PVC might not have triggered disk reconciliation until an owner reference from the disk appeared on the PVC (and it only appears there at the very end of provisioning). If the PVC has an owner reference from a DataVolume, then the disk reconciliation would be lost. This PR fixes that issue.
```changes
section: vd
type: fix
summary: 
```
=> fix(vd): enqueue requests from pvc's owner refs recursively

templates/descheduler/descheduler.yaml, tools/kubeconform/fixtures/module-values.yaml, tools/kubeconform/kubeconform.sh
Use global values to check if descheduler CRD is known to deckhouse. lookup may be not reliable on transitional processes, i.e. deckhouse install, deckhouse restarts or module enabling.
Also add fixes to kubeconform script: delete unexpected metadata properties in descheduler CRDs before running kubeconform.
`lookup` checking leads to Deckhouse queue stuck on descheduler enabling.
We can enable and disable descheduler module without errors in the queue.
```changes
type: fix
summary:  Fix descheduler CRD checking in templates.
```
=> fix(core): fix discovery crd descheduler

api/core/v1alpha2/cluster_virtual_image.go, api/core/v1alpha2/virtual_disk.go, api/core/v1alpha2/virtual_image.go, crds/clustervirtualimages.yaml, crds/virtualdisks.yaml, crds/virtualimages.yaml, crds/virtualmachines.yaml, images/virtualization-artifact/pkg/common/validate/validate.go, images/virtualization-artifact/pkg/controller/cvi/cvi_webhook.go, images/virtualization-artifact/pkg/controller/vd/internal/validator/name_validator.go, images/virtualization-artifact/pkg/controller/vi/vi_webhook.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/meta_validator.go, tests/e2e/testdata/complex-test/cvi/cvi-from-cvi-ubuntu-http.yaml, tests/e2e/testdata/complex-test/cvi/cvi-from-vi-ubuntu-http.yaml, tests/e2e/testdata/connectivity/resources/vi.yaml, tests/e2e/testdata/connectivity/resources/vm-connectivity-a.yaml, tests/e2e/testdata/connectivity/resources/vm-connectivity-b.yaml, tests/e2e/testdata/cvi/cvi_containerimage.yaml, tests/e2e/testdata/images-creation/cvi/cvi_objectref_vi.yaml, tests/e2e/testdata/images-creation/vi/vi_objectref_vi.yaml, tests/e2e/testdata/images-creation/vi/vi_pvc_objectref_vi.yaml
Update name validation for VirtualImage, VirtualDisk, VirtualMachine, and ClusterVirtualImage to the actual length limit.
Actual length limits:
- VirtualMachine: 128 -> 63
- ClusterVirtualImage: 48 -> 36
- VirtualImage: 49 -> 37
Fixed inconsistency of name validations at the hook and crd levels.
```changes
section: api
type: fix 
summary: Update name validation for VirtualImage, VirtualDisk, VirtualMachine, and ClusterVirtualImage to the actual length limit.
```
=> fix(api): fix resource's names validation

images/virtualization-artifact/pkg/controller/service/size_policy_service.go, images/virtualization-artifact/pkg/controller/vmclass/internal/validators/sizing_policies_validator.go
Fix panic if Cores were not specified in the vmclass's SizingPolicy.
```changes
section: vm 
type: fix
summary: Fix panic if Cores were not specified in the vmclass's SizingPolicy.
```
=> fix(vm): nil pointer

images/virtualization-artifact/pkg/controller/service/restorer/restorer.go
A virtual machine block device attachment that has a reference to a virtual image must also be snapshotted.
A virtual machine block device attachment must be restored together with the virtual machine.
All virtual machine block device attachments from the virtual machine snapshot will be restored.
```changes
section: vmsnapshot
type: feature
summary: "All virtual machine block device attachment manifests are stored in the virtual machine snapshot when it is created."
```
=> feat(vmsnapshot): add hotplugged image manifests to snapshot

tests/e2e/default_config.yaml
The ignoring of the disk synchronization error message is being removed as the error is not reproducible.
```changes
section: vd
type: test
summary: "The ignoring of the disk synchronization error message is being removed as the error is not reproducible."
```
=> test(vd): remove pvc is exists error message ignoring

templates/cdi/config.yaml, templates/kubevirt/kubevirt.yaml, templates/virtualization-api/deployment.yaml, templates/virtualization-controller/deployment.yaml
Every component which is run on master nodes should have at least 3 replicas and run on separate masters. Every other component should have 2 replicas.
This is a useful feature for HA, because, firstly, sometimes masters can be unavailable, and this saves time on deployment of new pods, and secondly, this evens out load on multiple masters, because some replicas of the same deployment can be leaders on non-leader etcd master node.
In HA mode we should see this picture.
3 replicas of following components:
- cdi-apiserver
- virt-api
- virtualization-api
- virtualization-controller
and 2 replicas of other components.
```changes
section: core
type: feature
summary: set replicas equal to 3 for HA mode
```
=> feat(core): set replicas equal to 3 for HA mode

images/virt-launcher/werf.inc.yaml
Add vlctl and node-labeller to svace.
```changes
```
=> chore(ci): add vlctl and node-labeller to svace

images/virtualization-artifact/pkg/config/load_dvcr_settings.go, images/virtualization-artifact/pkg/controller/uploader/uploader_ingress.go, templates/virtualization-controller/_helpers.tpl
Fix validation logic related to the `https.mode` field in the virtualization module settings, ensuring that the UPLOADER_INGRESS_TLS_SECRET is only required when the HTTPS mode is 'CertManager' or 'CustomCertificate'.
If the `https.mode` field in the module settings is set to `OnlyInURI`, we get an error:
```
1. ModuleRun:main:virtualization:KubeConfig-Changed-Modules:failures 1:run helm install: execution error at (virtualization/templates/virtualization-controller/deployment.yaml:96:16): https.mode must be CustomCertificate or CertManager
```
```changes
type: fix
summary: Fix validation logic related to the https.mode field in the virtualization module settings, ensuring that the UPLOADER_INGRESS_TLS_SECRET is only required when the HTTPS mode is …
```
=> fix(module): fix validating for field https.mode

images/virt-artifact/werf.inc.yaml
bump kubevirt to "v1.3.1-v12n.5" 
- increase max length for hotplug containerDisk volumes
https://github.com/deckhouse/3p-kubevirt/pull/7
- drop openshift labels from controller namespace
https://github.com/deckhouse/3p-kubevirt/pull/5
```changes
section: core
type: fix
summary: Increase max length for hotplug containerDisk volumes. Drop openshift labels from controller namespace
```
=> chore: bump kubevirt to v1.3.1-v12n.5

images/virtualization-artifact/pkg/common/validate/validate.go
Fix name validation for VirtualImage and ClusterVirtualImage to the actual length limit.
Actual length limits:
ClusterVirtualImage: 36 -> 48
VirtualImage: 37 -> 49
```changes
section: images
type: fix 
summary: |
The allowed name lengths for resources have been adjusted and the corresponding validation has been added:
- VirtualMachine: 63 characters
- ClusterVirtualImage: 48 characters
- VirtualImage: 49 characters
- VirtualDisk: 60 characters
```
=> fix(images): fix names validation for images

api/core/v1alpha2/virtual_machine_block_device_attachment.go, crds/virtualmachineblockdeviceattachments.yaml
add columns whit blockdevice kind and name for wide output
```changes
section: vmbda
type: chore
summary: add columns whit blockdevice kind and name for wide output
```
=> chore(vmbda): add columns with blockdevice kind and name for wide output

src/cli/cmd/main.go, src/cli/go.mod, src/cli/go.sum, src/cli/internal/clientconfig/clientconfig.go, src/cli/internal/cmd/console/console.go, src/cli/internal/cmd/lifecycle/evict.go, src/cli/internal/cmd/lifecycle/lifecycle.go, src/cli/internal/cmd/lifecycle/restart.go, src/cli/internal/cmd/lifecycle/start.go, src/cli/internal/cmd/lifecycle/stop.go, src/cli/internal/cmd/lifecycle/vmop/vmop.go, src/cli/internal/cmd/portforward/portforward.go, src/cli/internal/cmd/scp/native.go, src/cli/internal/cmd/scp/scp.go, src/cli/internal/cmd/ssh/native.go, src/cli/internal/cmd/ssh/ssh.go, src/cli/internal/cmd/vnc/vnc.go, src/cli/pkg/command/virtualization.go
add common clientconfig
```changes
section: cli
type: refactor
summary: add clientconfig
```
=> refactor(cli): add common clientconfig

images/virtualization-artifact/pkg/controller/service/base_storage_class_service.go, images/virtualization-artifact/pkg/controller/vd/internal/interfaces.go, images/virtualization-artifact/pkg/controller/vd/internal/mock.go, images/virtualization-artifact/pkg/controller/vd/internal/storageclass_ready.go, images/virtualization-artifact/pkg/controller/vd/internal/storageclass_ready_test.go, images/virtualization-artifact/pkg/controller/vd/internal/validator/spec_changes_validator.go, images/virtualization-artifact/pkg/controller/vd/vd_controller.go, images/virtualization-artifact/pkg/controller/vd/vd_webhook.go, images/virtualization-artifact/pkg/controller/vi/internal/interfaces.go, images/virtualization-artifact/pkg/controller/vi/internal/mock.go, images/virtualization-artifact/pkg/controller/vi/internal/storageclass_ready.go, images/virtualization-artifact/pkg/controller/vi/internal/storageclass_ready_test.go, images/virtualization-artifact/pkg/controller/vi/vi_controller.go, images/virtualization-artifact/pkg/controller/vi/vi_webhook.go
For `VirtualDisk` and `VirtualImage` creation.
Support for storage classes managed by the local-path-provisioner module has been discontinued.
```changes
section: api
type: feature
summary: "The storage classes managed by the `local-path-provisioner` module are now deprecated for VirtualImage and VirtualDisk creation."
```
=> feat(api): deprecate the local-path-provisioner

images/cdi-artifact/werf.inc.yaml, images/cdi-cloner/werf.inc.yaml, images/virt-launcher/werf.inc.yaml
Add self-written components (cloner-startup, hello, temp_pod) to svace.
```changes
section: ci
type: chore 
summary: add self-written components to svace
```
=> chore(ci): add self-written components to svace

images/virt-artifact/werf.inc.yaml
Fix hotplug volumes in filesystem mode
Bump kubevirt version to v1.3.1-v12n.6
- https://github.com/deckhouse/3p-kubevirt/pull/8
To reduce the number of dependencies in the container by removing unnecessary binaries like findmnt.
Using the github.com/moby/sys/mountinfo library achieves the same functionality without external commands.
```changes
section: vm
type: fix
summary: Fix hotplug volumes in filesystem mode
```
=> fix(kubevirt): fix hotplug volumes in filesystem mode, bump kubevirt version to v1.3.1-v12n.6

images/virt-artifact/werf.inc.yaml, images/virt-launcher/werf.inc.yaml
support vpc and read-only containers
bump kubevirt version to v1.3.1-v12n.7 
- https://github.com/deckhouse/3p-kubevirt/pull/10
- https://github.com/deckhouse/3p-kubevirt/pull/9
```changes
section: core
type: feature
summary: support vpc and read-only containers, bump kubevirt version to v1.3.1-v12n.7
```
=> feat(kubevirt): support vpc and read-only containers, bump kubevirt version to v1.3.1-v12n.7

images/hooks/cmd/virtualization-module-hooks/register.go, images/hooks/pkg/hooks/drop-openshift-labels/hook.go, images/hooks/pkg/hooks/drop-openshift-labels/hook_test.go
Add hook for drop openshift labels from module namespace (d8-virtualization)
```changes
type: feature
summary:  Add hook for drop openshift labels from module namespace (d8-virtualization)
```
=> feat(core): add hook for drop openshift labels from module namespace (d8-virtualization)

.github/workflows/dev_module_build.yml, tests/e2e/Taskfile.yaml
Fix run e2e if audit disabled
```changes
section: ci
type: chore
summary: fix run e2e if audit disabled
```
=> fix(ci): fix run e2e if audit disabled

images/base-alt-p11/werf.inc.yaml, images/edk2/werf.inc.yaml, images/libvirt/werf.inc.yaml, images/qemu/werf.inc.yaml, images/virt-artifact/werf.inc.yaml
- virt-artifact image adds "nonroot" group and user to the passwd file explicitly.
- qemu, libvirt, and edk2 images are not needed "nonroot" group and user.
```changes
section: ci
type: chore
summary: drop transient image base-alt-p11, use builder/alt directly
```
=> chore(ci): drop transient image base-alt-p11, use builder/alt directly

images/virtualization-artifact/pkg/controller/service/base_storage_class_service.go, images/virtualization-artifact/pkg/controller/vd/internal/interfaces.go, images/virtualization-artifact/pkg/controller/vd/internal/mock.go, images/virtualization-artifact/pkg/controller/vd/internal/storageclass_ready.go, images/virtualization-artifact/pkg/controller/vd/internal/storageclass_ready_test.go, images/virtualization-artifact/pkg/controller/vd/internal/validator/spec_changes_validator.go, images/virtualization-artifact/pkg/controller/vi/internal/interfaces.go, images/virtualization-artifact/pkg/controller/vi/internal/mock.go, images/virtualization-artifact/pkg/controller/vi/internal/storageclass_ready.go, images/virtualization-artifact/pkg/controller/vi/internal/storageclass_ready_test.go, images/virtualization-artifact/pkg/controller/vi/vi_webhook.go
Update the IsStorageClassDeprecated method to accept a StorageClass pointer instead of a string.  Adjust related mock implementations and tests accordingly. Fix linter errors.
This change improves type safety and reduces the need for additional lookups.
```changes
section: api
type: chore
summary: Update the IsStorageClassDeprecated method to accept a StorageClass pointer instead of a string.
```
=> refactor(api): simplify IsStorageClassDeprecated method signature

images/virt-artifact/werf.inc.yaml
bump kubevirt to tag v1.3.1-v12n.8
- Set mac address for non default pod network
https://github.com/deckhouse/3p-kubevirt/pull/12
- Improve reason when live-migration failed
https://github.com/deckhouse/3p-kubevirt/pull/11
```changes
section: core
type: feature
summary: bump kubevirt to tag v1.3.1-v12n.8. Set mac address for non default pod network and improve reason when live-migration failed
```
=> feat: bump kubevirt to tag v1.3.1-v12n.8

images/virtualization-artifact/pkg/controller/vm/internal/validators/networks_validator.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/networks_validator_test.go
- Fix an issue where multiple networks of type "Main" could be specified in a virtual machine's spec.
```changes
section: vm
type: fix
summary: Fix an issue where multiple networks of type "Main" could be specified in a virtual machine's spec.
```
=> fix(vm): fix networks validator

templates/custom-certificate.yaml
Override helm_lib_module_https_copy_custom_certificate template from the helm-lib, add base64 for Secret fields.
Fix of regression after rewrite copy_custom_certificate in Go. helm-lib expects base64 encoded certificates in values, but common hook returns raw strings.
Custom certificate specified in ModuleConfig/global in spec.settings.modules.https.customCertificate.secretName leads to this error:
```
helm upgrade failed: cannot patch "ingress-tls-customcertificate" with kind Secret ... invalid value: "{ ... \"data\":{\"tls.crt\":\"-----BEGIN CERTIFICATE----....
```
```changes
type: fix
summary: Fix helm template to be compatible with CustomCertificate https mode.
```
=> fix(module): base64 encoding for custom certificate Secret template

module.yaml
Up minimal version of Deckhouse for better compatibility with snapshot-controller. 1.70 required for correct setting volumeSnapshotClassName.
```changes
type: chore
summary: Up minimal version of Deckhouse for better compatibility with snapshot-controller. 1.70 required for correct setting volumeSnapshotClassName.
```
=> chore(module): up Deckhouse min. version

api/core/v1alpha2/vdcondition/condition.go, images/virtualization-artifact/pkg/controller/vd/internal/datasource_ready.go, images/virtualization-artifact/pkg/controller/vd/internal/datasource_ready_test.go, images/virtualization-artifact/pkg/controller/vd/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vd/internal/life_cycle_test.go, images/virtualization-artifact/pkg/controller/vd/internal/source/errors.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_cvi.go, images/virtualization-artifact/pkg/controller/vd/internal/source/object_ref_vi.go
Enhance error handling and condition propagation to clearly indicate in the DatasourceReady and Ready conditions when a referenced VirtualImage or ClusterVirtualImage is not found, distinguishing from "not ready" cases.
This resolves misleading status where missing images were treated generically as "not ready", providing explicit "not found" messaging.
```changes
section: vd
type: fix
summary: Set ImageNotReady/ClusterImageNotReady condition when VI/CVI is missing.
```
=> fix(vd): improve Ready condition for missing VirtualImage references

images/virtualization-artifact/pkg/audit/events/vm/vm_access.go, images/virtualization-artifact/pkg/audit/events/vm/vm_access_test.go
Improve VM Access audit messages. Add stage from audit message to eventLog name.
At the moment it is not clear at what stage the request comes when connecting via port-forward, as well as when connecting via console and vnc.
Add stage status of request from event message.
```changes
type: fix 
summary: Improve VM Access audit messages. Add stage from audit message to eventLog name.
```
=> fix(audit): improve VM Access message

images/virtualization-artifact/pkg/controller/conditions/getter.go, images/virtualization-artifact/pkg/controller/vm/internal/lifecycle.go, images/virtualization-artifact/pkg/controller/vm/internal/util.go, images/virtualization-artifact/pkg/controller/vm/internal/watcher/kvvm_watcher.go
Prevent "Starting" hang when quota is exceeded.
```changes
section: vm
type: fix
summary: Prevent "Starting" hang when quota is exceeded.
```
=> fix(vm): prevent "Starting" hang when quota is exceeded

images/virtualization-artifact/pkg/controller/moduleconfig/moduleconfig_webhook.go, images/virtualization-artifact/pkg/controller/moduleconfig/vi_storageclass_validator.go, images/virtualization-artifact/pkg/controller/service/base_storage_class_service.go, images/virtualization-artifact/pkg/controller/vi/internal/interfaces.go, images/virtualization-artifact/pkg/controller/vi/internal/mock.go, images/virtualization-artifact/pkg/controller/vi/internal/service/vi_storage_class_service.go, images/virtualization-artifact/pkg/controller/vi/internal/service/vi_storage_class_service_test.go, images/virtualization-artifact/pkg/controller/vi/internal/storageclass_ready.go, images/virtualization-artifact/pkg/controller/vi/internal/storageclass_ready_test.go, images/virtualization-artifact/pkg/controller/vi/vi_webhook.go
Currently, only storage classes with Block volume mode and RWX access mode can be used.
This is required until the problem with the Filesystem volume mode is resolved.
```changes
section: vi
type: chore
summary: "Currently, only storage classes with Block volume mode and RWX access mode can be used."
```
=> fix(vi): validate storage class

images/libvirt/werf.inc.yaml, images/packages/gnutls/werf.inc.yaml, images/packages/libattr/werf.inc.yaml, images/packages/libblkid/werf.inc.yaml, images/packages/libbrotli/werf.inc.yaml, images/packages/libbsd/werf.inc.yaml, images/packages/libburn/werf.inc.yaml, images/packages/libfuse3/werf.inc.yaml, images/packages/libgcrypt/werf.inc.yaml, images/packages/libgmp/werf.inc.yaml, images/packages/lvm2/werf.inc.yaml, images/qemu/werf.inc.yaml
Enable packages for deckhouse embeded build
```changes
section: core
type: fix
summary: enable packages for deckhouse embeded build
```
=> chore(core): enable packages for deckhouse embeded build

images/virtualization-artifact/pkg/controller/vm/internal/watcher/kvvm_watcher.go
Without this, when VMBDA is in the deletion process, it gets stuck in the terminating phase because a stopped VM cannot update block device references during this phase.
A VMBDA should be correctly deleted when a VM is in the stopped phase.
```changes
section: vm
type: fix
summary: "A VMBDA should be correctly deleted when a VM is in the stopped phase."
```
=> fix(vm): watch for kvvm volume snapshot statuses

images/virtualization-artifact/pkg/controller/vdsnapshot/internal/life_cycle.go
The VirtualDiskSnapshot changes its status to Failed if the VirtualDisk is simultaneously attached to another VirtualMachine after a successful snapshotting process.
The VirtualDiskSnapshot retains its Ready status even if the VirtualDisk is simultaneously attached to another VirtualMachine after a successful snapshotting process.
```changes
section: vdsnapshot
type: fix
summary: "The VirtualDiskSnapshot retains its Ready status even if the VirtualDisk is simultaneously attached to another VirtualMachine after a successful snapshotting process."
```
=> fix(vdsnapshot): fix multiple vm attachment check

crds/virtualmachines.yaml
Make provisioning type spec field required.
Unspecified type leads to an error.
```changes
section: vm
type: fix
summary: Make provisioning type spec field required.
```
=> fix(vm): make provisioning type spec field required

tests/e2e/default_config.yaml
Remove unused error filter from e2e logs filter.
```changes
```
=> chore(api): remove not used error filter

api/core/v1alpha2/virtual_machine_ip_address_lease.go, images/virtualization-artifact/pkg/controller/vmrestore/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vmrestore/internal/restorer/vd_restorer.go, images/virtualization-artifact/pkg/controller/vmrestore/internal/restorer/vm_restorer.go, images/virtualization-artifact/pkg/controller/vmrestore/internal/restorer/vmbda_restorer.go, images/virtualization-artifact/pkg/controller/vmrestore/internal/restorer/vmip_restorer.go, tests/e2e/README.md, tests/e2e/Taskfile.yaml, tests/e2e/config/config.go, tests/e2e/default_config.yaml, tests/e2e/kubectl/kubectl.go, tests/e2e/testdata/vm-restore-safe/kustomization.yaml, tests/e2e/testdata/vm-restore-safe/ns.yaml, tests/e2e/testdata/vm-restore-safe/transformer.yaml, tests/e2e/testdata/vm-restore-safe/vi/kustomization.yaml, tests/e2e/testdata/vm-restore-safe/vi/vi-alpine-http.yaml, tests/e2e/testdata/vm-restore-safe/vi/vi-ubuntu-http.yaml, tests/e2e/testdata/vm-restore-safe/vm/base/cfg/cloudinit.yaml, tests/e2e/testdata/vm-restore-safe/vm/base/kustomization.yaml, tests/e2e/testdata/vm-restore-safe/vm/base/transformer.yaml, tests/e2e/testdata/vm-restore-safe/vm/base/vd-blank.yaml, tests/e2e/testdata/vm-restore-safe/vm/base/vd-root.yaml, tests/e2e/testdata/vm-restore-safe/vm/base/vm.yaml, tests/e2e/testdata/vm-restore-safe/vm/base/vmbda-vd.yaml, tests/e2e/testdata/vm-restore-safe/vm/base/vmbda-vi.yaml, tests/e2e/testdata/vm-restore-safe/vm/kustomization.yaml, tests/e2e/testdata/vm-restore-safe/vm/overlays/vm/kustomization.yaml, tests/e2e/vm_restore_safe_test.go
Resource validation works properly when a virtual machine is restored in Safe mode.
```changes
section: vmrestore
type: fix
summary: "Resource validation works properly when a virtual machine is restored in Safe mode."
```
=> fix(vmrestore): fix validation in safe mode

src/cli/.golangci.yaml, src/cli/Taskfile.yaml, src/cli/internal/cmd/console/console.go, src/cli/internal/cmd/lifecycle/lifecycle.go, src/cli/internal/cmd/portforward/portforward.go, src/cli/internal/cmd/portforward/portforwarder.go, src/cli/internal/cmd/scp/native.go, src/cli/internal/cmd/ssh/knownhosts.go, src/cli/internal/cmd/ssh/native.go, src/cli/internal/cmd/ssh/terminal_unix.go, src/cli/internal/cmd/ssh/wrapped.go, src/cli/internal/cmd/vnc/vnc.go, src/cli/internal/templates/target.go, src/cli/internal/templates/templates.go, src/cli/internal/util/consts.go, src/cli/pkg/command/virtualization.go
lint cli d8v
```changes
section: core
type: chore 
summary: lint cli d8v
```
=> chore: lint cli d8v

tests/e2e/errlogger/errlogger.go
Increase buffer size for log parser.
A scan error occurs when the virtualization controller log level is set to debug.
```
[FAILED] in [It] - /username/virtualization/tests/e2e/errlogger/errlogger.go:198 @ 08/26/25 09:45:02.748
• [FAILED] [16.971 seconds]
ComplexTest When virtualization resources are applied [It] result should be succeeded [Serial]
/username/virtualization/tests/e2e/complex_test.go:59
[FAILED] failed to scan the "STDOUT" stream)
Unexpected error:
<*errors.errorString | 0x5d56870>:
bufio.Scanner: token too long
{
s: "bufio.Scanner: token too long",
}
occurred
In [It] at: /username/virtualization/tests/e2e/errlogger/errlogger.go:198 @ 08/26/25 09:45:02.748
```
No errors.
```changes
section: test
type: fix
summary: increase buffer size for local e2e run when loglevel is …
```
=> fix(test): increase buffer size for log parser

images/virtualization-artifact/pkg/controller/service/restorer/keys.go, images/virtualization-artifact/pkg/controller/service/restorer/restorer.go, images/virtualization-artifact/pkg/controller/vmrestore/internal/interfaces.go, images/virtualization-artifact/pkg/controller/vmrestore/internal/life_cycle.go, images/virtualization-artifact/pkg/controller/vmrestore/internal/mock.go, images/virtualization-artifact/pkg/controller/vmrestore/internal/restorer/vmmac_restorer.go, images/virtualization-artifact/pkg/controller/vmsnapshot/internal/life_cycle.go
This PR enhances the snapshot and restore functionality by including VirtualMachineMACAddress resources.   
- VirtualMachineMACAddress is now captured in snapshots.  
- During restore, VirtualMachineMACAddress resources are properly recreated to ensure network configuration consistency.
```changes
section: vm
type: feature
summary: Add support for including VirtualMachineMACAddress resources in snapshots and restores them during the recovery process to preserve network configuration and ensure consistent VM network identity.
```
=> feat(vm): add mac in snapshots and restore

api/core/v1alpha2/virtual_machine_mac_address_lease.go, images/virtualization-artifact/pkg/apiserver/api/generated/openapi/zz_generated.openapi.go
Fix the typo in VirtualMachineMACAddressLease struct.
=> fix(vmmaclease): fix the typo in VirtualMachineMACAddressLease struct

tests/e2e/vm_restore_force_test.go, tests/e2e/vm_restore_safe_test.go
- Forced: Disable VM status check until the issue with the runPolicy is fixed.
- Safe: Use Virtual Machine GVK instead of short name.
```changes
section: vmrestore
type: fix
summary: "This fix VMRestore end-to-end tests."
```
=> test(vmrestore): fix vmrestore end-to-end tests

images/dvcr-artifact/pkg/registry/registry.go, images/dvcr-artifact/pkg/registry/tar.go, templates/dvcr/ nodegroupconfiguration.yaml
- Support containerd v2 config layout: change NGC with dvcr registry.
- Support erofs tar unpacking: erofs strictly requires end-of-file tar marker.
- Fix creation time and add common fields in generated DVCR images manifests.
CVI/VI attaching to VM not working properly with containerd v2 and erofs:
```
NAME                                                                 PHASE     NODE           IPADDRESS    AGE
virtualmachine.virtualization.deckhouse.io/cloud-alpine-eros-fail    Pending                  10.66.10.3   16m
NAME                                              READY   STATUS                  RESTARTS   AGE
pod/virt-launcher-cloud-alpine-eros-fail-7h5z4    0/2     Init:ImagePullBackOff   0          49s
Event from kubectl describe:
Warning    Failed   12s                kubelet …
```
=> feat(core): add dvcr config for containerd v2

images/virtualization-artifact/pkg/controller/vm/internal/network.go, images/virtualization-artifact/pkg/controller/vm/internal/network_test.go
Add display of `.status.network` if `.spec.network` is empty.
```changes
section: vm
type: fix
summary:  Add display of `.status.network` if `.spec.network` is empty
```
=> fix(vm): add display of `.status.network` if `.spec.network` is empty

images/virtualization-artifact/pkg/controller/vm/internal/network.go
Fix message in NetworkReady condition:
- when module SDN don't set annotation with network status data
- when vm pods not exist
Message "Annotation %s is not found" is not clear to the user.
```changes
section: vm
type: fix
summary: fix message in NetworkReady condition
```
=> fix(vm): fix message in `NetworkReady` condition

images/virtualization-artifact/pkg/builder/cvi/cvi.go, images/virtualization-artifact/pkg/builder/cvi/option.go, images/virtualization-artifact/pkg/builder/vd/option.go, images/virtualization-artifact/pkg/builder/vd/vd.go, images/virtualization-artifact/pkg/builder/vi/option.go, images/virtualization-artifact/pkg/builder/vi/vi.go, images/virtualization-artifact/pkg/builder/vm/option.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/first_block_device_validator.go, images/virtualization-artifact/pkg/controller/vm/internal/validators/first_block_device_validator_test.go, images/virtualization-artifact/pkg/controller/vm/vm_webhook.go, tests/e2e/testdata/vm-versions/kustomization.yaml, tests/e2e/testdata/vm-versions/vd/kustomization.yaml, tests/e2e/testdata/vm-versions/vd/vd-root.yaml, tests/e2e/testdata/vm-versions/vm/vm.yaml, tests/e2e/vm_version_test.go
If first block device in spec of VirtualMachine is VirtualImage or ClusterVirtualImage, it must be iso. Added a webhook for this.
```changes
section: vm
type: chore
summary: Check is first block device bootable.
```
=> chore(vm): check is first block device bootable

tests/e2e/default_config.yaml
Simplify regex for catching error messages with empty slice of IPs
```IP address (10.66.10.32) is not among addresses assigned to 'default' network interface ()```
```changes
section: test
type: chore
summary: simplify regex for catching error messages with empty slice of IPs.
```
=> chore(e2e): fix IPAM error

tests/e2e/Taskfile.yaml, tests/e2e/task_run_ci.sh
The `run:ci` script should be executed from within the script itself to avoid issues with shell processing on a GitHub runner.
```changes
section: ci
type: fix
summary: "The `run:ci` script should be executed from within the script itself to avoid issues with shell processing on a GitHub runner."
```
=> test(ci): extract e2e-run-ci script from taskfile

tests/e2e/tests_suite_test.go
Errors in test cases should not stop the Ginkgo process.
```changes
section: api
type: fix
summary: "Errors in test cases should not stop the Ginkgo process."
```
=> test: replace log fatal with ginkgo expect

images/hooks/pkg/hooks/discovery-clusterip-service-for-dvcr/hook.go, images/hooks/pkg/hooks/discovery-workload-nodes/hook.go, openapi/values.yaml, templates/kubevirt/_kubevirt_helpers.tpl, templates/kubevirt/kubevirt.yaml, tools/kubeconform/fixtures/module-values.yaml
- Run discover cluster IP hook before TLS certificate generator for DVCR hook.
- Set updated value for parallelMigrationsPerCluster if kubevirt config is Deployed.
1. Running discover hook before certificate generator leads to helm template render error and unnecessary restart:
```
1. ModuleRun:parallel_queue_1:virtualization:doStartup:OperatorStartup:failures 1:
run helm install: template: virtualization/templates/dvcr/secret.yaml:12:20:
executing "virtualization/templates/dvcr/secret.yaml" at <.Values.virtualization.internal.dvcr.cert.ca>:
nil pointer evaluating interface {}.ca
```
3. Updating `parallelMigrationsPerCluster` to virt-handler nodes adds more restarts during kubevirt deploy process with errors like this:
```
run helm install: helm upgrade failed: cannot patch "config" with …
```
=> chore(module): reduce module restarts during installation

images/packages/glib2/werf.inc.yaml
Fix build glib2 for a closed environment
```changes
section: core
type: chore
summary: Enable build glib2 in closed environment.
```
=> chore(core): fix build glib2

docs/internal/cdi_kubevirt_patching.md
Remove from english documentation cyrillic characters
English documentation should not contains cyrillic characters
```
[cyrillic-in-english (#documentation)]
Message:      English documentation contains cyrillic characters
Module:       virtualization
Value:        Line 65: #### Сlean
-----^
Line 97: #### Сlean
-----^
FilePath:     docs/internal/cdi_kubevirt_patching.md
```
```changes
section: docs
type: fix
summary: english documentation remove cyrillic characters cdi_kubevirt_patching
```
=> fix(docs): english documentation remove cyrillic characters cdi_kubevirt_patching

tests/e2e/default_config.yaml, tests/e2e/vm_restore_force_test.go, tests/e2e/vm_restore_safe_test.go
- Skip test if forced restoration fails with the virtual machine in the pending phase.
- Skip annotation and label checks.
- Skip MAC address checks.
These bugs are currently known, and nightly end-to-end tests should not fail for the related cases.
Nightly end-to-end tests should not fail due to known errors.
```changes
section: api
type: chore
summary: "Nightly end-to-end tests should not fail due to known errors."
```
=> test(vmrestore): disable checks until issues are fixed

build/components/versions.yml, monitoring/grafana-dashboards/main/virtual-machine.json, templates/kubevirt/service-monitor.yaml
- Remove metric replacement rule to always set network label with "default" value
- Add kubevirt patch to set network name from annotation.
Supporting PR: [3p-kubevirt #22 feat(metrics): add network label with network name](https://github.com/deckhouse/3p-kubevirt/pull/22)
Given this specs:
```
networks:
- type: Main
- name: test-vlan-540
type: Network
- name: test-vlan-542
type: Network
```
Before: only "default" network is shown:
After:
Network bandwidth is summed for all networks:
Graph contains separate lines for each network specified in the VM spec.
```changes
section: observability
type: feature
summary: Repeat "Network details" graphs for all networks specified in the VM spec.
```
=> chore(module): add network label with network name

images/virtualization-artifact/pkg/controller/vm/internal/block_device_condition.go
Fix the case when a disk in the "Terminating" phase was being added to volumes during a restore operation in Strict mode.
During restore, the VM captured the PVC from the old disk, which was in the Terminating phase.
The VM should wait until the new restored disk becomes available and then capture its restored PVC. 
```changes
section: vmop
type: fix
summary: Fix the case when a disk in the "Terminating" phase was being added to volumes during a restore operation in Strict mode.
```
=> fix(vmop): fix restore operation in Strict mode

api/client/kubeclient/client.go, api/client/kubeclient/config.go, src/cli/internal/comp/namespace.go, src/cli/internal/comp/virtualmachine.go, src/cli/pkg/command/virtualization.go
add virtual machine name and namespace flag completions
```changes
section: core
type: feature
summary: add virtual machine name and namespace flag completions to cli
```
=> feat(cli): add virtual machine name and namespace flag completions

werf.yaml
remove internal docs from module images
```changes
type: chore 
summary: remove internal docs from module images
```
=> chore(module): remove internal docs from module images

tests/e2e/util_test.go
Add volumesnapshot resources to e2e fail dump.
```changes
section: core
type: feature
summary: Add volumesnapshot resources to e2e fail dump.
```
=> feat(core): add volumesnapshot resources to e2e fail dump

tests/e2e/vm_label_annotation_test.go
Do not wait agent in label and annotation test.
```changes
section: api
type: feature
summary: Do not wait agent in label and annotation test.
```
=> test: do not wait agent in label and annotation test

.github/workflows/nightly_e2e_tests_ceph.yaml, tests/e2e/framework/client.go
This PR fixes a typo in the Go tools installation command within the nightly E2E workflow.
**Before:** `go tool install` (incorrect, this command does not exist)
**After:** `go install tool` (correct command for installing tools)
The previous command (`go tool install`) was invalid and likely caused the tool installation step to fail. The correct command is `go install tool`.
This ensures that the necessary dependencies are properly installed for the nightly end-to-end tests.
=>  fix: Correct Go tools installation command in nightly E2E workflow

tests/e2e/default_config.yaml
Ignore the following error on e2e tests.
`failed to sync migrating volumes: admission webhook "virtualmachine-validator.kubevirt.io" denied the request: spec.template.spec.domain.devices.disks`
To remove noise from tests.
No errors of that kind in Ginkgo output.
=> chore(ci): ignore specific error on e2e tests

tests/e2e/testdata/vm-restore-force/vm/overlays/vm-exists-always-on/kustomization.yaml, tests/e2e/testdata/vm-restore-force/vm/overlays/vm-exists/kustomization.yaml, tests/e2e/testdata/vm-restore-safe/vm/overlays/vm/kustomization.yaml
This change is required to prevent potential conflicts between Automatic mode and VMOP restart.
```changes
section: api
type: chore
summary: "This change is required to prevent potential conflicts between Automatic mode and VMOP restart."
```
=> test(vmrestore): change restart approval mode

images/virtualization-artifact/pkg/builder/vd/option.go, images/virtualization-artifact/pkg/builder/vm/option.go, tests/e2e/framework/framework.go, tests/e2e/object/vd.go, tests/e2e/util_test.go, tests/e2e/vm_live_migration_tcp_session_test.go
The new migration test case has been added.
```changes
section: api
type: chore
summary: "The new migration test case has been added."
```
=> test(vm): check TCP connection during VM migration

images/packages/p11-kit/werf.inc.yaml, images/virt-launcher/mount-points.yaml
- Fix /var/log/libvirt mount point in virt-launcher image to run it as node-labeller.
- Fix build for p11-kit: rewrite for submodule.
```
kubectl describe po virt-handler-...
Warning  Failed     28m (x5 over 29m)   kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: 
unable to start container process: error during container init: 
error mounting "/var/lib/kubelet/pods/9d576643-8f00-4d97-9d17-af45c5c0bdca/volumes/kubernetes.io~empty-dir/var-log-node-labeller" to rootfs at "/var/log/libvirt": create mountpoint for /var/log/libvirt mount:
mkdir at /run/containerd/io.containerd.runtime.v2.task/k8s.io/virt-launcher/rootfs/var/log/libvirt: read-only file system
```
Module works in the strict environment.
=> chore(core): fix run with ro rootfs

tests/e2e/vm_live_migration_tcp_session_test.go
Skip VirtualMachineLiveMigrationTCPSession test
=> chore: skip VirtualMachineLiveMigrationTCPSession test

tests/e2e/vd_snapshots_test.go
Skip VDSnapshot blinking error.
=> chore: skip vd snapshots blinking error

images/dvcr-artifact/pkg/retry/backoff.go
Promote vd/vi import error if url is broken.
Right now, if the HTTP source returns an error, the VI/VD will hang in the “Provisioning” status, and the only way to tell that something went wrong will be by checking the importer pod logs.
```changes
section: core
type: feature
summary: Promote vd/vi import error if url is broken.
```
=> feat(core): promote vd/vi import error if url is broken

images/virtualization-artifact/pkg/controller/conditions/builder.go, tests/e2e/default_config.yaml
Fix setting LastTransitionTime in condition if reason changed.
```changes
section: core
type: fix
summary: Fix setting LastTransitionTime in condition if reason changed.
```
=> fix(core): fix setting LastTransitionTime in condition if reason changed
